#ifndef ALMOG_PLATFORM_LIBRARY_H_
#define ALMOG_PLATFORM_LIBRARY_H_


#endif /* ALMOG_PLATFORM_LIBRARY_H_*/

#ifdef ALMOG_PLATFORM_LIBRARY_IMPLEMENTATION
#undef ALMOG_PLATFORM_LIBRARY_IMPLEMENTATION



#endif /* ALMOG_PLATFORM_LIBRARY_IMPLEMENTATION*/