Matrix3D.h File Reference
Single-header 3D matrix (tensor) utilities for contiguous float data.
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
Classes
struct Mat3D
Contiguous 3D float matrix (tensor).
Macros
#define MATRIX3D_MALLOC malloc
Allocation function used by mat3D_alloc.
#define MATRIX3D_ASSERT assert
Assertion macro used for parameter and allocation checks.
#define MAT3D_AT(m, i, j, k) (m).elements[((i)*(m).cols + (j))*(m).layers + (k)]
Lvalue (Locator value) access to element at (i, j, k).
#define MAT3D_PRINT(m) mat3D_print(m, #m, 0)
Convenience macro to print a Mat3D with its variable name and no left padding.
Functions
float mat3D_rand_float (void)
Generate a pseudo-random float in [0, 1].
Mat3D mat3D_alloc (size_t rows, size_t cols, size_t layers)
Allocate a 3D matrix with the given shape.
void mat3D_free (Mat3D m)
Free the memory owned by a Mat3D.
void mat3D_fill (Mat3D m, float x)
Fill all elements with a constant value.
void mat3D_rand (Mat3D m, float low, float high)
Fill all elements with random values in [low, high].
void mat3D_sum (Mat3D dst, Mat3D a)
Element-wise addition: dst += a.
void mat3D_mult (Mat3D m, float factor)
In-place scaling by an integer factor: m *= factor.
void mat3D_print (Mat3D m, const char *name, size_t padding)
Print the matrix with a name and left padding.
void mat3D_identity_mat (Mat3D m)
Set m to the 3D identity tensor (Kronecker delta).
void mat3D_copy (Mat3D res, Mat3D src)
Copy all elements from src to res.
Detailed Description
Single-header 3D matrix (tensor) utilities for contiguous float data.
Matrix3D is a minimal, dependency-free C library for working with dense 3D arrays (tensors) of floats. It provides allocation, initialization, random filling, element-wise addition, scaling, identity construction, copying, and pretty-printing.
Memory layout is row-major with the following linearization: index(i, j, k) = ((i * cols) + j) * layers + k
i in [0, rows)
j in [0, cols)
k in [0, layers)
k is the fastest-varying dimension.
Usage:
In exactly one translation unit, define MATRIX3D_IMPLEMENTATION before including this header to get the function definitions.
In all other translation units, include this header without the define.
Example:
#define MATRIX3D_IMPLEMENTATION
#include "matrix3d.h"
int main(void) {
    Mat3D m = mat3D_alloc(2, 3, 4);
    mat3D_fill(m, 0.0f);
    MAT3D_AT(m, 1, 2, 3) = 42.0f;
    MAT3D_PRINT(m);
    mat3D_free(m);
    return 0;
}
Configuration:
Define MATRIX3D_MALLOC to override the allocator used by mat3D_alloc.
Define MATRIX3D_ASSERT to override assertions.
Thread-safety:
All functions operate on caller-provided objects. There is no internal global state other than the use of C's rand() in mat3D_rand_float and mat3D_rand, which is not thread-safe. Seed with srand() as needed.
Error handling:
By default, allocation failure triggers MATRIX3D_ASSERT. If you need graceful handling, override MATRIX3D_ASSERT.
Note
This one-file library is heavily inspired by Tsoding's nn.h implementation of matrix creation and operation. you can find the source code in: https://github.com/tsoding/nn.h . featured in this video of his: https://youtu.be/L1TbWe8bVOc?list=PLpM-Dvs8t0VZPZKggcql-MmjaBdZKeDMw .
Definition in file Matrix3D.h.
Macro Definition Documentation
MAT3D_AT
#define MAT3D_AT(m, i, j, k) (m).elements[((i)*(m).cols + (j))*(m).layers + (k)]
Lvalue (Locator value) access to element at (i, j, k).
Parameters
m Mat3D lvalue or expression
i Row index in [0, m.rows)
j Column index in [0, m.cols)
k Layer index in [0, m.layers)
Returns
An lvalue reference to the element at (i, j, k).
Warning
The macro evaluates its arguments multiple times. Avoid passing expressions with side effects.
Definition at line 142 of file Matrix3D.h.
MAT3D_PRINT
#define MAT3D_PRINT(m) mat3D_print(m, #m, 0)
Convenience macro to print a Mat3D with its variable name and no left padding.
Parameters
m Mat3D to print.
Definition at line 150 of file Matrix3D.h.
MATRIX3D_ASSERT
#define MATRIX3D_ASSERT assert
Assertion macro used for parameter and allocation checks.
Defaults to assert. You may override it to integrate with your project's error handling or to disable assertions in production builds.
Definition at line 89 of file Matrix3D.h.
MATRIX3D_MALLOC
#define MATRIX3D_MALLOC malloc
Allocation function used by mat3D_alloc.
Defaults to malloc. You may override this macro before including the header to provide a custom allocator (e.g., an arena or tracking allocator). The memory must be free()'able by mat3D_free (which calls free()) unless you also replace mat3D_free.
Definition at line 76 of file Matrix3D.h.
Function Documentation
mat3D_alloc()
Mat3D mat3D_alloc (size_t rows, size_t cols, size_t layers)
Allocate a 3D matrix with the given shape.
Parameters
rows Number of rows (i dimension).
cols Number of columns (j dimension).
layers Number of layers (k dimension).
Returns
Mat3D with allocated elements and initialized metadata.
Precondition
rows * cols * layers > 0. Behavior is undefined for zero-sized allocations due to assertion on NULL pointers.
Postcondition
m.elements is non-NULL on success (asserts otherwise).
Note
Elements are uninitialized.
See also
mat3D_free
Definition at line 199 of file Matrix3D.h.
References Mat3D::cols, Mat3D::elements, Mat3D::layers, MATRIX3D_ASSERT, MATRIX3D_MALLOC, Mat3D::rows, and Mat3D::stride.
Referenced by main().
mat3D_copy()
void mat3D_copy (Mat3D res, Mat3D src)
Copy all elements from src to res.
Parameters
res Destination matrix.
src Source matrix.
Precondition
res.rows == src.rows, res.cols == src.cols, res.layers == src.layers.
Definition at line 370 of file Matrix3D.h.
References Mat3D::cols, Mat3D::layers, MAT3D_AT, MATRIX3D_ASSERT, and Mat3D::rows.
mat3D_fill()
void mat3D_fill (Mat3D m, float x)
Fill all elements with a constant value.
Parameters
m Destination matrix.
x Value to assign to each element.
Definition at line 231 of file Matrix3D.h.
References Mat3D::cols, Mat3D::layers, MAT3D_AT, and Mat3D::rows.
Referenced by main().
mat3D_free()
void mat3D_free (Mat3D m)
Free the memory owned by a Mat3D.
Parameters
m Mat3D to free.
Postcondition
m.elements becomes invalid after this call.
Note
Safe to call with m.elements == NULL (free(NULL) is a no-op).
Warning
Do not double-free the same Mat3D.
Definition at line 220 of file Matrix3D.h.
References Mat3D::elements.
Referenced by main().
mat3D_identity_mat()
void mat3D_identity_mat (Mat3D m)
Set m to the 3D identity tensor (Kronecker delta).
Parameters
m Destination matrix.
Precondition
m.rows == m.cols == m.layers.
Sets element (i, j, k) to 1 when i == j == k, otherwise 0.
Definition at line 345 of file Matrix3D.h.
References Mat3D::cols, Mat3D::layers, MAT3D_AT, MATRIX3D_ASSERT, and Mat3D::rows.
Referenced by main().
mat3D_mult()
void mat3D_mult (Mat3D m, float factor)
In-place scaling by an integer factor: m *= factor.
Parameters
m Matrix to scale.
factor Scale factor (size_t). Elements are multiplied as floats.
Definition at line 290 of file Matrix3D.h.
References Mat3D::cols, Mat3D::layers, MAT3D_AT, and Mat3D::rows.
mat3D_print()
void mat3D_print (Mat3D m, const char * name, size_t padding)
Print the matrix with a name and left padding.
Parameters
m Matrix to print.
name A label to print before the data (e.g., the variable name).
padding Number of spaces of left padding for each printed line.
The output is organized by layers (k), printing each 2D slice with row-wise lines.
Definition at line 312 of file Matrix3D.h.
References Mat3D::cols, Mat3D::layers, MAT3D_AT, and Mat3D::rows.
mat3D_rand()
void mat3D_rand (Mat3D m, float low, float high)
Fill all elements with random values in [low, high].
Parameters
m Destination matrix.
low Lower bound (inclusive).
high Upper bound (exclusive when using typical rand()).
Note
Uses mat3D_rand_float and therefore rand(); not thread-safe.
Definition at line 251 of file Matrix3D.h.
References Mat3D::cols, Mat3D::layers, MAT3D_AT, mat3D_rand_float(), and Mat3D::rows.
mat3D_rand_float()
float mat3D_rand_float (void)
Generate a pseudo-random float in [0, 1].
Uses C's rand() scaled to [0, 1]. The random stream is shared with the process; call srand() if you want a specific seed.
Returns
Random float in [0, 1].
Note
Not thread-safe due to rand().
Definition at line 179 of file Matrix3D.h.
Referenced by mat3D_rand().
mat3D_sum()
void mat3D_sum (Mat3D dst, Mat3D a)
Element-wise addition: dst += a.
Parameters
dst Destination matrix; also the left operand.
a Right operand; must have the same shape as dst.
Precondition
dst.rows == a.rows, dst.cols == a.cols, dst.layers == a.layers.
Definition at line 270 of file Matrix3D.h.
References Mat3D::cols, Mat3D::layers, MAT3D_AT, MATRIX3D_ASSERT, and Mat3D::rows.
Referenced by main().