Almog_Draw_Library.h File Reference
Immediate-mode 2D/3D raster helpers for drawing onto Mat2D_uint32 pixel buffers.
#include <math.h>
#include <stdint.h>
#include <limits.h>
#include <string.h>
#include <float.h>
#include `./Matrix2D.h`
#include `./Almog_Dynamic_Array.h`
#include <assert.h>
Classes
struct Offset_zoom_param
Pan/zoom parameters relative to screen center.
struct Point
Homogeneous 2D/3D point with per-vertex depth (z) and w.
struct Curve
Polyline of points with a uniform color.
struct Curve_ada
Dynamic array of curves (polyline container).
struct Tri
Triangle primitive with optional per-vertex attributes.
struct Quad
Quad primitive with optional per-vertex attributes.
struct Tri_mesh
Dynamic array of triangles (triangle mesh).
struct Quad_mesh
Dynamic array of quads (quad mesh).
struct Figure
Plotting figure holding a pixel buffer, z-buffer and plot state.
struct Grid
Grid definition (as lines) in a chosen plane.
Macros
#define ADL_ASSERT assert
Assertion macro used by this header (defaults to assert).
#define POINT
#define CURVE
#define CURVE_ADA
#define TRI
#define QUAD
#define TRI_MESH
#define QUAD_MESH
#define HexARGB_RGBA(x) ((x)>>(8*2)&0xFF), ((x)>>(8*1)&0xFF), ((x)>>(8*0)&0xFF), ((x)>>(8*3)&0xFF)
#define HexARGB_RGB_VAR(x, r, g, b) r = ((x)>>(8*2)&0xFF); g = ((x)>>(8*1)&0xFF); b = ((x)>>(8*0)&0xFF);
#define HexARGB_RGBA_VAR(x, r, g, b, a) r = ((x)>>(8*2)&0xFF); g = ((x)>>(8*1)&0xFF); b = ((x)>>(8*0)&0xFF); a = ((x)>>(8*3)&0xFF)
#define RGB_hexRGB(r, g, b) (int)(0x010000*(int)(r) + 0x000100*(int)(g) + 0x000001*(int)(b))
#define RGBA_hexARGB(r, g, b, a) (int)(0x01000000l*(int)(fminf(a, 255)) + 0x010000*(int)(r) + 0x000100*(int)(g) + 0x000001*(int)(b))
#define RED_hexARGB 0xFFFF0000
#define GREEN_hexARGB 0xFF00FF00
#define BLUE_hexARGB 0xFF0000FF
#define PURPLE_hexARGB 0xFFFF00FF
#define CYAN_hexARGB 0xFF00FFFF
#define YELLOW_hexARGB 0xFFFFFF00
#define edge_cross_point(a1, b, a2, p) (b.x-a1.x)*(p.y-a2.y)-(b.y-a1.y)*(p.x-a2.x)
#define is_top_edge(x, y) (y == 0 && x > 0)
#define is_left_edge(x, y) (y < 0)
#define is_top_left(ps, pe) (is_top_edge(pe.x-ps.x, pe.y-ps.y) || is_left_edge(pe.x-ps.x, pe.y-ps.y))
#define ADL_MAX_POINT_VAL 1e5
#define adl_assert_point_is_valid(p) ADL_ASSERT(isfinite(p.x) && isfinite(p.y) && isfinite(p.z) && isfinite(p.w))
#define adl_assert_tri_is_valid(tri)
#define adl_assert_quad_is_valid(quad)
#define ADL_FIGURE_PADDING_PRECENTAGE 20
#define ADL_MAX_FIGURE_PADDING 70
#define ADL_MIN_FIGURE_PADDING 20
#define ADL_MAX_HEAD_SIZE 15
#define ADL_FIGURE_HEAD_ANGLE_DEG 30
#define ADL_FIGURE_AXIS_COLOR 0xff000000
#define ADL_MAX_CHARACTER_OFFSET 10
#define ADL_MIN_CHARACTER_OFFSET 5
#define ADL_MAX_SENTENCE_LEN 256
#define ADL_MAX_ZOOM 1e3
#define ADL_DEFAULT_OFFSET_ZOOM (Offset_zoom_param){1,0,0,0,0}
#define adl_offset_zoom_point(p, window_w, window_h, offset_zoom_param)
#define adl_offset2d(i, j, ni) (j) * (ni) + (i)
Functions
void adl_point_draw (Mat2D_uint32 screen_mat, int x, int y, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a single pixel with alpha blending.
void adl_line_draw (Mat2D_uint32 screen_mat, const float x1_input, const float y1_input, const float x2_input, const float y2_input, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw an anti-aliased-like line by vertical spans (integer grid).
void adl_lines_draw (const Mat2D_uint32 screen_mat, const Point *points, const size_t len, const uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a polyline connecting an array of points.
void adl_lines_loop_draw (const Mat2D_uint32 screen_mat, const Point *points, const size_t len, const uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a closed polyline (loop).
void adl_arrow_draw (Mat2D_uint32 screen_mat, int xs, int ys, int xe, int ye, float head_size, float angle_deg, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw an arrow from start to end with a triangular head.
void adl_character_draw (Mat2D_uint32 screen_mat, char c, int width_pixel, int hight_pixel, int x_top_left, int y_top_left, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a vector glyph for a single ASCII character.
void adl_sentence_draw (Mat2D_uint32 screen_mat, const char sentence[], size_t len, const int x_top_left, const int y_top_left, const int hight_pixel, const uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a horizontal sentence using vector glyphs.
void adl_rectangle_draw_min_max (Mat2D_uint32 screen_mat, int min_x, int max_x, int min_y, int max_y, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a rectangle outline defined by min/max corners (inclusive).
void adl_rectangle_fill_min_max (Mat2D_uint32 screen_mat, int min_x, int max_x, int min_y, int max_y, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a rectangle defined by min/max corners (inclusive).
void adl_quad_draw (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw the outline of a quad (four points, looped).
void adl_quad_fill (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a quad using mean-value (Barycentric) coordinates and flat base color.
void adl_quad_fill_interpolate_normal_mean_value (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a quad with per-pixel light interpolation (mean value coords).
void adl_quad_fill_interpolate_color_mean_value (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, Offset_zoom_param offset_zoom_param)
Fill a quad with per-vertex colors (mean value coords).
void adl_quad_mesh_draw (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw outlines for all quads in a mesh.
void adl_quad_mesh_fill (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill all quads in a mesh with a uniform base color.
void adl_quad_mesh_fill_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill all quads in a mesh using interpolated lighting.
void adl_quad_mesh_fill_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, Offset_zoom_param offset_zoom_param)
Fill all quads in a mesh using per-vertex colors.
void adl_circle_draw (Mat2D_uint32 screen_mat, float center_x, float center_y, float r, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw an approximate circle outline (1px thickness).
void adl_circle_fill (Mat2D_uint32 screen_mat, float center_x, float center_y, float r, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a circle.
void adl_tri_draw (Mat2D_uint32 screen_mat, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw the outline of a triangle.
void adl_tri_fill_Pinedas_rasterizer (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a triangle using Pineda's rasterizer with flat base color.
void adl_tri_fill_Pinedas_rasterizer_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, Offset_zoom_param offset_zoom_param)
Fill a triangle using Pineda's rasterizer with per-vertex colors.
void adl_tri_fill_Pinedas_rasterizer_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a triangle with interpolated lighting over a uniform color.
void adl_tri_mesh_draw (Mat2D_uint32 screen_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw outlines for all triangles in a mesh.
void adl_tri_mesh_fill_Pinedas_rasterizer (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill all triangles in a mesh with a uniform base color.
void adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, Offset_zoom_param offset_zoom_param)
Fill all triangles in a mesh with a uniform base color.
void adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill all triangles in a mesh with interpolated lighting.
float adl_tan_half_angle (Point vi, Point vj, Point p, float li, float lj)
Compute tan(alpha/2) for the angle at point p between segments p->vi and p->vj.
float adl_linear_map (float s, float min_in, float max_in, float min_out, float max_out)
Affine map from one scalar range to another (no clamping).
void adl_quad2tris (Quad quad, Tri *tri1, Tri *tri2, char split_line[])
Split a quad into two triangles along a chosen diagonal.
void adl_linear_sRGB_to_okLab (uint32_t hex_ARGB, float *L, float *a, float *b)
Convert a linear sRGB color (ARGB) to Oklab components.
void adl_okLab_to_linear_sRGB (float L, float a, float b, uint32_t *hex_ARGB)
Convert Oklab components to a linear sRGB ARGB color.
void adl_linear_sRGB_to_okLch (uint32_t hex_ARGB, float *L, float *c, float *h_deg)
Convert a linear sRGB color (ARGB) to OkLch components.
void adl_okLch_to_linear_sRGB (float L, float c, float h_deg, uint32_t *hex_ARGB)
Convert OkLch components to a linear sRGB ARGB color.
void adl_interpolate_ARGBcolor_on_okLch (uint32_t color1, uint32_t color2, float t, float num_of_rotations, uint32_t *color_out)
Interpolate between two ARGB colors in OkLch space.
Figure adl_figure_alloc (size_t rows, size_t cols, Point top_left_position)
Allocate and initialize a Figure with an internal pixel buffer.
void adl_figure_copy_to_screen (Mat2D_uint32 screen_mat, Figure figure)
Blit a Figure's pixels onto a destination screen buffer.
void adl_axis_draw_on_figure (Figure *figure)
Draw X/Y axes with arrowheads into a Figure.
void adl_max_min_values_draw_on_figure (Figure figure)
Draw min/max numeric labels for the current data range.
void adl_curve_add_to_figure (Figure *figure, Point *src_points, size_t src_len, uint32_t color)
Add a curve (polyline) to a Figure and update its data bounds.
void adl_curves_plot_on_figure (Figure figure)
Render all added curves into a Figure's pixel buffer.
void adl_2Dscalar_interp_on_figure (Figure figure, double *x_2Dmat, double *y_2Dmat, double *scalar_2Dmat, int ni, int nj, char color_scale[], float num_of_rotations)
Visualize a scalar field on a Figure by colored quads.
Grid adl_cartesian_grid_create (float min_e1, float max_e1, float min_e2, float max_e2, int num_samples_e1, int num_samples_e2, char plane[], float third_direction_position)
Create a Cartesian grid (as curves) on one of the principal planes.
void adl_grid_draw (Mat2D_uint32 screen_mat, Grid grid, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a previously created Grid as line segments.
Detailed Description
Immediate-mode 2D/3D raster helpers for drawing onto Mat2D_uint32 pixel buffers.
This single-header library provides a minimal software rasterizer for drawing into a 32-bit ARGB pixel buffer (Mat2D_uint32). It supports:
Points, lines, circles, triangles and quads (wire and filled)
Z-buffered triangle/quad rasterization (inverse-Z convention)
Per-vertex color and simple light-intensity interpolation
Basic vector-text drawing (ASCII subset)
Plotting helper types (Figure) and utilities for curve plots and 2D scalar-field visualization using perceptual color interpolation in the OKLab/OKLch color spaces
Cartesian grid generation in common planes
All draw calls may accept an Offset_zoom_param that enables simple pan/zoom behavior around the screen center.
Types Mat2D and Mat2D_uint32 are provided by Matrix2D.h.
Usage:
Include this header wherever you use the API.
In exactly one translation unit (source file) define ALMOG_DRAW_LIBRARY_IMPLEMENTATION before including this header to compile the function definitions.
Note
Colors are ARGB in 0xAARRGGBB packed 32-bit format.
Z buffering uses an inverse-Z buffer (bigger is closer).
The OKLab/OKLch conversions here assume linear sRGB channels.
Definition in file Almog_Draw_Library.h.
Macro Definition Documentation
ADL_ASSERT
#define ADL_ASSERT assert
Assertion macro used by this header (defaults to assert).
Define ADL_ASSERT before including this file to override. When NDEBUG is defined, standard assert() is disabled.
Definition at line 55 of file Almog_Draw_Library.h.
adl_assert_point_is_valid
#define adl_assert_point_is_valid(p) ADL_ASSERT(isfinite(p.x) && isfinite(p.y) && isfinite(p.z) && isfinite(p.w))
Definition at line 310 of file Almog_Draw_Library.h.
adl_assert_quad_is_valid
#define adl_assert_quad_is_valid(quad)
Value:
        adl_assert_point_is_valid(quad.points[0]); \
        adl_assert_point_is_valid(quad.points[1]); \
        adl_assert_point_is_valid(quad.points[2]); \
        adl_assert_point_is_valid(quad.points[3])
Definition at line 314 of file Almog_Draw_Library.h.
adl_assert_tri_is_valid
#define adl_assert_tri_is_valid(tri)
Value:
        adl_assert_point_is_valid(tri.points[0]); \
        adl_assert_point_is_valid(tri.points[1]); \
        adl_assert_point_is_valid(tri.points[2])
Definition at line 311 of file Almog_Draw_Library.h.
ADL_DEFAULT_OFFSET_ZOOM
#define ADL_DEFAULT_OFFSET_ZOOM (Offset_zoom_param){1,0,0,0,0}
Definition at line 331 of file Almog_Draw_Library.h.
ADL_FIGURE_AXIS_COLOR
#define ADL_FIGURE_AXIS_COLOR 0xff000000
Definition at line 324 of file Almog_Draw_Library.h.
ADL_FIGURE_HEAD_ANGLE_DEG
#define ADL_FIGURE_HEAD_ANGLE_DEG 30
Definition at line 323 of file Almog_Draw_Library.h.
ADL_FIGURE_PADDING_PRECENTAGE
#define ADL_FIGURE_PADDING_PRECENTAGE 20
Definition at line 319 of file Almog_Draw_Library.h.
ADL_MAX_CHARACTER_OFFSET
#define ADL_MAX_CHARACTER_OFFSET 10
Definition at line 326 of file Almog_Draw_Library.h.
ADL_MAX_FIGURE_PADDING
#define ADL_MAX_FIGURE_PADDING 70
Definition at line 320 of file Almog_Draw_Library.h.
ADL_MAX_HEAD_SIZE
#define ADL_MAX_HEAD_SIZE 15
Definition at line 322 of file Almog_Draw_Library.h.
ADL_MAX_POINT_VAL
#define ADL_MAX_POINT_VAL 1e5
Definition at line 309 of file Almog_Draw_Library.h.
ADL_MAX_SENTENCE_LEN
#define ADL_MAX_SENTENCE_LEN 256
Definition at line 328 of file Almog_Draw_Library.h.
ADL_MAX_ZOOM
#define ADL_MAX_ZOOM 1e3
Definition at line 329 of file Almog_Draw_Library.h.
ADL_MIN_CHARACTER_OFFSET
#define ADL_MIN_CHARACTER_OFFSET 5
Definition at line 327 of file Almog_Draw_Library.h.
ADL_MIN_FIGURE_PADDING
#define ADL_MIN_FIGURE_PADDING 20
Definition at line 321 of file Almog_Draw_Library.h.
adl_offset2d
#define adl_offset2d(i, j, ni) (j) * (ni) + (i)
Definition at line 2294 of file Almog_Draw_Library.h.
adl_offset_zoom_point
#define adl_offset_zoom_point(p, window_w, window_h, offset_zoom_param)
Value:
    (p).x = ((p).x - (window_w)/2 + offset_zoom_param.offset_x) * offset_zoom_param.zoom_multiplier + (window_w)/2; \
    (p).y = ((p).y - (window_h)/2 + offset_zoom_param.offset_y) * offset_zoom_param.zoom_multiplier + (window_h)/2
Definition at line 332 of file Almog_Draw_Library.h.
BLUE_hexARGB
#define BLUE_hexARGB 0xFF0000FF
Definition at line 299 of file Almog_Draw_Library.h.
CURVE
#define CURVE
Definition at line 90 of file Almog_Draw_Library.h.
CURVE_ADA
#define CURVE_ADA
Definition at line 103 of file Almog_Draw_Library.h.
CYAN_hexARGB
#define CYAN_hexARGB 0xFF00FFFF
Definition at line 301 of file Almog_Draw_Library.h.
edge_cross_point
#define edge_cross_point(a1, b, a2, p) (b.x-a1.x)*(p.y-a2.y)-(b.y-a1.y)*(p.x-a2.x)
Definition at line 304 of file Almog_Draw_Library.h.
GREEN_hexARGB
#define GREEN_hexARGB 0xFF00FF00
Definition at line 298 of file Almog_Draw_Library.h.
HexARGB_RGB_VAR
#define HexARGB_RGB_VAR(x, r, g, b) r = ((x)>>(8*2)&0xFF); g = ((x)>>(8*1)&0xFF); b = ((x)>>(8*0)&0xFF);
Definition at line 224 of file Almog_Draw_Library.h.
HexARGB_RGBA
#define HexARGB_RGBA(x) ((x)>>(8*2)&0xFF), ((x)>>(8*1)&0xFF), ((x)>>(8*0)&0xFF), ((x)>>(8*3)&0xFF)
Definition at line 221 of file Almog_Draw_Library.h.
HexARGB_RGBA_VAR
#define HexARGB_RGBA_VAR(x, r, g, b, a) r = ((x)>>(8*2)&0xFF); g = ((x)>>(8*1)&0xFF); b = ((x)>>(8*0)&0xFF); a = ((x)>>(8*3)&0xFF)
Definition at line 227 of file Almog_Draw_Library.h.
is_left_edge
#define is_left_edge(x, y) (y < 0)
Definition at line 306 of file Almog_Draw_Library.h.
is_top_edge
#define is_top_edge(x, y) (y == 0 && x > 0)
Definition at line 305 of file Almog_Draw_Library.h.
is_top_left
#define is_top_left(ps, pe) (is_top_edge(pe.x-ps.x, pe.y-ps.y) || is_left_edge(pe.x-ps.x, pe.y-ps.y))
Definition at line 307 of file Almog_Draw_Library.h.
POINT
#define POINT
Definition at line 74 of file Almog_Draw_Library.h.
PURPLE_hexARGB
#define PURPLE_hexARGB 0xFFFF00FF
Definition at line 300 of file Almog_Draw_Library.h.
QUAD
#define QUAD
Definition at line 130 of file Almog_Draw_Library.h.
QUAD_MESH
#define QUAD_MESH
Definition at line 156 of file Almog_Draw_Library.h.
RED_hexARGB
#define RED_hexARGB 0xFFFF0000
Definition at line 297 of file Almog_Draw_Library.h.
RGB_hexRGB
#define RGB_hexRGB(r, g, b) (int)(0x010000*(int)(r) + 0x000100*(int)(g) + 0x000001*(int)(b))
Definition at line 230 of file Almog_Draw_Library.h.
RGBA_hexARGB
#define RGBA_hexARGB(r, g, b, a) (int)(0x01000000l*(int)(fminf(a, 255)) + 0x010000*(int)(r) + 0x000100*(int)(g) + 0x000001*(int)(b))
Definition at line 233 of file Almog_Draw_Library.h.
TRI
#define TRI
Definition at line 115 of file Almog_Draw_Library.h.
TRI_MESH
#define TRI_MESH
Definition at line 144 of file Almog_Draw_Library.h.
YELLOW_hexARGB
#define YELLOW_hexARGB 0xFFFFFF00
Definition at line 302 of file Almog_Draw_Library.h.
Function Documentation
adl_2Dscalar_interp_on_figure()
void adl_2Dscalar_interp_on_figure (Figure figure, double * x_2Dmat, double * y_2Dmat, double * scalar_2Dmat, int ni, int nj, char color_scale[], float num_of_rotations)
Visualize a scalar field on a Figure by colored quads.
Treats x_2Dmat and y_2Dmat as a structured 2D grid of positions (column-major with stride ni) and colors each cell using scalar_2Dmat mapped through a two-color OkLch gradient. Also updates figure bounds from the provided data. Depth-tested inside the figure's buffers.
Parameters
figure Figure to render into (uses its own pixel buffers).
x_2Dmat Grid X coordinates, size ni*nj.
y_2Dmat Grid Y coordinates, size ni*nj.
scalar_2Dmat Scalar values per grid node, size ni*nj.
ni Number of samples along the first index (rows).
nj Number of samples along the second index (cols).
color_scale Two-letter code of endpoints (`b-c`,`b-g`,`b-r`, `b-y`,`g-y`,`g-p`,`g-r`,`r-y`).
num_of_rotations Hue turns for the OkLch interpolation (can be fractional/negative).
Definition at line 2314 of file Almog_Draw_Library.h.
References adl_axis_draw_on_figure(), ADL_DEFAULT_OFFSET_ZOOM, adl_interpolate_ARGBcolor_on_okLch(), adl_linear_map(), adl_max_min_values_draw_on_figure(), adl_offset2d, adl_offset_zoom_point, adl_quad_fill_interpolate_color_mean_value(), Figure::background_color, BLUE_hexARGB, Quad::colors, Mat2D::cols, Mat2D_uint32::cols, CYAN_hexARGB, Mat2D::elements, GREEN_hexARGB, Figure::inv_z_buffer_mat, Quad::light_intensity, mat2D_fill_uint32(), Figure::max_x, Figure::max_x_pixel, Figure::max_y, Figure::max_y_pixel, Figure::min_x, Figure::min_x_pixel, Figure::min_y, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Quad::points, PURPLE_hexARGB, RED_hexARGB, Mat2D::rows, Mat2D_uint32::rows, Quad::to_draw, Figure::to_draw_axis, Figure::to_draw_max_min_values, Point::w, Point::x, Point::y, YELLOW_hexARGB, and Point::z.
adl_arrow_draw()
void adl_arrow_draw (Mat2D_uint32 screen_mat, int xs, int ys, int xe, int ye, float head_size, float angle_deg, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw an arrow from start to end with a triangular head.
The head is constructed by rotating around the arrow tip by +/- angle_deg and using head_size as a fraction of the shaft length.
Note
: This function is a bit complicated and expansive but this is what I could come up with
Parameters
screen_mat Destination ARGB pixel buffer.
xs Start X (before pan/zoom).
ys Start Y (before pan/zoom).
xe End X (before pan/zoom), i.e., the arrow tip.
ye End Y (before pan/zoom), i.e., the arrow tip.
head_size Head size as a fraction of total length in [0,1].
angle_deg Head wing rotation angle in degrees.
color Arrow color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 518 of file Almog_Draw_Library.h.
References adl_line_draw(), mat2D_add(), mat2D_alloc(), MAT2D_AT, mat2D_copy(), mat2D_dot(), mat2D_fill(), mat2D_free(), mat2D_set_rot_mat_z(), and mat2D_sub().
Referenced by adl_axis_draw_on_figure().
adl_axis_draw_on_figure()
void adl_axis_draw_on_figure (Figure * figure)
Draw X/Y axes with arrowheads into a Figure.
Uses the current figure's pixel extents and padding to place axes, and stores the computed head sizes for later label layout.
Parameters
figure [in,out] Figure to draw onto.
Definition at line 2144 of file Almog_Draw_Library.h.
References adl_arrow_draw(), ADL_FIGURE_AXIS_COLOR, ADL_FIGURE_HEAD_ANGLE_DEG, ADL_FIGURE_PADDING_PRECENTAGE, ADL_MAX_FIGURE_PADDING, ADL_MAX_HEAD_SIZE, ADL_MIN_FIGURE_PADDING, Mat2D_uint32::cols, Figure::max_x_pixel, Figure::max_y_pixel, Figure::min_x_pixel, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Mat2D_uint32::rows, Figure::x_axis_head_size, and Figure::y_axis_head_size.
Referenced by adl_2Dscalar_interp_on_figure(), and adl_curves_plot_on_figure().
adl_cartesian_grid_create()
Grid adl_cartesian_grid_create (float min_e1, float max_e1, float min_e2, float max_e2, int num_samples_e1, int num_samples_e2, char plane[], float third_direction_position)
Create a Cartesian grid (as curves) on one of the principal planes.
Supported planes (case-insensitive): `XY`,`xy`,`XZ`,`xz`,`YX`,`yx`,`YZ`,`yz`,`ZX`,`zx`,`ZY`,`zy`. The third_direction_position places the grid along the axis normal to the plane (e.g., Z for `XY`).
Parameters
min_e1 Minimum coordinate along the first axis of the plane.
max_e1 Maximum coordinate along the first axis of the plane.
min_e2 Minimum coordinate along the second axis of the plane.
max_e2 Maximum coordinate along the second axis of the plane.
num_samples_e1 Number of segments along first axis.
num_samples_e2 Number of segments along second axis.
plane Plane code string (`XY`,`xy`,`XZ`,`xz`,`YX`,`yx`,`YZ`,`yz`,`ZX`,`zx`,`ZY`,`zy`).
third_direction_position Position along the axis normal to plane.
Returns
Grid structure containing the generated curves and spacing.
Definition at line 2513 of file Almog_Draw_Library.h.
References ada_appand, ada_init_array, Grid::curves, Grid::de1, Grid::de2, Grid::max_e1, Grid::max_e2, Grid::min_e1, Grid::min_e2, Grid::num_samples_e1, Grid::num_samples_e2, Grid::plane, Point::w, Point::x, Point::y, and Point::z.
adl_character_draw()
void adl_character_draw (Mat2D_uint32 screen_mat, char c, int width_pixel, int hight_pixel, int x_top_left, int y_top_left, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a vector glyph for a single ASCII character.
Only a limited set of characters is supported (AZ, az, 09, space, '.', ':', '-', '+'). Unsupported characters are rendered as a framed box with an 'X'. Coordinates are for the character's top-left corner.
Parameters
screen_mat Destination ARGB pixel buffer.
c The character to draw.
width_pixel Character box width in pixels.
hight_pixel Character box height in pixels (spelled as in API).
x_top_left X of top-left corner (before pan/zoom).
y_top_left Y of top-left corner (before pan/zoom).
color Stroke color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 586 of file Almog_Draw_Library.h.
References adl_line_draw(), adl_rectangle_draw_min_max(), and adl_rectangle_fill_min_max().
Referenced by adl_sentence_draw(), and render().
adl_circle_draw()
void adl_circle_draw (Mat2D_uint32 screen_mat, float center_x, float center_y, float r, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw an approximate circle outline (1px thickness).
The outline is approximated on the integer grid by sampling a band around radius r.
Parameters
screen_mat Destination ARGB pixel buffer.
center_x Circle center X (before pan/zoom).
center_y Circle center Y (before pan/zoom).
r Circle radius in pixels.
color Stroke color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1427 of file Almog_Draw_Library.h.
References adl_point_draw().
adl_circle_fill()
void adl_circle_fill (Mat2D_uint32 screen_mat, float center_x, float center_y, float r, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a circle.
Parameters
screen_mat Destination ARGB pixel buffer.
center_x Circle center X (before pan/zoom).
center_y Circle center Y (before pan/zoom).
r Circle radius in pixels.
color Fill color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1449 of file Almog_Draw_Library.h.
References adl_point_draw().
adl_curve_add_to_figure()
void adl_curve_add_to_figure (Figure * figure, Point * src_points, size_t src_len, uint32_t color)
Add a curve (polyline) to a Figure and update its data bounds.
The input points are copied into the figure's source curve array with the given color. Figure min/max bounds are updated to include them.
Parameters
figure [in,out] Target figure.
src_points Array of source points (in data space).
src_len Number of points.
color Curve color (0xAARRGGBB).
Definition at line 2230 of file Almog_Draw_Library.h.
References ada_appand, ada_init_array, Curve::color, Figure::max_x, Figure::max_y, Figure::min_x, Figure::min_y, Figure::src_curve_array, Point::x, and Point::y.
Referenced by setup().
adl_curves_plot_on_figure()
void adl_curves_plot_on_figure (Figure figure)
Render all added curves into a Figure's pixel buffer.
Clears the pixel buffer to background_color, draws axes if enabled, maps data-space points to pixel-space using current min/max bounds, draws the polylines, and optionally draws min/max labels.
Parameters
figure Figure to render into (uses its own pixel buffer).
Definition at line 2265 of file Almog_Draw_Library.h.
References adl_axis_draw_on_figure(), adl_line_draw(), adl_linear_map(), adl_max_min_values_draw_on_figure(), Figure::background_color, Curve::color, Mat2D::cols, Curve::elements, Curve_ada::elements, Mat2D::elements, Figure::inv_z_buffer_mat, Curve::length, Curve_ada::length, mat2D_fill_uint32(), Figure::max_x, Figure::max_x_pixel, Figure::max_y, Figure::max_y_pixel, Figure::min_x, Figure::min_x_pixel, Figure::min_y, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Mat2D::rows, Figure::src_curve_array, Figure::to_draw_axis, Figure::to_draw_max_min_values, Point::x, and Point::y.
Referenced by render().
adl_figure_alloc()
Figure adl_figure_alloc (size_t rows, size_t cols, Point top_left_position)
Allocate and initialize a Figure with an internal pixel buffer.
Initializes the pixel buffer (rows x cols), an inverse-Z buffer (zeroed), an empty source curve array, and default padding/axes bounds. The background_color, to_draw_axis, and to_draw_max_min_values should be set by the caller before rendering.
Parameters
rows Height of the figure in pixels.
cols Width of the figure in pixels.
top_left_position Target position when copying to a screen.
Returns
A new Figure with allocated buffers.
Definition at line 2081 of file Almog_Draw_Library.h.
References ada_init_array, ADL_ASSERT, adl_assert_point_is_valid, ADL_DEFAULT_OFFSET_ZOOM, ADL_FIGURE_PADDING_PRECENTAGE, ADL_MAX_FIGURE_PADDING, Mat2D::cols, Mat2D_uint32::cols, Mat2D::elements, Figure::inv_z_buffer_mat, mat2D_alloc(), mat2D_alloc_uint32(), Figure::max_x, Figure::max_x_pixel, Figure::max_y, Figure::max_y_pixel, Figure::min_x, Figure::min_x_pixel, Figure::min_y, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Mat2D::rows, Mat2D_uint32::rows, Figure::src_curve_array, and Figure::top_left_position.
Referenced by setup().
adl_figure_copy_to_screen()
void adl_figure_copy_to_screen (Mat2D_uint32 screen_mat, Figure figure)
Blit a Figure's pixels onto a destination screen buffer.
Performs per-pixel blending using adl_point_draw and the identity transform. The figure's top_left_position is used as the destination offset.
Parameters
screen_mat Destination ARGB pixel buffer.
figure Source figure to copy from.
Definition at line 2124 of file Almog_Draw_Library.h.
References adl_point_draw(), Mat2D_uint32::cols, MAT2D_AT_UINT32, Figure::pixels_mat, Mat2D_uint32::rows, Figure::top_left_position, Point::x, and Point::y.
Referenced by render().
adl_grid_draw()
void adl_grid_draw (Mat2D_uint32 screen_mat, Grid grid, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a previously created Grid as line segments.
Parameters
screen_mat Destination ARGB pixel buffer.
grid Grid to draw (curves are 2-point polylines).
color Line color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 2791 of file Almog_Draw_Library.h.
References adl_lines_draw(), Grid::curves, Curve::elements, Curve_ada::elements, Curve::length, and Curve_ada::length.
adl_interpolate_ARGBcolor_on_okLch()
void adl_interpolate_ARGBcolor_on_okLch (uint32_t color1, uint32_t color2, float t, float num_of_rotations, uint32_t * color_out)
Interpolate between two ARGB colors in OkLch space.
Lightness and chroma are interpolated linearly. Hue is interpolated in degrees after adding 360*num_of_rotations to the second hue, allowing control over the winding direction.
Parameters
color1 Start color (0xAARRGGBB).
color2 End color (0xAARRGGBB).
t Interpolation factor in [0,1].
num_of_rotations Number of hue turns to add to color2 (can be fractional/negative).
color_out [out] Interpolated ARGB color (A=255).
Definition at line 2053 of file Almog_Draw_Library.h.
References adl_linear_sRGB_to_okLch(), and adl_okLch_to_linear_sRGB().
Referenced by adl_2Dscalar_interp_on_figure().
adl_line_draw()
void adl_line_draw (Mat2D_uint32 screen_mat, const float x1_input, const float y1_input, const float x2_input, const float y2_input, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw an anti-aliased-like line by vertical spans (integer grid).
The line is rasterized with a simple integer-span approach. Pan/zoom is applied about the screen center prior to rasterization.
Parameters
screen_mat Destination ARGB pixel buffer.
x1_input Line start X (before pan/zoom).
y1_input Line start Y (before pan/zoom).
x2_input Line end X (before pan/zoom).
y2_input Line end Y (before pan/zoom).
color Line color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 383 of file Almog_Draw_Library.h.
References ADL_ASSERT, ADL_MAX_POINT_VAL, adl_point_draw(), Mat2D_uint32::cols, Offset_zoom_param::offset_x, Offset_zoom_param::offset_y, Mat2D_uint32::rows, and Offset_zoom_param::zoom_multiplier.
Referenced by adl_arrow_draw(), adl_character_draw(), adl_curves_plot_on_figure(), adl_lines_draw(), adl_lines_loop_draw(), adl_rectangle_draw_min_max(), adl_rectangle_fill_min_max(), and adl_tri_draw().
adl_linear_map()
float adl_linear_map (float s, float min_in, float max_in, float min_out, float max_out)
Affine map from one scalar range to another (no clamping).
Parameters
s Input value.
min_in Input range minimum.
max_in Input range maximum.
min_out Output range minimum.
max_out Output range maximum.
Returns
Mapped value in the output range (may exceed if s is out-of-range).
Definition at line 1865 of file Almog_Draw_Library.h.
Referenced by adl_2Dscalar_interp_on_figure(), adl_curves_plot_on_figure(), and render().
adl_linear_sRGB_to_okLab()
void adl_linear_sRGB_to_okLab (uint32_t hex_ARGB, float * L, float * a, float * b)
Convert a linear sRGB color (ARGB) to Oklab components.
Oklab components are returned in ranges: L in [0,1], a in [-0.5,0.5], b in [-0.5,0.5] (typical). Input is assumed to be linear sRGB.
Parameters
hex_ARGB Input color (0xAARRGGBB). Alpha is ignored.
L [out] Perceptual lightness.
a [out] First opponent axis.
b [out] Second opponent axis.
Definition at line 1945 of file Almog_Draw_Library.h.
References HexARGB_RGB_VAR.
Referenced by adl_linear_sRGB_to_okLch().
adl_linear_sRGB_to_okLch()
void adl_linear_sRGB_to_okLch (uint32_t hex_ARGB, float * L, float * c, float * h_deg)
Convert a linear sRGB color (ARGB) to OkLch components.
Parameters
hex_ARGB Input color (0xAARRGGBB). Alpha is ignored.
L [out] Lightness in [0,1].
c [out] Chroma (non-negative).
h_deg [out] Hue angle in degrees [-180,180] from atan2.
Definition at line 2012 of file Almog_Draw_Library.h.
References adl_linear_sRGB_to_okLab(), and PI.
Referenced by adl_interpolate_ARGBcolor_on_okLch().
adl_lines_draw()
void adl_lines_draw (const Mat2D_uint32 screen_mat, const Point * points, const size_t len, const uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a polyline connecting an array of points.
Draws segments between consecutive points: p[0]-p[1]-...-p[len-1].
Parameters
screen_mat Destination ARGB pixel buffer.
points Array of points in pixel space (before pan/zoom).
len Number of points in the array (>= 1).
color Line color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 470 of file Almog_Draw_Library.h.
References adl_line_draw(), and points.
Referenced by adl_grid_draw().
adl_lines_loop_draw()
void adl_lines_loop_draw (const Mat2D_uint32 screen_mat, const Point * points, const size_t len, const uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a closed polyline (loop).
Same as adl_lines_draw, plus an extra segment from the last point back to the first point.
Parameters
screen_mat Destination ARGB pixel buffer.
points Array of points in pixel space (before pan/zoom).
len Number of points in the array (>= 1).
color Line color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 490 of file Almog_Draw_Library.h.
References adl_line_draw(), and points.
Referenced by adl_quad_draw().
adl_max_min_values_draw_on_figure()
void adl_max_min_values_draw_on_figure (Figure figure)
Draw min/max numeric labels for the current data range.
Renders textual min/max values for both axes inside the figure area. Assumes figure.min_x/max_x/min_y/max_y have been populated.
Parameters
figure Figure whose labels are drawn into its own pixel buffer.
Definition at line 2170 of file Almog_Draw_Library.h.
References ADL_FIGURE_AXIS_COLOR, ADL_MAX_CHARACTER_OFFSET, ADL_MIN_CHARACTER_OFFSET, adl_sentence_draw(), Figure::max_x, Figure::max_x_pixel, Figure::max_y, Figure::max_y_pixel, Figure::min_x, Figure::min_x_pixel, Figure::min_y, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Mat2D_uint32::rows, Figure::x_axis_head_size, and Figure::y_axis_head_size.
Referenced by adl_2Dscalar_interp_on_figure(), and adl_curves_plot_on_figure().
adl_okLab_to_linear_sRGB()
void adl_okLab_to_linear_sRGB (float L, float a, float b, uint32_t * hex_ARGB)
Convert Oklab components to a linear sRGB ARGB color.
Output RGB components are clamped to [0,255], alpha is set to 255.
Parameters
L Oklab lightness.
a Oklab a component.
b Oklab b component.
hex_ARGB [out] Output color (0xAARRGGBB, A=255).
Definition at line 1980 of file Almog_Draw_Library.h.
References RGBA_hexARGB.
Referenced by adl_okLch_to_linear_sRGB().
adl_okLch_to_linear_sRGB()
void adl_okLch_to_linear_sRGB (float L, float c, float h_deg, uint32_t * hex_ARGB)
Convert OkLch components to a linear sRGB ARGB color.
Hue is wrapped to [0,360). Output RGB is clamped to [0,255], alpha=255.
Parameters
L Lightness.
c Chroma.
h_deg Hue angle in degrees.
hex_ARGB [out] Output color (0xAARRGGBB, A=255).
Definition at line 2031 of file Almog_Draw_Library.h.
References adl_okLab_to_linear_sRGB(), and PI.
Referenced by adl_interpolate_ARGBcolor_on_okLch().
adl_point_draw()
void adl_point_draw (Mat2D_uint32 screen_mat, int x, int y, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a single pixel with alpha blending.
Applies the pan/zoom transform and writes the pixel if it falls inside the destination bounds. The source color is blended over the existing pixel using the source alpha; the stored alpha is set to 255.
Parameters
screen_mat Destination ARGB pixel buffer.
x X coordinate in pixels (before pan/zoom).
y Y coordinate in pixels (before pan/zoom).
color Source color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 350 of file Almog_Draw_Library.h.
References Mat2D_uint32::cols, HexARGB_RGBA_VAR, MAT2D_AT_UINT32, Offset_zoom_param::offset_x, Offset_zoom_param::offset_y, RGBA_hexARGB, Mat2D_uint32::rows, and Offset_zoom_param::zoom_multiplier.
Referenced by adl_circle_draw(), adl_circle_fill(), adl_figure_copy_to_screen(), adl_line_draw(), adl_quad_fill(), adl_quad_fill_interpolate_color_mean_value(), adl_quad_fill_interpolate_normal_mean_value(), adl_tri_fill_Pinedas_rasterizer(), adl_tri_fill_Pinedas_rasterizer_interpolate_color(), and adl_tri_fill_Pinedas_rasterizer_interpolate_normal().
adl_quad2tris()
void adl_quad2tris (Quad quad, Tri * tri1, Tri * tri2, char split_line[])
Split a quad into two triangles along a chosen diagonal.
The split is controlled by split_line:
`02` splits along diagonal from vertex 0 to vertex 2.
`13` splits along diagonal from vertex 1 to vertex 3.
The function copies positions, per-vertex colors, light_intensity, and the to_draw flag into the output triangles.
Parameters
quad Input quad.
tri1 [out] First output triangle.
tri2 [out] Second output triangle.
split_line Null-terminated code: `02` or `13`.
Definition at line 1885 of file Almog_Draw_Library.h.
References Tri::colors, Quad::colors, Tri::light_intensity, Quad::light_intensity, Tri::points, Quad::points, Tri::to_draw, and Quad::to_draw.
adl_quad_draw()
void adl_quad_draw (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw the outline of a quad (four points, looped).
Depth buffer is not used in this outline variant.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer Unused for outline; safe to pass a dummy Mat2D.
quad Quad to draw in pixel space (before transform).
color Stroke color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1010 of file Almog_Draw_Library.h.
References adl_lines_loop_draw(), and Quad::points.
Referenced by adl_quad_mesh_draw(), and render().
adl_quad_fill()
void adl_quad_fill (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a quad using mean-value (Barycentric) coordinates and flat base color.
Performs a depth test against inv_z_buffer and modulates the base color with the average light_intensity of the quad's vertices.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer Inverse-Z buffer (larger is closer).
quad Quad in pixel space; points carry z and w for depth.
color Base color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1028 of file Almog_Draw_Library.h.
References adl_point_draw(), Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, Quad::light_intensity, MAT2D_AT, Quad::points, RGBA_hexARGB, Mat2D_uint32::rows, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_quad_mesh_fill().
adl_quad_fill_interpolate_color_mean_value()
void adl_quad_fill_interpolate_color_mean_value (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, Offset_zoom_param offset_zoom_param)
Fill a quad with per-vertex colors (mean value coords).
Interpolates ARGB vertex colors using mean-value coordinates, optionally modulated by the average light_intensity. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer Inverse-Z buffer (larger is closer).
quad Quad in pixel space with quad.colors[] set.
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1216 of file Almog_Draw_Library.h.
References adl_point_draw(), adl_tan_half_angle(), Quad::colors, Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, Quad::light_intensity, MAT2D_AT, Quad::points, RGBA_hexARGB, Mat2D_uint32::rows, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_2Dscalar_interp_on_figure(), adl_quad_mesh_fill_interpolate_color(), and render().
adl_quad_fill_interpolate_normal_mean_value()
void adl_quad_fill_interpolate_normal_mean_value (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a quad with per-pixel light interpolation (mean value coords).
Interpolates light_intensity across the quad using mean-value coordinates and modulates a uniform base color. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer Inverse-Z buffer (larger is closer).
quad Quad in pixel space; points carry z and w for depth.
color Base color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1122 of file Almog_Draw_Library.h.
References adl_point_draw(), adl_tan_half_angle(), Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, Quad::light_intensity, MAT2D_AT, Quad::points, RGBA_hexARGB, Mat2D_uint32::rows, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_quad_mesh_fill_interpolate_normal().
adl_quad_mesh_draw()
void adl_quad_mesh_draw (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw outlines for all quads in a mesh.
Skips elements with to_draw == false. Depth buffer is not used.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer_mat Unused for outline; safe to pass a dummy Mat2D.
mesh Quad mesh (array + length).
color Stroke color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1320 of file Almog_Draw_Library.h.
References adl_assert_quad_is_valid, adl_quad_draw(), Quad_mesh::elements, Quad_mesh::length, and Quad::to_draw.
adl_quad_mesh_fill()
void adl_quad_mesh_fill (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill all quads in a mesh with a uniform base color.
Applies per-quad average light_intensity. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer_mat Inverse-Z buffer (larger is closer).
mesh Quad mesh (array + length).
color Base color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1344 of file Almog_Draw_Library.h.
References adl_assert_quad_is_valid, adl_quad_fill(), Quad_mesh::elements, Quad_mesh::length, and Quad::to_draw.
adl_quad_mesh_fill_interpolate_color()
void adl_quad_mesh_fill_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, Offset_zoom_param offset_zoom_param)
Fill all quads in a mesh using per-vertex colors.
Interpolates quad.colors[] across each quad with mean-value coordinates. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer_mat Inverse-Z buffer (larger is closer).
mesh Quad mesh (array + length).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1401 of file Almog_Draw_Library.h.
References adl_assert_quad_is_valid, adl_quad_fill_interpolate_color_mean_value(), Quad_mesh::elements, Quad_mesh::length, and Quad::to_draw.
adl_quad_mesh_fill_interpolate_normal()
void adl_quad_mesh_fill_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill all quads in a mesh using interpolated lighting.
Interpolates light_intensity across quads and modulates a uniform base color. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer_mat Inverse-Z buffer (larger is closer).
mesh Quad mesh (array + length).
color Base color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1371 of file Almog_Draw_Library.h.
References adl_assert_quad_is_valid, adl_quad_fill_interpolate_normal_mean_value(), Quad_mesh::elements, HexARGB_RGBA_VAR, Quad_mesh::length, and Quad::to_draw.
adl_rectangle_draw_min_max()
void adl_rectangle_draw_min_max (Mat2D_uint32 screen_mat, int min_x, int max_x, int min_y, int max_y, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a rectangle outline defined by min/max corners (inclusive).
Parameters
screen_mat Destination ARGB pixel buffer.
min_x Minimum X (before pan/zoom).
max_x Maximum X (before pan/zoom).
min_y Minimum Y (before pan/zoom).
max_y Maximum Y (before pan/zoom).
color Stroke color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 973 of file Almog_Draw_Library.h.
References adl_line_draw().
Referenced by adl_character_draw().
adl_rectangle_fill_min_max()
void adl_rectangle_fill_min_max (Mat2D_uint32 screen_mat, int min_x, int max_x, int min_y, int max_y, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a rectangle defined by min/max corners (inclusive).
Parameters
screen_mat Destination ARGB pixel buffer.
min_x Minimum X (before pan/zoom).
max_x Maximum X (before pan/zoom).
min_y Minimum Y (before pan/zoom).
max_y Maximum Y (before pan/zoom).
color Fill color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 992 of file Almog_Draw_Library.h.
References adl_line_draw().
Referenced by adl_character_draw().
adl_sentence_draw()
void adl_sentence_draw (Mat2D_uint32 screen_mat, const char sentence[], size_t len, const int x_top_left, const int y_top_left, const int hight_pixel, const uint32_t color, Offset_zoom_param offset_zoom_param)
Draw a horizontal sentence using vector glyphs.
Characters are laid out left-to-right with a spacing derived from the character height. All characters share the same height.
Parameters
screen_mat Destination ARGB pixel buffer.
sentence ASCII string buffer.
len Number of characters to draw from sentence.
x_top_left X of top-left of the first character (before transform).
y_top_left Y of top-left of the first character (before transform).
hight_pixel Character height in pixels (spelled as in API).
color Stroke color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 949 of file Almog_Draw_Library.h.
References adl_character_draw(), ADL_MAX_CHARACTER_OFFSET, and ADL_MIN_CHARACTER_OFFSET.
Referenced by adl_max_min_values_draw_on_figure().
adl_tan_half_angle()
float adl_tan_half_angle (Point vi, Point vj, Point p, float li, float lj)
Compute tan(alpha/2) for the angle at point p between segments p->vi and p->vj.
Uses the identity tan(alpha/2) = |ab| / (|a||b| + ab), where a = vi - p and b = vj - p. The lengths li = |a| and lj = |b| are passed in to avoid recomputation.
Parameters
vi Vertex i.
vj Vertex j.
p Pivot point.
li Precomputed |vi - p|.
lj Precomputed |vj - p|.
Returns
tan(alpha/2) (non-negative).
Definition at line 1845 of file Almog_Draw_Library.h.
References Point::x, and Point::y.
Referenced by adl_quad_fill_interpolate_color_mean_value(), and adl_quad_fill_interpolate_normal_mean_value().
adl_tri_draw()
void adl_tri_draw (Mat2D_uint32 screen_mat, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw the outline of a triangle.
Parameters
screen_mat Destination ARGB pixel buffer.
tri Triangle in pixel space (before transform).
color Stroke color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1469 of file Almog_Draw_Library.h.
References adl_line_draw(), Tri::points, tri, Point::x, and Point::y.
Referenced by adl_tri_mesh_draw(), and render().
adl_tri_fill_Pinedas_rasterizer()
void adl_tri_fill_Pinedas_rasterizer (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a triangle using Pineda's rasterizer with flat base color.
Uses the top-left fill convention and performs a depth test using inverse-Z computed from per-vertex z and w.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer Inverse-Z buffer (larger is closer).
tri Triangle in pixel space; points carry z and w for depth.
color Base color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1492 of file Almog_Draw_Library.h.
References adl_point_draw(), Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, is_top_left, Tri::light_intensity, MAT2D_AT, MATRIX2D_ASSERT, Tri::points, RGBA_hexARGB, Mat2D_uint32::rows, tri, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_tri_mesh_fill_Pinedas_rasterizer().
adl_tri_fill_Pinedas_rasterizer_interpolate_color()
void adl_tri_fill_Pinedas_rasterizer_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, Offset_zoom_param offset_zoom_param)
Fill a triangle using Pineda's rasterizer with per-vertex colors.
Interpolates tri.colors[] and optionally modulates by average light_intensity. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer Inverse-Z buffer (larger is closer).
tri Triangle in pixel space with colors set.
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1573 of file Almog_Draw_Library.h.
References adl_point_draw(), Tri::colors, Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, is_top_left, Tri::light_intensity, MAT2D_AT, MATRIX2D_ASSERT, Tri::points, RGBA_hexARGB, Mat2D_uint32::rows, tri, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_color(), and render().
adl_tri_fill_Pinedas_rasterizer_interpolate_normal()
void adl_tri_fill_Pinedas_rasterizer_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill a triangle with interpolated lighting over a uniform color.
Interpolates light_intensity across the triangle and modulates a uniform base color. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer Inverse-Z buffer (larger is closer).
tri Triangle in pixel space; points carry z and w for depth.
color Base color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1664 of file Almog_Draw_Library.h.
References adl_point_draw(), Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, is_top_left, Tri::light_intensity, MAT2D_AT, MATRIX2D_ASSERT, Tri::points, RGBA_hexARGB, Mat2D_uint32::rows, tri, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal().
adl_tri_mesh_draw()
void adl_tri_mesh_draw (Mat2D_uint32 screen_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Draw outlines for all triangles in a mesh.
Skips elements with to_draw == false.
Parameters
screen_mat Destination ARGB pixel buffer.
mesh Triangle mesh (array + length).
color Stroke color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1746 of file Almog_Draw_Library.h.
References adl_tri_draw(), Tri_mesh::elements, Tri_mesh::length, Tri::to_draw, and tri.
adl_tri_mesh_fill_Pinedas_rasterizer()
void adl_tri_mesh_fill_Pinedas_rasterizer (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill all triangles in a mesh with a uniform base color.
Applies average light_intensity per triangle. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer_mat Inverse-Z buffer (larger is closer).
mesh Triangle mesh (array + length).
color Base color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1768 of file Almog_Draw_Library.h.
References adl_assert_tri_is_valid, adl_tri_fill_Pinedas_rasterizer(), Tri_mesh::elements, Tri_mesh::length, Tri::to_draw, and tri.
adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_color()
void adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, Offset_zoom_param offset_zoom_param)
Fill all triangles in a mesh with a uniform base color.
Applies average light_intensity per triangle. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer_mat Inverse-Z buffer (larger is closer).
mesh Triangle mesh (array + length).
color Base color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1792 of file Almog_Draw_Library.h.
References adl_assert_tri_is_valid, adl_tri_fill_Pinedas_rasterizer_interpolate_color(), Tri_mesh::elements, Tri_mesh::length, Tri::to_draw, and tri.
adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal()
void adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Fill all triangles in a mesh with interpolated lighting.
Interpolates light_intensity across each triangle and modulates a uniform base color. Depth-tested.
Parameters
screen_mat Destination ARGB pixel buffer.
inv_z_buffer_mat Inverse-Z buffer (larger is closer).
mesh Triangle mesh (array + length).
color Base color (0xAARRGGBB).
offset_zoom_param Pan/zoom transform. Use ADL_DEFAULT_OFFSET_ZOOM for identity.
Definition at line 1817 of file Almog_Draw_Library.h.
References adl_assert_tri_is_valid, adl_tri_fill_Pinedas_rasterizer_interpolate_normal(), Tri_mesh::elements, Tri_mesh::length, Tri::to_draw, and tri.