example1.c File Reference
#include `./Almog_Draw_Library.h`
#include `./display.c`
#include `./Matrix2D.h`
Macros
#define SETUP
#define UPDATE
#define RENDER
#define ALMOG_DRAW_LIBRARY_IMPLEMENTATION
#define MATRIX2D_IMPLEMENTATION
Functions
void setup (game_state_t *game_state)
void update (game_state_t *game_state)
void render (game_state_t *game_state)
Variables
Figure figure1
Figure figure2
Curve points
Curve points1
Macro Definition Documentation
ALMOG_DRAW_LIBRARY_IMPLEMENTATION
#define ALMOG_DRAW_LIBRARY_IMPLEMENTATION
Definition at line 4 of file example1.c.
MATRIX2D_IMPLEMENTATION
#define MATRIX2D_IMPLEMENTATION
Definition at line 7 of file example1.c.
RENDER
#define RENDER
Definition at line 3 of file example1.c.
SETUP
#define SETUP
Definition at line 1 of file example1.c.
UPDATE
#define UPDATE
Definition at line 2 of file example1.c.
Function Documentation
render()
void render (game_state_t * game_state)
Definition at line 64 of file example1.c.
References adl_character_draw(), adl_curves_plot_on_figure(), ADL_DEFAULT_OFFSET_ZOOM, adl_figure_copy_to_screen(), figure1, figure2, and game_state_t::window_pixels_mat.
setup()
void setup (game_state_t * game_state)
Definition at line 15 of file example1.c.
References ada_appand, ada_init_array, adl_curve_add_to_figure(), adl_figure_alloc(), Figure::background_color, game_state_t::const_fps, Curve::elements, figure1, figure2, Curve::length, points, points1, Figure::to_draw_axis, and Figure::to_draw_max_min_values.
update()
void update (game_state_t * game_state)
Definition at line 60 of file example1.c.
Variable Documentation
figure1
Figure figure1
Definition at line 11 of file example1.c.
Referenced by render(), and setup().
figure2
Figure figure2
Definition at line 12 of file example1.c.
Referenced by render(), and setup().
points
Curve points
Definition at line 13 of file example1.c.
Referenced by adl_lines_draw(), adl_lines_loop_draw(), and setup().
points1
Curve points1
Definition at line 14 of file example1.c.
Referenced by setup().