Matrix2D.h File Reference
A single-header C library for simple 2D matrix operations on doubles and uint32_t, including allocation, basic arithmetic, linear algebra, and helpers (LUP, inverse, determinant, DCM, etc.).
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <assert.h>
#include <math.h>
Classes
struct Mat2D
Dense row-major matrix of doubles.
struct Mat2D_uint32
Dense row-major matrix of uint32_t.
struct Mat2D_Minor
A minor `view` into a reference matrix.
Macros
#define MATRIX2D_MALLOC malloc
Allocation function used by the library.
#define MATRIX2D_ASSERT assert
Assertion macro used by the library for parameter validation.
#define MAT2D_AT(m, i, j) (m).elements[i * m.stride_r + j]
Access element (i, j) of a Mat2D (0-based).
#define MAT2D_AT_UINT32(m, i, j) (m).elements[i * m.stride_r + j]
Access element (i, j) of a Mat2D_uint32 (0-based).
#define __USE_MISC
#define PI M_PI
#define MAT2D_MINOR_AT(mm, i, j) MAT2D_AT(mm.ref_mat, mm.rows_list[i], mm.cols_list[j])
Access element (i, j) of a Mat2D_Minor (0-based), dereferencing into the underlying reference matrix.
#define MAT2D_PRINT(m) mat2D_print(m, #m, 0)
Convenience macro to print a matrix with its variable name.
#define MAT2D_PRINT_AS_COL(m) mat2D_print_as_col(m, #m, 0)
Convenience macro to print a matrix as a single column with its name.
#define MAT2D_MINOR_PRINT(mm) mat2D_minor_print(mm, #mm, 0)
Convenience macro to print a minor with its variable name.
#define mat2D_normalize(m) mat2D_mult((m), 1.0 / mat2D_calc_norma((m)))
In-place normalization of all elements so that the Frobenius norm becomes 1.
Functions
double mat2D_rand_double (void)
Return a pseudo-random double in the range [0, 1].
Mat2D mat2D_alloc (size_t rows, size_t cols)
Allocate a rows x cols matrix of doubles.
Mat2D_uint32 mat2D_alloc_uint32 (size_t rows, size_t cols)
Allocate a rows x cols matrix of uint32_t.
void mat2D_free (Mat2D m)
Free the memory owned by a Mat2D (elements pointer).
void mat2D_free_uint32 (Mat2D_uint32 m)
Free the memory owned by a Mat2D_uint32 (elements pointer).
size_t mat2D_offset2d (Mat2D m, size_t i, size_t j)
Compute the linear offset of element (i, j) in a Mat2D.
size_t mat2D_offset2d_uint32 (Mat2D_uint32 m, size_t i, size_t j)
Compute the linear offset of element (i, j) in a Mat2D_uint32.
void mat2D_fill (Mat2D m, double x)
Fill all elements of a matrix of doubles with a scalar value.
void mat2D_fill_sequence (Mat2D m, double start, double step)
Fill a matrix with an arithmetic sequence laid out in row-major order.
void mat2D_fill_uint32 (Mat2D_uint32 m, uint32_t x)
Fill all elements of a matrix of uint32_t with a scalar value.
void mat2D_rand (Mat2D m, double low, double high)
Fill a matrix with random doubles in [low, high).
void mat2D_dot (Mat2D dst, Mat2D a, Mat2D b)
Matrix product: dst = a * b.
double mat2D_dot_product (Mat2D a, Mat2D b)
Dot product between two vectors.
void mat2D_cross (Mat2D dst, Mat2D a, Mat2D b)
3D cross product: dst = a x b for 3x1 vectors.
void mat2D_add (Mat2D dst, Mat2D a)
In-place addition: dst += a.
void mat2D_add_row_time_factor_to_row (Mat2D m, size_t des_r, size_t src_r, double factor)
Row operation: row(des_r) += factor * row(src_r).
void mat2D_sub (Mat2D dst, Mat2D a)
In-place subtraction: dst -= a.
void mat2D_sub_row_time_factor_to_row (Mat2D m, size_t des_r, size_t src_r, double factor)
Row operation: row(des_r) -= factor * row(src_r).
void mat2D_mult (Mat2D m, double factor)
In-place scalar multiplication: m *= factor.
void mat2D_mult_row (Mat2D m, size_t r, double factor)
In-place row scaling: row(r) *= factor.
void mat2D_print (Mat2D m, const char *name, size_t padding)
Print a matrix to stdout with a name and indentation padding.
void mat2D_print_as_col (Mat2D m, const char *name, size_t padding)
Print a matrix as a flattened column vector to stdout.
void mat2D_set_identity (Mat2D m)
Set a square matrix to the identity matrix.
double mat2D_make_identity (Mat2D m)
Reduce a matrix to identity via Gauss-Jordan elimination and return the cumulative scaling factor.
void mat2D_set_rot_mat_x (Mat2D m, float angle_deg)
Set a 3x3 rotation matrix for rotation about the X-axis.
void mat2D_set_rot_mat_y (Mat2D m, float angle_deg)
Set a 3x3 rotation matrix for rotation about the Y-axis.
void mat2D_set_rot_mat_z (Mat2D m, float angle_deg)
Set a 3x3 rotation matrix for rotation about the Z-axis.
void mat2D_set_DCM_zyx (Mat2D DCM, float yaw_deg, float pitch_deg, float roll_deg)
Build a 3x3 direction cosine matrix (DCM) from Z-Y-X Euler angles.
void mat2D_copy (Mat2D des, Mat2D src)
Copy all elements from src to des.
void mat2D_copy_mat_to_mat_at_window (Mat2D des, Mat2D src, size_t is, size_t js, size_t ie, size_t je)
Copy a rectangular window from src into des.
void mat2D_get_col (Mat2D des, size_t des_col, Mat2D src, size_t src_col)
Copy a column from src into a column of des.
void mat2D_add_col_to_col (Mat2D des, size_t des_col, Mat2D src, size_t src_col)
Add a source column into a destination column: des[:, des_col] += src[:, src_col].
void mat2D_sub_col_to_col (Mat2D des, size_t des_col, Mat2D src, size_t src_col)
Subtract a source column from a destination column: des[:, des_col] -= src[:, src_col].
void mat2D_swap_rows (Mat2D m, size_t r1, size_t r2)
Swap two rows of a matrix in-place.
void mat2D_get_row (Mat2D des, size_t des_row, Mat2D src, size_t src_row)
Copy a row from src into a row of des.
void mat2D_add_row_to_row (Mat2D des, size_t des_row, Mat2D src, size_t src_row)
Add a source row into a destination row: des[des_row, :] += src[src_row, :].
void mat2D_sub_row_to_row (Mat2D des, size_t des_row, Mat2D src, size_t src_row)
Subtract a source row from a destination row: des[des_row, :] -= src[src_row, :].
double mat2D_calc_norma (Mat2D m)
Compute the Frobenius norm of a matrix, sqrt(sum(m_ij^2)).
bool mat2D_mat_is_all_digit (Mat2D m, double digit)
Check if all elements of a matrix equal a given digit.
bool mat2D_row_is_all_digit (Mat2D m, double digit, size_t r)
Check if all elements of a row equal a given digit.
bool mat2D_col_is_all_digit (Mat2D m, double digit, size_t c)
Check if all elements of a column equal a given digit.
double mat2D_det_2x2_mat (Mat2D m)
Determinant of a 2x2 matrix.
double mat2D_triangulate (Mat2D m)
Forward elimination to transform a matrix to upper triangular form.
double mat2D_det (Mat2D m)
Determinant of an NxN matrix via Gaussian elimination.
void mat2D_LUP_decomposition_with_swap (Mat2D src, Mat2D l, Mat2D p, Mat2D u)
Compute LUP decomposition: P*A = L*U with L unit diagonal.
void mat2D_transpose (Mat2D des, Mat2D src)
Transpose a matrix: des = src^T.
void mat2D_invert (Mat2D des, Mat2D src)
Invert a square matrix using Gauss-Jordan elimination.
void mat2D_solve_linear_sys_LUP_decomposition (Mat2D A, Mat2D x, Mat2D B)
Solve the linear system A x = B using LUP decomposition.
Mat2D_Minor mat2D_minor_alloc_fill_from_mat (Mat2D ref_mat, size_t i, size_t j)
Allocate a minor view by excluding row i and column j of ref_mat.
Mat2D_Minor mat2D_minor_alloc_fill_from_mat_minor (Mat2D_Minor ref_mm, size_t i, size_t j)
Allocate a nested minor view from an existing minor by excluding row i and column j of the minor.
void mat2D_minor_free (Mat2D_Minor mm)
Free the index arrays owned by a minor.
void mat2D_minor_print (Mat2D_Minor mm, const char *name, size_t padding)
Print a minor matrix to stdout with a name and indentation padding.
double mat2D_det_2x2_mat_minor (Mat2D_Minor mm)
Determinant of a 2x2 minor.
double mat2D_minor_det (Mat2D_Minor mm)
Determinant of a minor via recursive expansion by minors.
Detailed Description
A single-header C library for simple 2D matrix operations on doubles and uint32_t, including allocation, basic arithmetic, linear algebra, and helpers (LUP, inverse, determinant, DCM, etc.).
Storage is contiguous row-major (C-style). The element at row i, column j (0-based) is located at elements[i * stride_r + j].
Dense matrices of double are represented by Mat2D, and dense matrices of uint32_t are represented by Mat2D_uint32.
Some routines assert shape compatibility using MATRIX2D_ASSERT.
Random number generation uses the C library rand(); it is not cryptographically secure.
Inversion is done via Gauss-Jordan elimination with partial pivoting only when a pivot is zero; this can be numerically unstable for ill-conditioned matrices. See notes below.
To compile the implementation, define MATRIX2D_IMPLEMENTATION in exactly one translation unit before including this header.
Example: #define MATRIX2D_IMPLEMENTATION #include `matrix2d.h`
Note
This one-file library is heavily inspired by Tsoding's nn.h implementation of matrix creation and operations: https://github.com/tsoding/nn.h and the video: https://youtu.be/L1TbWe8bVOc?list=PLpM-Dvs8t0VZPZKggcql-MmjaBdZKeDMw
Warning
Numerical stability:
There is a set of functions for minors that can be used to compute the determinant, but that approach is factorial in complexity and too slow for larger matrices. This library uses Gaussian elimination instead.
The inversion function can fail or be unstable if pivot values become very small. Consider preconditioning or using a more robust decomposition (e.g., full pivoting, SVD) for ill-conditioned problems.
Definition in file Matrix2D.h.
Macro Definition Documentation
__USE_MISC
#define __USE_MISC
Definition at line 151 of file Matrix2D.h.
MAT2D_AT
#define MAT2D_AT(m, i, j) (m).elements[i * m.stride_r + j]
Access element (i, j) of a Mat2D (0-based).
Warning
This macro does not perform bounds checking in the fast configuration. Use carefully.
Definition at line 145 of file Matrix2D.h.
MAT2D_AT_UINT32
#define MAT2D_AT_UINT32(m, i, j) (m).elements[i * m.stride_r + j]
Access element (i, j) of a Mat2D_uint32 (0-based).
Warning
This macro does not perform bounds checking in the fast configuration. Use carefully.
Definition at line 146 of file Matrix2D.h.
MAT2D_MINOR_AT
#define MAT2D_MINOR_AT(mm, i, j) MAT2D_AT(mm.ref_mat, mm.rows_list[i], mm.cols_list[j])
Access element (i, j) of a Mat2D_Minor (0-based), dereferencing into the underlying reference matrix.
Definition at line 162 of file Matrix2D.h.
MAT2D_MINOR_PRINT
#define MAT2D_MINOR_PRINT(mm) mat2D_minor_print(mm, #mm, 0)
Convenience macro to print a minor with its variable name.
Definition at line 177 of file Matrix2D.h.
mat2D_normalize
#define mat2D_normalize(m) mat2D_mult((m), 1.0 / mat2D_calc_norma((m)))
In-place normalization of all elements so that the Frobenius norm becomes 1.
Equivalent to: m *= 1.0 / mat2D_calc_norma(m).
Definition at line 184 of file Matrix2D.h.
MAT2D_PRINT
#define MAT2D_PRINT(m) mat2D_print(m, #m, 0)
Convenience macro to print a matrix with its variable name.
Definition at line 167 of file Matrix2D.h.
MAT2D_PRINT_AS_COL
#define MAT2D_PRINT_AS_COL(m) mat2D_print_as_col(m, #m, 0)
Convenience macro to print a matrix as a single column with its name.
Definition at line 172 of file Matrix2D.h.
MATRIX2D_ASSERT
#define MATRIX2D_ASSERT assert
Assertion macro used by the library for parameter validation.
Defaults to C assert. Override by defining MATRIX2D_ASSERT before including this header if you want custom behavior.
Definition at line 68 of file Matrix2D.h.
MATRIX2D_MALLOC
#define MATRIX2D_MALLOC malloc
Allocation function used by the library.
Defaults to malloc. Override by defining MATRIX2D_MALLOC before including this header if you want to use a custom allocator.
Definition at line 56 of file Matrix2D.h.
PI
#define PI M_PI
Definition at line 154 of file Matrix2D.h.
Function Documentation
mat2D_add()
void mat2D_add (Mat2D dst, Mat2D a)
In-place addition: dst += a.
Parameters
dst Destination matrix to be incremented.
a Summand of same shape as dst.
Precondition
Shapes match.
Definition at line 496 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
Referenced by adl_arrow_draw().
mat2D_add_col_to_col()
void mat2D_add_col_to_col (Mat2D des, size_t des_col, Mat2D src, size_t src_col)
Add a source column into a destination column: des[:, des_col] += src[:, src_col].
Parameters
des Destination matrix (same row count as src).
des_col Column index in destination.
src Source matrix.
src_col Column index in source.
Definition at line 828 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_add_row_time_factor_to_row()
void mat2D_add_row_time_factor_to_row (Mat2D m, size_t des_r, size_t src_r, double factor)
Row operation: row(des_r) += factor * row(src_r).
Parameters
m Matrix.
des_r Destination row index.
src_r Source row index.
factor Scalar multiplier.
Definition at line 514 of file Matrix2D.h.
References Mat2D::cols, and MAT2D_AT.
mat2D_add_row_to_row()
void mat2D_add_row_to_row (Mat2D des, size_t des_row, Mat2D src, size_t src_row)
Add a source row into a destination row: des[des_row, :] += src[src_row, :].
Parameters
des Destination matrix (same number of columns as src).
des_row Row index in destination.
src Source matrix.
src_row Row index in source.
Definition at line 897 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_alloc()
Mat2D mat2D_alloc (size_t rows, size_t cols)
Allocate a rows x cols matrix of doubles.
Parameters
rows Number of rows (>= 1).
cols Number of columns (>= 1).
Returns
A Mat2D with contiguous storage; must be freed with mat2D_free.
Postcondition
m.stride_r == cols.
Definition at line 278 of file Matrix2D.h.
References Mat2D::cols, Mat2D::elements, MATRIX2D_ASSERT, MATRIX2D_MALLOC, Mat2D::rows, and Mat2D::stride_r.
Referenced by adl_arrow_draw(), adl_figure_alloc(), check_window_mat_size(), mat2D_det(), mat2D_invert(), mat2D_set_DCM_zyx(), mat2D_solve_linear_sys_LUP_decomposition(), and setup_window().
mat2D_alloc_uint32()
Mat2D_uint32 mat2D_alloc_uint32 (size_t rows, size_t cols)
Allocate a rows x cols matrix of uint32_t.
Parameters
rows Number of rows (>= 1).
cols Number of columns (>= 1).
Returns
A Mat2D_uint32 with contiguous storage; free with mat2D_free_uint32.
Postcondition
m.stride_r == cols.
Definition at line 297 of file Matrix2D.h.
References Mat2D_uint32::cols, Mat2D_uint32::elements, MATRIX2D_ASSERT, MATRIX2D_MALLOC, Mat2D_uint32::rows, and Mat2D_uint32::stride_r.
Referenced by adl_figure_alloc(), check_window_mat_size(), and setup_window().
mat2D_calc_norma()
double mat2D_calc_norma (Mat2D m)
Compute the Frobenius norm of a matrix, sqrt(sum(m_ij^2)).
Parameters
m Matrix.
Returns
Frobenius norm.
Definition at line 931 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, and Mat2D::rows.
mat2D_col_is_all_digit()
bool mat2D_col_is_all_digit (Mat2D m, double digit, size_t c)
Check if all elements of a column equal a given digit.
Parameters
m Matrix.
digit Value to compare.
c Column index.
Returns
true if every element equals digit, false otherwise.
Definition at line 985 of file Matrix2D.h.
References Mat2D::cols, and MAT2D_AT.
Referenced by mat2D_det().
mat2D_copy()
void mat2D_copy (Mat2D des, Mat2D src)
Copy all elements from src to des.
Parameters
des Destination matrix.
src Source matrix.
Precondition
Shapes match.
Definition at line 768 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
Referenced by adl_arrow_draw(), mat2D_det(), mat2D_invert(), and mat2D_LUP_decomposition_with_swap().
mat2D_copy_mat_to_mat_at_window()
void mat2D_copy_mat_to_mat_at_window (Mat2D des, Mat2D src, size_t is, size_t js, size_t ie, size_t je)
Copy a rectangular window from src into des.
Parameters
des Destination matrix. Must have size (ie - is + 1) x (je - js + 1).
src Source matrix.
is Start row index in src (inclusive).
js Start column index in src (inclusive).
ie End row index in src (inclusive).
je End column index in src (inclusive).
Precondition
0 <= is <= ie < src.rows, 0 <= js <= je < src.cols.
Definition at line 790 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_cross()
void mat2D_cross (Mat2D dst, Mat2D a, Mat2D b)
3D cross product: dst = a x b for 3x1 vectors.
Parameters
dst 3x1 destination vector.
a 3x1 input vector.
b 3x1 input vector.
Precondition
All matrices have shape 3x1.
Definition at line 479 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_det()
double mat2D_det (Mat2D m)
Determinant of an NxN matrix via Gaussian elimination.
Parameters
m Square matrix.
Returns
det(m).
Copies m internally, triangulates it, and returns the product of diagonal elements (adjusted by any scaling factor as implemented).
Definition at line 1052 of file Matrix2D.h.
References Mat2D::cols, mat2D_alloc(), MAT2D_AT, mat2D_col_is_all_digit(), mat2D_copy(), mat2D_free(), mat2D_row_is_all_digit(), mat2D_triangulate(), MATRIX2D_ASSERT, and Mat2D::rows.
Referenced by mat2D_invert().
mat2D_det_2x2_mat()
double mat2D_det_2x2_mat (Mat2D m)
Determinant of a 2x2 matrix.
Parameters
m Matrix (must be 2x2).
Returns
det(m) = a11 a22 - a12 a21.
Definition at line 1000 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_det_2x2_mat_minor()
double mat2D_det_2x2_mat_minor (Mat2D_Minor mm)
Determinant of a 2x2 minor.
Parameters
mm Minor (must be 2x2).
Returns
det(mm).
Definition at line 1383 of file Matrix2D.h.
References Mat2D_Minor::cols, MAT2D_MINOR_AT, MATRIX2D_ASSERT, and Mat2D_Minor::rows.
Referenced by mat2D_minor_det().
mat2D_dot()
void mat2D_dot (Mat2D dst, Mat2D a, Mat2D b)
Matrix product: dst = a * b.
Parameters
dst Destination matrix (size a.rows x b.cols).
a Left matrix (size a.rows x a.cols).
b Right matrix (size a.cols x b.cols).
Precondition
a.cols == b.rows, dst.rows == a.rows, dst.cols == b.cols.
Postcondition
dst is overwritten.
Definition at line 424 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
Referenced by adl_arrow_draw(), mat2D_set_DCM_zyx(), and mat2D_solve_linear_sys_LUP_decomposition().
mat2D_dot_product()
double mat2D_dot_product (Mat2D a, Mat2D b)
Dot product between two vectors.
Parameters
a Vector (shape n x 1 or 1 x n).
b Vector (same shape as a).
Returns
The scalar dot product sum.
Precondition
a.rows == b.rows, a.cols == b.cols, and one dimension equals 1.
Definition at line 450 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_fill()
void mat2D_fill (Mat2D m, double x)
Fill all elements of a matrix of doubles with a scalar value.
Parameters
m Matrix to fill.
x Value to assign to every element.
Definition at line 362 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, and Mat2D::rows.
Referenced by adl_arrow_draw(), mat2D_invert(), mat2D_LUP_decomposition_with_swap(), and mat2D_solve_linear_sys_LUP_decomposition().
mat2D_fill_sequence()
void mat2D_fill_sequence (Mat2D m, double start, double step)
Fill a matrix with an arithmetic sequence laid out in row-major order.
Parameters
m Matrix to fill.
start First value in the sequence.
step Increment between consecutive elements.
Element at linear index k gets value start + step * k.
Definition at line 378 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, mat2D_offset2d(), and Mat2D::rows.
mat2D_fill_uint32()
void mat2D_fill_uint32 (Mat2D_uint32 m, uint32_t x)
Fill all elements of a matrix of uint32_t with a scalar value.
Parameters
m Matrix to fill.
x Value to assign to every element.
Definition at line 391 of file Matrix2D.h.
References Mat2D_uint32::cols, MAT2D_AT_UINT32, and Mat2D_uint32::rows.
Referenced by adl_2Dscalar_interp_on_figure(), and adl_curves_plot_on_figure().
mat2D_free()
void mat2D_free (Mat2D m)
Free the memory owned by a Mat2D (elements pointer).
Parameters
m Matrix whose elements were allocated via MATRIX2D_MALLOC.
Note
Safe to call with m.elements == NULL.
Definition at line 314 of file Matrix2D.h.
References Mat2D::elements.
Referenced by adl_arrow_draw(), check_window_mat_size(), mat2D_det(), mat2D_invert(), mat2D_set_DCM_zyx(), and mat2D_solve_linear_sys_LUP_decomposition().
mat2D_free_uint32()
void mat2D_free_uint32 (Mat2D_uint32 m)
Free the memory owned by a Mat2D_uint32 (elements pointer).
Parameters
m Matrix whose elements were allocated via MATRIX2D_MALLOC.
Note
Safe to call with m.elements == NULL.
Definition at line 324 of file Matrix2D.h.
References Mat2D_uint32::elements.
Referenced by check_window_mat_size(), and destroy_window().
mat2D_get_col()
void mat2D_get_col (Mat2D des, size_t des_col, Mat2D src, size_t src_col)
Copy a column from src into a column of des.
Parameters
des Destination matrix (same row count as src).
des_col Column index in destination.
src Source matrix.
src_col Column index in source.
Definition at line 810 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_get_row()
void mat2D_get_row (Mat2D des, size_t des_row, Mat2D src, size_t src_row)
Copy a row from src into a row of des.
Parameters
des Destination matrix (same number of columns as src).
des_row Row index in destination.
src Source matrix.
src_row Row index in source.
Definition at line 879 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_invert()
void mat2D_invert (Mat2D des, Mat2D src)
Invert a square matrix using Gauss-Jordan elimination.
Parameters
des Destination matrix (same shape as src).
src Source square matrix.
Precondition
src is square and nonsingular.
If det(src) == 0, prints an error and sets des to all zeros.
Warning
May be numerically unstable for ill-conditioned matrices.
Definition at line 1169 of file Matrix2D.h.
References Mat2D::cols, mat2D_alloc(), MAT2D_AT, mat2D_copy(), mat2D_det(), mat2D_fill(), mat2D_free(), mat2D_mult_row(), mat2D_set_identity(), mat2D_sub_row_time_factor_to_row(), mat2D_swap_rows(), MATRIX2D_ASSERT, and Mat2D::rows.
Referenced by mat2D_solve_linear_sys_LUP_decomposition().
mat2D_LUP_decomposition_with_swap()
void mat2D_LUP_decomposition_with_swap (Mat2D src, Mat2D l, Mat2D p, Mat2D u)
Compute LUP decomposition: P*A = L*U with L unit diagonal.
Parameters
src Input matrix A (not modified).
l Lower triangular matrix with unit diagonal (output).
p Permutation matrix (output).
u Upper triangular matrix (output).
Precondition
l, p, u are allocated to match src shape; src is square.
Definition at line 1107 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, mat2D_copy(), mat2D_fill(), mat2D_set_identity(), mat2D_sub_row_time_factor_to_row(), mat2D_swap_rows(), and Mat2D::rows.
Referenced by mat2D_solve_linear_sys_LUP_decomposition().
mat2D_make_identity()
double mat2D_make_identity (Mat2D m)
Reduce a matrix to identity via Gauss-Jordan elimination and return the cumulative scaling factor.
Parameters
m Matrix reduced in-place to identity (if nonsingular).
Returns
The product of row scaling factors applied during elimination.
Note
Intended as a helper for determinant-related operations.
Warning
Not robust to singular or ill-conditioned matrices.
Definition at line 643 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, mat2D_mult_row(), mat2D_sub_row_time_factor_to_row(), mat2D_swap_rows(), and Mat2D::rows.
mat2D_mat_is_all_digit()
bool mat2D_mat_is_all_digit (Mat2D m, double digit)
Check if all elements of a matrix equal a given digit.
Parameters
m Matrix.
digit Value to compare.
Returns
true if every element equals digit, false otherwise.
Definition at line 949 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, and Mat2D::rows.
mat2D_minor_alloc_fill_from_mat()
Mat2D_Minor mat2D_minor_alloc_fill_from_mat (Mat2D ref_mat, size_t i, size_t j)
Allocate a minor view by excluding row i and column j of ref_mat.
Parameters
ref_mat Reference square matrix.
i Excluded row index in ref_mat.
j Excluded column index in ref_mat.
Returns
A Mat2D_Minor that references ref_mat.
Note
Free rows_list and cols_list with mat2D_minor_free when done.
Definition at line 1279 of file Matrix2D.h.
References Mat2D::cols, Mat2D_Minor::cols, Mat2D_Minor::cols_list, MATRIX2D_ASSERT, MATRIX2D_MALLOC, Mat2D_Minor::ref_mat, Mat2D::rows, Mat2D_Minor::rows, Mat2D_Minor::rows_list, and Mat2D_Minor::stride_r.
mat2D_minor_alloc_fill_from_mat_minor()
Mat2D_Minor mat2D_minor_alloc_fill_from_mat_minor (Mat2D_Minor ref_mm, size_t i, size_t j)
Allocate a nested minor view from an existing minor by excluding row i and column j of the minor.
Parameters
ref_mm Reference minor.
i Excluded row index in the minor.
j Excluded column index in the minor.
Returns
A new Mat2D_Minor that references the same underlying matrix.
Note
Free rows_list and cols_list with mat2D_minor_free when done.
Definition at line 1318 of file Matrix2D.h.
References Mat2D_Minor::cols, Mat2D_Minor::cols_list, MATRIX2D_ASSERT, MATRIX2D_MALLOC, Mat2D_Minor::ref_mat, Mat2D_Minor::rows, Mat2D_Minor::rows_list, and Mat2D_Minor::stride_r.
Referenced by mat2D_minor_det().
mat2D_minor_det()
double mat2D_minor_det (Mat2D_Minor mm)
Determinant of a minor via recursive expansion by minors.
Parameters
mm Square minor.
Returns
det(mm).
Warning
Exponential complexity (factorial). Intended for educational or very small matrices only.
Definition at line 1396 of file Matrix2D.h.
References Mat2D_Minor::cols, mat2D_det_2x2_mat_minor(), mat2D_minor_alloc_fill_from_mat_minor(), MAT2D_MINOR_AT, mat2D_minor_free(), MATRIX2D_ASSERT, and Mat2D_Minor::rows.
mat2D_minor_free()
void mat2D_minor_free (Mat2D_Minor mm)
Free the index arrays owned by a minor.
Parameters
mm Minor to free.
Note
After this call, mm.rows_list and mm.cols_list are invalid.
Definition at line 1353 of file Matrix2D.h.
References Mat2D_Minor::cols_list, and Mat2D_Minor::rows_list.
Referenced by mat2D_minor_det().
mat2D_minor_print()
void mat2D_minor_print (Mat2D_Minor mm, const char * name, size_t padding)
Print a minor matrix to stdout with a name and indentation padding.
Parameters
mm Minor to print.
name Label to print.
padding Left padding in spaces.
Definition at line 1365 of file Matrix2D.h.
References Mat2D_Minor::cols, MAT2D_MINOR_AT, and Mat2D_Minor::rows.
mat2D_mult()
void mat2D_mult (Mat2D m, double factor)
In-place scalar multiplication: m *= factor.
Parameters
m Matrix.
factor Scalar multiplier.
Definition at line 557 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, and Mat2D::rows.
mat2D_mult_row()
void mat2D_mult_row (Mat2D m, size_t r, double factor)
In-place row scaling: row(r) *= factor.
Parameters
m Matrix.
r Row index.
factor Scalar multiplier.
Definition at line 572 of file Matrix2D.h.
References Mat2D::cols, and MAT2D_AT.
Referenced by mat2D_invert(), and mat2D_make_identity().
mat2D_offset2d()
size_t mat2D_offset2d (Mat2D m, size_t i, size_t j)
Compute the linear offset of element (i, j) in a Mat2D.
Parameters
m Matrix.
i Row index (0-based).
j Column index (0-based).
Returns
The linear offset i * stride_r + j.
Precondition
0 <= i < rows, 0 <= j < cols (asserted).
Definition at line 337 of file Matrix2D.h.
References Mat2D::cols, MATRIX2D_ASSERT, Mat2D::rows, and Mat2D::stride_r.
Referenced by mat2D_fill_sequence().
mat2D_offset2d_uint32()
size_t mat2D_offset2d_uint32 (Mat2D_uint32 m, size_t i, size_t j)
Compute the linear offset of element (i, j) in a Mat2D_uint32.
Parameters
m Matrix.
i Row index (0-based).
j Column index (0-based).
Returns
The linear offset i * stride_r + j.
Precondition
0 <= i < rows, 0 <= j < cols (asserted).
Definition at line 351 of file Matrix2D.h.
References Mat2D_uint32::cols, MATRIX2D_ASSERT, Mat2D_uint32::rows, and Mat2D_uint32::stride_r.
mat2D_print()
void mat2D_print (Mat2D m, const char * name, size_t padding)
Print a matrix to stdout with a name and indentation padding.
Parameters
m Matrix to print.
name Label to print.
padding Left padding in spaces.
Definition at line 585 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, and Mat2D::rows.
mat2D_print_as_col()
void mat2D_print_as_col (Mat2D m, const char * name, size_t padding)
Print a matrix as a flattened column vector to stdout.
Parameters
m Matrix to print (flattened in row-major).
name Label to print.
padding Left padding in spaces.
Definition at line 604 of file Matrix2D.h.
References Mat2D::cols, Mat2D::elements, and Mat2D::rows.
mat2D_rand()
void mat2D_rand (Mat2D m, double low, double high)
Fill a matrix with random doubles in [low, high).
Parameters
m Matrix to fill.
low Lower bound (inclusive).
high Upper bound (exclusive).
Precondition
high > low.
Definition at line 407 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, mat2D_rand_double(), and Mat2D::rows.
mat2D_rand_double()
double mat2D_rand_double (void)
Return a pseudo-random double in the range [0, 1].
Note
Uses C library rand() and RAND_MAX. Not cryptographically secure.
Definition at line 266 of file Matrix2D.h.
Referenced by mat2D_rand().
mat2D_row_is_all_digit()
bool mat2D_row_is_all_digit (Mat2D m, double digit, size_t r)
Check if all elements of a row equal a given digit.
Parameters
m Matrix.
digit Value to compare.
r Row index.
Returns
true if every element equals digit, false otherwise.
Definition at line 968 of file Matrix2D.h.
References Mat2D::cols, and MAT2D_AT.
Referenced by mat2D_det().
mat2D_set_DCM_zyx()
void mat2D_set_DCM_zyx (Mat2D DCM, float yaw_deg, float pitch_deg, float roll_deg)
Build a 3x3 direction cosine matrix (DCM) from Z-Y-X Euler angles.
Parameters
DCM 3x3 destination matrix.
yaw_deg Rotation about Z in degrees.
pitch_deg Rotation about Y in degrees.
roll_deg Rotation about X in degrees.
Computes DCM = R_x(roll) * R_y(pitch) * R_z(yaw).
Definition at line 743 of file Matrix2D.h.
References mat2D_alloc(), mat2D_dot(), mat2D_free(), mat2D_set_rot_mat_x(), mat2D_set_rot_mat_y(), and mat2D_set_rot_mat_z().
mat2D_set_identity()
void mat2D_set_identity (Mat2D m)
Set a square matrix to the identity matrix.
Parameters
m Matrix (must be square).
Precondition
m.rows == m.cols.
Definition at line 619 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
Referenced by mat2D_invert(), mat2D_LUP_decomposition_with_swap(), mat2D_set_rot_mat_x(), mat2D_set_rot_mat_y(), and mat2D_set_rot_mat_z().
mat2D_set_rot_mat_x()
void mat2D_set_rot_mat_x (Mat2D m, float angle_deg)
Set a 3x3 rotation matrix for rotation about the X-axis.
Parameters
m 3x3 destination matrix.
angle_deg Angle in degrees.
Definition at line 689 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, mat2D_set_identity(), MATRIX2D_ASSERT, PI, and Mat2D::rows.
Referenced by mat2D_set_DCM_zyx().
mat2D_set_rot_mat_y()
void mat2D_set_rot_mat_y (Mat2D m, float angle_deg)
Set a 3x3 rotation matrix for rotation about the Y-axis.
Parameters
m 3x3 destination matrix.
angle_deg Angle in degrees.
Definition at line 706 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, mat2D_set_identity(), MATRIX2D_ASSERT, PI, and Mat2D::rows.
Referenced by mat2D_set_DCM_zyx().
mat2D_set_rot_mat_z()
void mat2D_set_rot_mat_z (Mat2D m, float angle_deg)
Set a 3x3 rotation matrix for rotation about the Z-axis.
Parameters
m 3x3 destination matrix.
angle_deg Angle in degrees.
Definition at line 723 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, mat2D_set_identity(), MATRIX2D_ASSERT, PI, and Mat2D::rows.
Referenced by adl_arrow_draw(), and mat2D_set_DCM_zyx().
mat2D_solve_linear_sys_LUP_decomposition()
void mat2D_solve_linear_sys_LUP_decomposition (Mat2D A, Mat2D x, Mat2D B)
Solve the linear system A x = B using LUP decomposition.
Parameters
A Coefficient matrix (NxN).
x Solution vector (N x 1) (output).
B Right-hand side vector (N x 1).
Internally computes LUP and uses explicit inverses of L and U.
Warning
Forming inverses explicitly can be less stable; a forward/backward substitution would be preferable for production-quality code.
Definition at line 1236 of file Matrix2D.h.
References Mat2D::cols, mat2D_alloc(), mat2D_dot(), mat2D_fill(), mat2D_free(), mat2D_invert(), mat2D_LUP_decomposition_with_swap(), MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_sub()
void mat2D_sub (Mat2D dst, Mat2D a)
In-place subtraction: dst -= a.
Parameters
dst Destination matrix to be decremented.
a Subtrahend of same shape as dst.
Precondition
Shapes match.
Definition at line 527 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
Referenced by adl_arrow_draw().
mat2D_sub_col_to_col()
void mat2D_sub_col_to_col (Mat2D des, size_t des_col, Mat2D src, size_t src_col)
Subtract a source column from a destination column: des[:, des_col] -= src[:, src_col].
Parameters
des Destination matrix (same row count as src).
des_col Column index in destination.
src Source matrix.
src_col Column index in source.
Definition at line 846 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_sub_row_time_factor_to_row()
void mat2D_sub_row_time_factor_to_row (Mat2D m, size_t des_r, size_t src_r, double factor)
Row operation: row(des_r) -= factor * row(src_r).
Parameters
m Matrix.
des_r Destination row index.
src_r Source row index.
factor Scalar multiplier.
Definition at line 545 of file Matrix2D.h.
References Mat2D::cols, and MAT2D_AT.
Referenced by mat2D_invert(), mat2D_LUP_decomposition_with_swap(), mat2D_make_identity(), and mat2D_triangulate().
mat2D_sub_row_to_row()
void mat2D_sub_row_to_row (Mat2D des, size_t des_row, Mat2D src, size_t src_row)
Subtract a source row from a destination row: des[des_row, :] -= src[src_row, :].
Parameters
des Destination matrix (same number of columns as src).
des_row Row index in destination.
src Source matrix.
src_row Row index in source.
Definition at line 915 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_swap_rows()
void mat2D_swap_rows (Mat2D m, size_t r1, size_t r2)
Swap two rows of a matrix in-place.
Parameters
m Matrix.
r1 First row index.
r2 Second row index.
Definition at line 863 of file Matrix2D.h.
References Mat2D::cols, and MAT2D_AT.
Referenced by mat2D_invert(), mat2D_LUP_decomposition_with_swap(), mat2D_make_identity(), and mat2D_triangulate().
mat2D_transpose()
void mat2D_transpose (Mat2D des, Mat2D src)
Transpose a matrix: des = src^T.
Parameters
des Destination matrix (shape src.cols x src.rows).
src Source matrix.
Definition at line 1149 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, and Mat2D::rows.
mat2D_triangulate()
double mat2D_triangulate (Mat2D m)
Forward elimination to transform a matrix to upper triangular form.
Parameters
m Matrix transformed in-place.
Returns
Product of row scaling factors (currently 1 in this implementation).
Note
Used as part of determinant computation via triangularization.
Warning
Not robust for linearly dependent rows or tiny pivots.
Definition at line 1013 of file Matrix2D.h.
References Mat2D::cols, MAT2D_AT, mat2D_sub_row_time_factor_to_row(), mat2D_swap_rows(), and Mat2D::rows.
Referenced by mat2D_det().