striped_Almog_Draw_Library.h File Reference
#include <math.h>
#include <stdint.h>
#include <limits.h>
#include <string.h>
#include <float.h>
#include `./Matrix2D.h`
#include `./Almog_Dynamic_Array.h`
#include <assert.h>
Classes
struct Offset_zoom_param
struct Point
struct Curve
struct Curve_ada
struct Tri
struct Quad
struct Tri_mesh
struct Quad_mesh
struct Figure
struct Grid
Macros
#define ADL_ASSERT assert
#define POINT
#define CURVE
#define CURVE_ADA
#define TRI
#define QUAD
#define TRI_MESH
#define QUAD_MESH
#define HexARGB_RGBA(x) ((x)>>(8*2)&0xFF), ((x)>>(8*1)&0xFF), ((x)>>(8*0)&0xFF), ((x)>>(8*3)&0xFF)
#define HexARGB_RGB_VAR(x, r, g, b) r = ((x)>>(8*2)&0xFF); g = ((x)>>(8*1)&0xFF); b = ((x)>>(8*0)&0xFF);
#define HexARGB_RGBA_VAR(x, r, g, b, a) r = ((x)>>(8*2)&0xFF); g = ((x)>>(8*1)&0xFF); b = ((x)>>(8*0)&0xFF); a = ((x)>>(8*3)&0xFF)
#define RGB_hexRGB(r, g, b) (int)(0x010000*(int)(r) + 0x000100*(int)(g) + 0x000001*(int)(b))
#define RGBA_hexARGB(r, g, b, a) (int)(0x01000000l*(int)(fminf(a, 255)) + 0x010000*(int)(r) + 0x000100*(int)(g) + 0x000001*(int)(b))
#define RED_hexARGB 0xFFFF0000
#define GREEN_hexARGB 0xFF00FF00
#define BLUE_hexARGB 0xFF0000FF
#define PURPLE_hexARGB 0xFFFF00FF
#define CYAN_hexARGB 0xFF00FFFF
#define YELLOW_hexARGB 0xFFFFFF00
#define edge_cross_point(a1, b, a2, p) (b.x-a1.x)*(p.y-a2.y)-(b.y-a1.y)*(p.x-a2.x)
#define is_top_edge(x, y) (y == 0 && x > 0)
#define is_left_edge(x, y) (y < 0)
#define is_top_left(ps, pe) (is_top_edge(pe.x-ps.x, pe.y-ps.y) || is_left_edge(pe.x-ps.x, pe.y-ps.y))
#define ADL_MAX_POINT_VAL 1e5
#define adl_assert_point_is_valid(p) ADL_ASSERT(isfinite(p.x) && isfinite(p.y) && isfinite(p.z) && isfinite(p.w))
#define adl_assert_tri_is_valid(tri)
#define adl_assert_quad_is_valid(quad)
#define ADL_FIGURE_PADDING_PRECENTAGE 20
#define ADL_MAX_FIGURE_PADDING 70
#define ADL_MIN_FIGURE_PADDING 20
#define ADL_MAX_HEAD_SIZE 15
#define ADL_FIGURE_HEAD_ANGLE_DEG 30
#define ADL_FIGURE_AXIS_COLOR 0xff000000
#define ADL_MAX_CHARACTER_OFFSET 10
#define ADL_MIN_CHARACTER_OFFSET 5
#define ADL_MAX_SENTENCE_LEN 256
#define ADL_MAX_ZOOM 1e3
#define ADL_DEFAULT_OFFSET_ZOOM (Offset_zoom_param){1,0,0,0,0}
#define adl_offset_zoom_point(p, window_w, window_h, offset_zoom_param)
#define adl_offset2d(i, j, ni) (j) * (ni) + (i)
Functions
void adl_point_draw (Mat2D_uint32 screen_mat, int x, int y, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_line_draw (Mat2D_uint32 screen_mat, const float x1_input, const float y1_input, const float x2_input, const float y2_input, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_lines_draw (const Mat2D_uint32 screen_mat, const Point *points, const size_t len, const uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_lines_loop_draw (const Mat2D_uint32 screen_mat, const Point *points, const size_t len, const uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_arrow_draw (Mat2D_uint32 screen_mat, int xs, int ys, int xe, int ye, float head_size, float angle_deg, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_character_draw (Mat2D_uint32 screen_mat, char c, int width_pixel, int hight_pixel, int x_top_left, int y_top_left, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_sentence_draw (Mat2D_uint32 screen_mat, const char sentence[], size_t len, const int x_top_left, const int y_top_left, const int hight_pixel, const uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_rectangle_draw_min_max (Mat2D_uint32 screen_mat, int min_x, int max_x, int min_y, int max_y, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_rectangle_fill_min_max (Mat2D_uint32 screen_mat, int min_x, int max_x, int min_y, int max_y, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_quad_draw (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_quad_fill (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_quad_fill_interpolate_normal_mean_value (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_quad_fill_interpolate_color_mean_value (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, Offset_zoom_param offset_zoom_param)
void adl_quad_mesh_draw (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_quad_mesh_fill (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_quad_mesh_fill_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_quad_mesh_fill_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, Offset_zoom_param offset_zoom_param)
void adl_circle_draw (Mat2D_uint32 screen_mat, float center_x, float center_y, float r, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_circle_fill (Mat2D_uint32 screen_mat, float center_x, float center_y, float r, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_tri_draw (Mat2D_uint32 screen_mat, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_tri_fill_Pinedas_rasterizer (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_tri_fill_Pinedas_rasterizer_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, Offset_zoom_param offset_zoom_param)
void adl_tri_fill_Pinedas_rasterizer_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_tri_mesh_draw (Mat2D_uint32 screen_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_tri_mesh_fill_Pinedas_rasterizer (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
void adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, Offset_zoom_param offset_zoom_param)
void adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
float adl_tan_half_angle (Point vi, Point vj, Point p, float li, float lj)
float adl_linear_map (float s, float min_in, float max_in, float min_out, float max_out)
void adl_quad2tris (Quad quad, Tri *tri1, Tri *tri2, char split_line[])
void adl_linear_sRGB_to_okLab (uint32_t hex_ARGB, float *L, float *a, float *b)
void adl_okLab_to_linear_sRGB (float L, float a, float b, uint32_t *hex_ARGB)
void adl_linear_sRGB_to_okLch (uint32_t hex_ARGB, float *L, float *c, float *h_deg)
void adl_okLch_to_linear_sRGB (float L, float c, float h_deg, uint32_t *hex_ARGB)
void adl_interpolate_ARGBcolor_on_okLch (uint32_t color1, uint32_t color2, float t, float num_of_rotations, uint32_t *color_out)
Figure adl_figure_alloc (size_t rows, size_t cols, Point top_left_position)
void adl_figure_copy_to_screen (Mat2D_uint32 screen_mat, Figure figure)
void adl_axis_draw_on_figure (Figure *figure)
void adl_max_min_values_draw_on_figure (Figure figure)
void adl_curve_add_to_figure (Figure *figure, Point *src_points, size_t src_len, uint32_t color)
void adl_curves_plot_on_figure (Figure figure)
void adl_2Dscalar_interp_on_figure (Figure figure, double *x_2Dmat, double *y_2Dmat, double *scalar_2Dmat, int ni, int nj, char color_scale[], float num_of_rotations)
Grid adl_cartesian_grid_create (float min_e1, float max_e1, float min_e2, float max_e2, int num_samples_e1, int num_samples_e2, char plane[], float third_direction_position)
void adl_grid_draw (Mat2D_uint32 screen_mat, Grid grid, uint32_t color, Offset_zoom_param offset_zoom_param)
Macro Definition Documentation
ADL_ASSERT
#define ADL_ASSERT assert
Definition at line 12 of file striped_Almog_Draw_Library.h.
adl_assert_point_is_valid
#define adl_assert_point_is_valid(p) ADL_ASSERT(isfinite(p.x) && isfinite(p.y) && isfinite(p.z) && isfinite(p.w))
Definition at line 189 of file striped_Almog_Draw_Library.h.
adl_assert_quad_is_valid
#define adl_assert_quad_is_valid(quad)
Value:
        adl_assert_point_is_valid(quad.points[0]); \
        adl_assert_point_is_valid(quad.points[1]); \
        adl_assert_point_is_valid(quad.points[2]); \
        adl_assert_point_is_valid(quad.points[3])
Definition at line 193 of file striped_Almog_Draw_Library.h.
adl_assert_tri_is_valid
#define adl_assert_tri_is_valid(tri)
Value:
        adl_assert_point_is_valid(tri.points[0]); \
        adl_assert_point_is_valid(tri.points[1]); \
        adl_assert_point_is_valid(tri.points[2])
Definition at line 190 of file striped_Almog_Draw_Library.h.
ADL_DEFAULT_OFFSET_ZOOM
#define ADL_DEFAULT_OFFSET_ZOOM (Offset_zoom_param){1,0,0,0,0}
Definition at line 207 of file striped_Almog_Draw_Library.h.
ADL_FIGURE_AXIS_COLOR
#define ADL_FIGURE_AXIS_COLOR 0xff000000
Definition at line 202 of file striped_Almog_Draw_Library.h.
ADL_FIGURE_HEAD_ANGLE_DEG
#define ADL_FIGURE_HEAD_ANGLE_DEG 30
Definition at line 201 of file striped_Almog_Draw_Library.h.
ADL_FIGURE_PADDING_PRECENTAGE
#define ADL_FIGURE_PADDING_PRECENTAGE 20
Definition at line 197 of file striped_Almog_Draw_Library.h.
ADL_MAX_CHARACTER_OFFSET
#define ADL_MAX_CHARACTER_OFFSET 10
Definition at line 203 of file striped_Almog_Draw_Library.h.
ADL_MAX_FIGURE_PADDING
#define ADL_MAX_FIGURE_PADDING 70
Definition at line 198 of file striped_Almog_Draw_Library.h.
ADL_MAX_HEAD_SIZE
#define ADL_MAX_HEAD_SIZE 15
Definition at line 200 of file striped_Almog_Draw_Library.h.
ADL_MAX_POINT_VAL
#define ADL_MAX_POINT_VAL 1e5
Definition at line 188 of file striped_Almog_Draw_Library.h.
ADL_MAX_SENTENCE_LEN
#define ADL_MAX_SENTENCE_LEN 256
Definition at line 205 of file striped_Almog_Draw_Library.h.
ADL_MAX_ZOOM
#define ADL_MAX_ZOOM 1e3
Definition at line 206 of file striped_Almog_Draw_Library.h.
ADL_MIN_CHARACTER_OFFSET
#define ADL_MIN_CHARACTER_OFFSET 5
Definition at line 204 of file striped_Almog_Draw_Library.h.
ADL_MIN_FIGURE_PADDING
#define ADL_MIN_FIGURE_PADDING 20
Definition at line 199 of file striped_Almog_Draw_Library.h.
adl_offset2d
#define adl_offset2d(i, j, ni) (j) * (ni) + (i)
Definition at line 1423 of file striped_Almog_Draw_Library.h.
adl_offset_zoom_point
#define adl_offset_zoom_point(p, window_w, window_h, offset_zoom_param)
Value:
    (p).x = ((p).x - (window_w)/2 + offset_zoom_param.offset_x) * offset_zoom_param.zoom_multiplier + (window_w)/2; \
    (p).y = ((p).y - (window_h)/2 + offset_zoom_param.offset_y) * offset_zoom_param.zoom_multiplier + (window_h)/2
Definition at line 208 of file striped_Almog_Draw_Library.h.
BLUE_hexARGB
#define BLUE_hexARGB 0xFF0000FF
Definition at line 180 of file striped_Almog_Draw_Library.h.
CURVE
#define CURVE
Definition at line 31 of file striped_Almog_Draw_Library.h.
CURVE_ADA
#define CURVE_ADA
Definition at line 40 of file striped_Almog_Draw_Library.h.
CYAN_hexARGB
#define CYAN_hexARGB 0xFF00FFFF
Definition at line 182 of file striped_Almog_Draw_Library.h.
edge_cross_point
#define edge_cross_point(a1, b, a2, p) (b.x-a1.x)*(p.y-a2.y)-(b.y-a1.y)*(p.x-a2.x)
Definition at line 184 of file striped_Almog_Draw_Library.h.
GREEN_hexARGB
#define GREEN_hexARGB 0xFF00FF00
Definition at line 179 of file striped_Almog_Draw_Library.h.
HexARGB_RGB_VAR
#define HexARGB_RGB_VAR(x, r, g, b) r = ((x)>>(8*2)&0xFF); g = ((x)>>(8*1)&0xFF); b = ((x)>>(8*0)&0xFF);
Definition at line 120 of file striped_Almog_Draw_Library.h.
HexARGB_RGBA
#define HexARGB_RGBA(x) ((x)>>(8*2)&0xFF), ((x)>>(8*1)&0xFF), ((x)>>(8*0)&0xFF), ((x)>>(8*3)&0xFF)
Definition at line 117 of file striped_Almog_Draw_Library.h.
HexARGB_RGBA_VAR
#define HexARGB_RGBA_VAR(x, r, g, b, a) r = ((x)>>(8*2)&0xFF); g = ((x)>>(8*1)&0xFF); b = ((x)>>(8*0)&0xFF); a = ((x)>>(8*3)&0xFF)
Definition at line 123 of file striped_Almog_Draw_Library.h.
is_left_edge
#define is_left_edge(x, y) (y < 0)
Definition at line 186 of file striped_Almog_Draw_Library.h.
is_top_edge
#define is_top_edge(x, y) (y == 0 && x > 0)
Definition at line 185 of file striped_Almog_Draw_Library.h.
is_top_left
#define is_top_left(ps, pe) (is_top_edge(pe.x-ps.x, pe.y-ps.y) || is_left_edge(pe.x-ps.x, pe.y-ps.y))
Definition at line 187 of file striped_Almog_Draw_Library.h.
POINT
#define POINT
Definition at line 22 of file striped_Almog_Draw_Library.h.
PURPLE_hexARGB
#define PURPLE_hexARGB 0xFFFF00FF
Definition at line 181 of file striped_Almog_Draw_Library.h.
QUAD
#define QUAD
Definition at line 59 of file striped_Almog_Draw_Library.h.
QUAD_MESH
#define QUAD_MESH
Definition at line 77 of file striped_Almog_Draw_Library.h.
RED_hexARGB
#define RED_hexARGB 0xFFFF0000
Definition at line 178 of file striped_Almog_Draw_Library.h.
RGB_hexRGB
#define RGB_hexRGB(r, g, b) (int)(0x010000*(int)(r) + 0x000100*(int)(g) + 0x000001*(int)(b))
Definition at line 126 of file striped_Almog_Draw_Library.h.
RGBA_hexARGB
#define RGBA_hexARGB(r, g, b, a) (int)(0x01000000l*(int)(fminf(a, 255)) + 0x010000*(int)(r) + 0x000100*(int)(g) + 0x000001*(int)(b))
Definition at line 129 of file striped_Almog_Draw_Library.h.
TRI
#define TRI
Definition at line 48 of file striped_Almog_Draw_Library.h.
TRI_MESH
#define TRI_MESH
Definition at line 69 of file striped_Almog_Draw_Library.h.
YELLOW_hexARGB
#define YELLOW_hexARGB 0xFFFFFF00
Definition at line 183 of file striped_Almog_Draw_Library.h.
Function Documentation
adl_2Dscalar_interp_on_figure()
void adl_2Dscalar_interp_on_figure (Figure figure, double * x_2Dmat, double * y_2Dmat, double * scalar_2Dmat, int ni, int nj, char color_scale[], float num_of_rotations)
Definition at line 1424 of file striped_Almog_Draw_Library.h.
References adl_axis_draw_on_figure(), ADL_DEFAULT_OFFSET_ZOOM, adl_interpolate_ARGBcolor_on_okLch(), adl_linear_map(), adl_max_min_values_draw_on_figure(), adl_offset2d, adl_offset_zoom_point, adl_quad_fill_interpolate_color_mean_value(), Figure::background_color, BLUE_hexARGB, Quad::colors, Mat2D::cols, Mat2D_uint32::cols, CYAN_hexARGB, Mat2D::elements, GREEN_hexARGB, Figure::inv_z_buffer_mat, Quad::light_intensity, mat2D_fill_uint32(), Figure::max_x, Figure::max_x_pixel, Figure::max_y, Figure::max_y_pixel, Figure::min_x, Figure::min_x_pixel, Figure::min_y, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Quad::points, PURPLE_hexARGB, RED_hexARGB, Mat2D::rows, Mat2D_uint32::rows, Quad::to_draw, Figure::to_draw_axis, Figure::to_draw_max_min_values, Point::w, Point::x, Point::y, YELLOW_hexARGB, and Point::z.
adl_arrow_draw()
void adl_arrow_draw (Mat2D_uint32 screen_mat, int xs, int ys, int xe, int ye, float head_size, float angle_deg, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 303 of file striped_Almog_Draw_Library.h.
References adl_line_draw(), mat2D_add(), mat2D_alloc(), MAT2D_AT, mat2D_copy(), mat2D_dot(), mat2D_fill(), mat2D_free(), mat2D_set_rot_mat_z(), and mat2D_sub().
Referenced by adl_axis_draw_on_figure().
adl_axis_draw_on_figure()
void adl_axis_draw_on_figure (Figure * figure)
Definition at line 1329 of file striped_Almog_Draw_Library.h.
References adl_arrow_draw(), ADL_FIGURE_AXIS_COLOR, ADL_FIGURE_HEAD_ANGLE_DEG, ADL_FIGURE_PADDING_PRECENTAGE, ADL_MAX_FIGURE_PADDING, ADL_MAX_HEAD_SIZE, ADL_MIN_FIGURE_PADDING, Mat2D_uint32::cols, Figure::max_x_pixel, Figure::max_y_pixel, Figure::min_x_pixel, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Mat2D_uint32::rows, Figure::x_axis_head_size, and Figure::y_axis_head_size.
Referenced by adl_2Dscalar_interp_on_figure(), and adl_curves_plot_on_figure().
adl_cartesian_grid_create()
Grid adl_cartesian_grid_create (float min_e1, float max_e1, float min_e2, float max_e2, int num_samples_e1, int num_samples_e2, char plane[], float third_direction_position)
Definition at line 1569 of file striped_Almog_Draw_Library.h.
References ada_appand, ada_init_array, Grid::curves, Grid::de1, Grid::de2, Grid::max_e1, Grid::max_e2, Grid::min_e1, Grid::min_e2, Grid::num_samples_e1, Grid::num_samples_e2, Grid::plane, Point::w, Point::x, Point::y, and Point::z.
adl_character_draw()
void adl_character_draw (Mat2D_uint32 screen_mat, char c, int width_pixel, int hight_pixel, int x_top_left, int y_top_left, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 346 of file striped_Almog_Draw_Library.h.
References adl_line_draw(), adl_rectangle_draw_min_max(), and adl_rectangle_fill_min_max().
Referenced by adl_sentence_draw().
adl_circle_draw()
void adl_circle_draw (Mat2D_uint32 screen_mat, float center_x, float center_y, float r, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 947 of file striped_Almog_Draw_Library.h.
References adl_point_draw().
adl_circle_fill()
void adl_circle_fill (Mat2D_uint32 screen_mat, float center_x, float center_y, float r, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 958 of file striped_Almog_Draw_Library.h.
References adl_point_draw().
adl_curve_add_to_figure()
void adl_curve_add_to_figure (Figure * figure, Point * src_points, size_t src_len, uint32_t color)
Definition at line 1378 of file striped_Almog_Draw_Library.h.
References ada_appand, ada_init_array, Curve::color, Figure::max_x, Figure::max_y, Figure::min_x, Figure::min_y, Figure::src_curve_array, Point::x, and Point::y.
adl_curves_plot_on_figure()
void adl_curves_plot_on_figure (Figure figure)
Definition at line 1401 of file striped_Almog_Draw_Library.h.
References adl_axis_draw_on_figure(), adl_line_draw(), adl_linear_map(), adl_max_min_values_draw_on_figure(), Figure::background_color, Curve::color, Mat2D::cols, Curve::elements, Curve_ada::elements, Mat2D::elements, Figure::inv_z_buffer_mat, Curve::length, Curve_ada::length, mat2D_fill_uint32(), Figure::max_x, Figure::max_x_pixel, Figure::max_y, Figure::max_y_pixel, Figure::min_x, Figure::min_x_pixel, Figure::min_y, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Mat2D::rows, Figure::src_curve_array, Figure::to_draw_axis, Figure::to_draw_max_min_values, Point::x, and Point::y.
adl_figure_alloc()
Figure adl_figure_alloc (size_t rows, size_t cols, Point top_left_position)
Definition at line 1294 of file striped_Almog_Draw_Library.h.
References ada_init_array, ADL_ASSERT, adl_assert_point_is_valid, ADL_DEFAULT_OFFSET_ZOOM, ADL_FIGURE_PADDING_PRECENTAGE, ADL_MAX_FIGURE_PADDING, Mat2D::cols, Mat2D_uint32::cols, Mat2D::elements, Figure::inv_z_buffer_mat, mat2D_alloc(), mat2D_alloc_uint32(), Figure::max_x, Figure::max_x_pixel, Figure::max_y, Figure::max_y_pixel, Figure::min_x, Figure::min_x_pixel, Figure::min_y, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Mat2D::rows, Mat2D_uint32::rows, Figure::src_curve_array, and Figure::top_left_position.
adl_figure_copy_to_screen()
void adl_figure_copy_to_screen (Mat2D_uint32 screen_mat, Figure figure)
Definition at line 1319 of file striped_Almog_Draw_Library.h.
References adl_point_draw(), Mat2D_uint32::cols, MAT2D_AT_UINT32, Figure::pixels_mat, Mat2D_uint32::rows, Figure::top_left_position, Point::x, and Point::y.
adl_grid_draw()
void adl_grid_draw (Mat2D_uint32 screen_mat, Grid grid, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 1785 of file striped_Almog_Draw_Library.h.
References adl_lines_draw(), Grid::curves, Curve::elements, Curve_ada::elements, Curve::length, and Curve_ada::length.
adl_interpolate_ARGBcolor_on_okLch()
void adl_interpolate_ARGBcolor_on_okLch (uint32_t color1, uint32_t color2, float t, float num_of_rotations, uint32_t * color_out)
Definition at line 1281 of file striped_Almog_Draw_Library.h.
References adl_linear_sRGB_to_okLch(), and adl_okLch_to_linear_sRGB().
Referenced by adl_2Dscalar_interp_on_figure().
adl_line_draw()
void adl_line_draw (Mat2D_uint32 screen_mat, const float x1_input, const float y1_input, const float x2_input, const float y2_input, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 226 of file striped_Almog_Draw_Library.h.
References ADL_ASSERT, ADL_MAX_POINT_VAL, adl_point_draw(), Mat2D_uint32::cols, Offset_zoom_param::offset_x, Offset_zoom_param::offset_y, Mat2D_uint32::rows, and Offset_zoom_param::zoom_multiplier.
Referenced by adl_arrow_draw(), adl_character_draw(), adl_curves_plot_on_figure(), adl_lines_draw(), adl_lines_loop_draw(), adl_rectangle_draw_min_max(), adl_rectangle_fill_min_max(), and adl_tri_draw().
adl_linear_map()
float adl_linear_map (float s, float min_in, float max_in, float min_out, float max_out)
Definition at line 1184 of file striped_Almog_Draw_Library.h.
Referenced by adl_2Dscalar_interp_on_figure(), and adl_curves_plot_on_figure().
adl_linear_sRGB_to_okLab()
void adl_linear_sRGB_to_okLab (uint32_t hex_ARGB, float * L, float * a, float * b)
Definition at line 1234 of file striped_Almog_Draw_Library.h.
References HexARGB_RGB_VAR.
Referenced by adl_linear_sRGB_to_okLch().
adl_linear_sRGB_to_okLch()
void adl_linear_sRGB_to_okLch (uint32_t hex_ARGB, float * L, float * c, float * h_deg)
Definition at line 1267 of file striped_Almog_Draw_Library.h.
References adl_linear_sRGB_to_okLab(), and PI.
Referenced by adl_interpolate_ARGBcolor_on_okLch().
adl_lines_draw()
void adl_lines_draw (const Mat2D_uint32 screen_mat, const Point * points, const size_t len, const uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 288 of file striped_Almog_Draw_Library.h.
References adl_line_draw(), and points.
Referenced by adl_grid_draw().
adl_lines_loop_draw()
void adl_lines_loop_draw (const Mat2D_uint32 screen_mat, const Point * points, const size_t len, const uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 295 of file striped_Almog_Draw_Library.h.
References adl_line_draw(), and points.
Referenced by adl_quad_draw().
adl_max_min_values_draw_on_figure()
void adl_max_min_values_draw_on_figure (Figure figure)
Definition at line 1342 of file striped_Almog_Draw_Library.h.
References ADL_FIGURE_AXIS_COLOR, ADL_MAX_CHARACTER_OFFSET, ADL_MIN_CHARACTER_OFFSET, adl_sentence_draw(), Figure::max_x, Figure::max_x_pixel, Figure::max_y, Figure::max_y_pixel, Figure::min_x, Figure::min_x_pixel, Figure::min_y, Figure::min_y_pixel, Figure::offset_zoom_param, Figure::pixels_mat, Mat2D_uint32::rows, Figure::x_axis_head_size, and Figure::y_axis_head_size.
Referenced by adl_2Dscalar_interp_on_figure(), and adl_curves_plot_on_figure().
adl_okLab_to_linear_sRGB()
void adl_okLab_to_linear_sRGB (float L, float a, float b, uint32_t * hex_ARGB)
Definition at line 1251 of file striped_Almog_Draw_Library.h.
References RGBA_hexARGB.
Referenced by adl_okLch_to_linear_sRGB().
adl_okLch_to_linear_sRGB()
void adl_okLch_to_linear_sRGB (float L, float c, float h_deg, uint32_t * hex_ARGB)
Definition at line 1274 of file striped_Almog_Draw_Library.h.
References adl_okLab_to_linear_sRGB(), and PI.
Referenced by adl_interpolate_ARGBcolor_on_okLch().
adl_point_draw()
void adl_point_draw (Mat2D_uint32 screen_mat, int x, int y, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 211 of file striped_Almog_Draw_Library.h.
References Mat2D_uint32::cols, HexARGB_RGBA_VAR, MAT2D_AT_UINT32, Offset_zoom_param::offset_x, Offset_zoom_param::offset_y, RGBA_hexARGB, Mat2D_uint32::rows, and Offset_zoom_param::zoom_multiplier.
Referenced by adl_circle_draw(), adl_circle_fill(), adl_figure_copy_to_screen(), adl_line_draw(), adl_quad_fill(), adl_quad_fill_interpolate_color_mean_value(), adl_quad_fill_interpolate_normal_mean_value(), adl_tri_fill_Pinedas_rasterizer(), adl_tri_fill_Pinedas_rasterizer_interpolate_color(), and adl_tri_fill_Pinedas_rasterizer_interpolate_normal().
adl_quad2tris()
void adl_quad2tris (Quad quad, Tri * tri1, Tri * tri2, char split_line[])
Definition at line 1188 of file striped_Almog_Draw_Library.h.
References Tri::colors, Quad::colors, Tri::light_intensity, Quad::light_intensity, Tri::points, Quad::points, Tri::to_draw, and Quad::to_draw.
adl_quad_draw()
void adl_quad_draw (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 698 of file striped_Almog_Draw_Library.h.
References adl_lines_loop_draw(), and Quad::points.
Referenced by adl_quad_mesh_draw().
adl_quad_fill()
void adl_quad_fill (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 703 of file striped_Almog_Draw_Library.h.
References adl_point_draw(), Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, Quad::light_intensity, MAT2D_AT, Quad::points, RGBA_hexARGB, Mat2D_uint32::rows, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_quad_mesh_fill().
adl_quad_fill_interpolate_color_mean_value()
void adl_quad_fill_interpolate_color_mean_value (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, Offset_zoom_param offset_zoom_param)
Definition at line 832 of file striped_Almog_Draw_Library.h.
References adl_point_draw(), adl_tan_half_angle(), Quad::colors, Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, Quad::light_intensity, MAT2D_AT, Quad::points, RGBA_hexARGB, Mat2D_uint32::rows, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_2Dscalar_interp_on_figure(), and adl_quad_mesh_fill_interpolate_color().
adl_quad_fill_interpolate_normal_mean_value()
void adl_quad_fill_interpolate_normal_mean_value (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Quad quad, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 768 of file striped_Almog_Draw_Library.h.
References adl_point_draw(), adl_tan_half_angle(), Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, Quad::light_intensity, MAT2D_AT, Quad::points, RGBA_hexARGB, Mat2D_uint32::rows, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_quad_mesh_fill_interpolate_normal().
adl_quad_mesh_draw()
void adl_quad_mesh_draw (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 906 of file striped_Almog_Draw_Library.h.
References adl_assert_quad_is_valid, adl_quad_draw(), Quad_mesh::elements, Quad_mesh::length, and Quad::to_draw.
adl_quad_mesh_fill()
void adl_quad_mesh_fill (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 915 of file striped_Almog_Draw_Library.h.
References adl_assert_quad_is_valid, adl_quad_fill(), Quad_mesh::elements, Quad_mesh::length, and Quad::to_draw.
adl_quad_mesh_fill_interpolate_color()
void adl_quad_mesh_fill_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, Offset_zoom_param offset_zoom_param)
Definition at line 938 of file striped_Almog_Draw_Library.h.
References adl_assert_quad_is_valid, adl_quad_fill_interpolate_color_mean_value(), Quad_mesh::elements, Quad_mesh::length, and Quad::to_draw.
adl_quad_mesh_fill_interpolate_normal()
void adl_quad_mesh_fill_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Quad_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 924 of file striped_Almog_Draw_Library.h.
References adl_assert_quad_is_valid, adl_quad_fill_interpolate_normal_mean_value(), Quad_mesh::elements, HexARGB_RGBA_VAR, Quad_mesh::length, and Quad::to_draw.
adl_rectangle_draw_min_max()
void adl_rectangle_draw_min_max (Mat2D_uint32 screen_mat, int min_x, int max_x, int min_y, int max_y, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 685 of file striped_Almog_Draw_Library.h.
References adl_line_draw().
Referenced by adl_character_draw().
adl_rectangle_fill_min_max()
void adl_rectangle_fill_min_max (Mat2D_uint32 screen_mat, int min_x, int max_x, int min_y, int max_y, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 692 of file striped_Almog_Draw_Library.h.
References adl_line_draw().
Referenced by adl_character_draw().
adl_sentence_draw()
void adl_sentence_draw (Mat2D_uint32 screen_mat, const char sentence[], size_t len, const int x_top_left, const int y_top_left, const int hight_pixel, const uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 675 of file striped_Almog_Draw_Library.h.
References adl_character_draw(), ADL_MAX_CHARACTER_OFFSET, and ADL_MIN_CHARACTER_OFFSET.
Referenced by adl_max_min_values_draw_on_figure().
adl_tan_half_angle()
float adl_tan_half_angle (Point vi, Point vj, Point p, float li, float lj)
Definition at line 1175 of file striped_Almog_Draw_Library.h.
References Point::x, and Point::y.
Referenced by adl_quad_fill_interpolate_color_mean_value(), and adl_quad_fill_interpolate_normal_mean_value().
adl_tri_draw()
void adl_tri_draw (Mat2D_uint32 screen_mat, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 969 of file striped_Almog_Draw_Library.h.
References adl_line_draw(), Tri::points, tri, Point::x, and Point::y.
Referenced by adl_tri_mesh_draw().
adl_tri_fill_Pinedas_rasterizer()
void adl_tri_fill_Pinedas_rasterizer (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 975 of file striped_Almog_Draw_Library.h.
References adl_point_draw(), Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, is_top_left, Tri::light_intensity, MAT2D_AT, MATRIX2D_ASSERT, Tri::points, RGBA_hexARGB, Mat2D_uint32::rows, tri, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_tri_mesh_fill_Pinedas_rasterizer().
adl_tri_fill_Pinedas_rasterizer_interpolate_color()
void adl_tri_fill_Pinedas_rasterizer_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, Offset_zoom_param offset_zoom_param)
Definition at line 1027 of file striped_Almog_Draw_Library.h.
References adl_point_draw(), Tri::colors, Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, is_top_left, Tri::light_intensity, MAT2D_AT, MATRIX2D_ASSERT, Tri::points, RGBA_hexARGB, Mat2D_uint32::rows, tri, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_color().
adl_tri_fill_Pinedas_rasterizer_interpolate_normal()
void adl_tri_fill_Pinedas_rasterizer_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer, Tri tri, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 1087 of file striped_Almog_Draw_Library.h.
References adl_point_draw(), Mat2D_uint32::cols, edge_cross_point, HexARGB_RGBA_VAR, is_top_left, Tri::light_intensity, MAT2D_AT, MATRIX2D_ASSERT, Tri::points, RGBA_hexARGB, Mat2D_uint32::rows, tri, Point::w, Point::x, Point::y, and Point::z.
Referenced by adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal().
adl_tri_mesh_draw()
void adl_tri_mesh_draw (Mat2D_uint32 screen_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 1139 of file striped_Almog_Draw_Library.h.
References adl_tri_draw(), Tri_mesh::elements, Tri_mesh::length, Tri::to_draw, and tri.
adl_tri_mesh_fill_Pinedas_rasterizer()
void adl_tri_mesh_fill_Pinedas_rasterizer (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 1148 of file striped_Almog_Draw_Library.h.
References adl_assert_tri_is_valid, adl_tri_fill_Pinedas_rasterizer(), Tri_mesh::elements, Tri_mesh::length, Tri::to_draw, and tri.
adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_color()
void adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_color (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, Offset_zoom_param offset_zoom_param)
Definition at line 1157 of file striped_Almog_Draw_Library.h.
References adl_assert_tri_is_valid, adl_tri_fill_Pinedas_rasterizer_interpolate_color(), Tri_mesh::elements, Tri_mesh::length, Tri::to_draw, and tri.
adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal()
void adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer_mat, Tri_mesh mesh, uint32_t color, Offset_zoom_param offset_zoom_param)
Definition at line 1166 of file striped_Almog_Draw_Library.h.
References adl_assert_tri_is_valid, adl_tri_fill_Pinedas_rasterizer_interpolate_normal(), Tri_mesh::elements, Tri_mesh::length, Tri::to_draw, and tri.