striped_Almog_String_Manipulation.h File Reference
#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <assert.h>
Macros
#define ASM_MAXDIR 100
#define ASM_MAX_LEN_LINE (int)1e3
#define asm_dprintSTRING(expr) printf(#expr ` = %s\n`, expr)
#define asm_dprintCHAR(expr) printf(#expr ` = %c\n`, expr)
#define asm_dprintINT(expr) printf(#expr ` = %d\n`, expr)
#define asm_dprintSIZE_T(expr) printf(#expr ` = %zu\n`, expr)
Functions
int asm_get_line (FILE *fp, char *dst)
int asm_length (char *str)
int asm_get_next_word_from_line (char *dst, char *src, char seperator)
void asm_copy_array_by_indesies (char *target, int start, int end, char *src)
int asm_get_word_and_cut (char *dst, char *src, char seperator)
int asm_str_in_str (char *src, char *word2search)
int asm_strncmp (const char *s1, const char *s2, const int N)
Macro Definition Documentation
asm_dprintCHAR
#define asm_dprintCHAR(expr) printf(#expr ` = %c\n`, expr)
Definition at line 10 of file striped_Almog_String_Manipulation.h.
asm_dprintINT
#define asm_dprintINT(expr) printf(#expr ` = %d\n`, expr)
Definition at line 11 of file striped_Almog_String_Manipulation.h.
asm_dprintSIZE_T
#define asm_dprintSIZE_T(expr) printf(#expr ` = %zu\n`, expr)
Definition at line 12 of file striped_Almog_String_Manipulation.h.
asm_dprintSTRING
#define asm_dprintSTRING(expr) printf(#expr ` = %s\n`, expr)
Definition at line 9 of file striped_Almog_String_Manipulation.h.
ASM_MAX_LEN_LINE
#define ASM_MAX_LEN_LINE (int)1e3
Definition at line 8 of file striped_Almog_String_Manipulation.h.
ASM_MAXDIR
#define ASM_MAXDIR 100
Definition at line 7 of file striped_Almog_String_Manipulation.h.
Function Documentation
asm_copy_array_by_indesies()
void asm_copy_array_by_indesies (char * target, int start, int end, char * src)
Definition at line 76 of file striped_Almog_String_Manipulation.h.
Referenced by asm_get_word_and_cut().
asm_get_line()
int asm_get_line (FILE * fp, char * dst)
Definition at line 23 of file striped_Almog_String_Manipulation.h.
References ASM_MAX_LEN_LINE.
asm_get_next_word_from_line()
int asm_get_next_word_from_line (char * dst, char * src, char seperator)
Definition at line 50 of file striped_Almog_String_Manipulation.h.
Referenced by asm_get_word_and_cut().
asm_get_word_and_cut()
int asm_get_word_and_cut (char * dst, char * src, char seperator)
Definition at line 85 of file striped_Almog_String_Manipulation.h.
References asm_copy_array_by_indesies(), asm_get_next_word_from_line(), and asm_length().
asm_length()
int asm_length (char * str)
Definition at line 41 of file striped_Almog_String_Manipulation.h.
Referenced by asm_get_word_and_cut(), and asm_str_in_str().
asm_str_in_str()
int asm_str_in_str (char * src, char * word2search)
Definition at line 98 of file striped_Almog_String_Manipulation.h.
References asm_length(), and asm_strncmp().
asm_strncmp()
int asm_strncmp (const char * s1, const char * s2, const int N)
Definition at line 109 of file striped_Almog_String_Manipulation.h.
Referenced by asm_str_in_str().