src/include/Almog_Engine.h File Reference
Software 3D rendering and scene utilities for meshes, camera, and projection.
#include `./Almog_Dynamic_Array.h`
#include `./Matrix2D.h`
#include `./Almog_Draw_Library.h`
#include `./Almog_String_Manipulation.h`
#include <assert.h>
#include <math.h>
#include <stdbool.h>
#include <float.h>
#include <stdint.h>
#include <errno.h>
#include <string.h>
Classes
struct Tri_mesh_array
struct Quad_mesh_array
struct Camera
struct Light_source
struct Material
struct Scene
Macros
#define AE_ASSERT assert
#define STL_HEADER_SIZE 80
#define STL_NUM_SIZE 4
#define STL_SIZE_FOREACH_TRI 50
#define STL_ATTRIBUTE_BITS_SIZE 2
#define ARGB_hexARGB(a, r, g, b) 0x01000000l*(uint8_t)(a) + 0x00010000*(uint8_t)(r) + 0x00000100*(uint8_t)(g) + 0x00000001*(uint8_t)(b)
#define AE_MAX_POINT_VAL 1e5
#define ae_assert_point_is_valid(p)
#define ae_assert_tri_is_valid(tri)
#define ae_assert_quad_is_valid(quad)
#define ae_point_normalize_xyz_norma(p, norma)
#define ae_point_calc_norma(p) sqrt(((p).x * (p).x) + ((p).y * (p).y) + ((p).z * (p).z))
#define ae_point_add_point(p, p1, p2)
#define ae_point_sub_point(p, p1, p2)
#define ae_point_dot_point(p1, p2) (((p1).x * (p2).x) + ((p1).y * (p2).y) + ((p1).z * (p2).z))
#define ae_point_mult(p, const)
#define ae_points_equal(p1, p2) (p1).x == (p2).x && (p1).y == (p2).y && (p1).z == (p2).z
#define TRI_MESH_ARRAY
#define QUAD_MESH_ARRAY
#define AE_PRINT_TRI(tri) ae_print_tri(tri, #tri, 0)
#define AE_PRINT_MESH(mesh) ae_print_tri_mesh(mesh, #mesh, 0)
Enumerations
enum Lighting_mode { AE_LIGHTING_FLAT
, AE_LIGHTING_SMOOTH
, AE_LIGHTING_MODE_LENGTH
 }
Functions
Tri ae_tri_create (Point p1, Point p2, Point p3)
Create a triangle from three points.
void ae_tri_mesh_create_copy (Tri_mesh *des, Tri *src_elements, size_t len)
Append copies of triangles to a destination Tri_mesh (resets destination length first).
void ae_camera_init (Scene *scene, int window_h, int window_w)
Initialize the camera part of a Scene.
void ae_camera_free (Scene *scene)
Free camera-related allocations in a Scene.
Scene ae_scene_init (int window_h, int window_w)
Create and initialize a Scene.
void ae_scene_free (Scene *scene)
Free all resources owned by a Scene.
void ae_camera_reset_pos (Scene *scene)
Reset camera orientation and position to initial state.
void ae_point_to_mat2D (Point p, Mat2D m)
Write a Point into a Mat2D vector.
Point ae_mat2D_to_point (Mat2D m)
Read a 3x1 Mat2D vector into a Point.
Tri_mesh ae_tri_mesh_get_from_obj_file (char *file_path)
Load a triangle mesh from a Wavefront OBJ file.
Tri_mesh ae_tri_mesh_get_from_stl_file (char *file_path)
Load a triangle mesh from a binary STL file.
Tri_mesh ae_tri_mesh_get_from_file (char *file_path)
Load a triangle mesh from a file (OBJ or STL).
void ae_tri_mesh_appand_copy (Tri_mesh_array *mesh_array, Tri_mesh mesh)
Append a copy of a Tri_mesh into a Tri_mesh_array.
Tri_mesh ae_tri_mesh_get_from_quad_mesh (Quad_mesh q_mesh)
Convert a Quad_mesh into a Tri_mesh.
void ae_print_points (Curve p)
Print a list of points to stdout.
void ae_print_tri (Tri tri, char *name, size_t padding)
Print a triangle to stdout.
void ae_print_tri_mesh (Tri_mesh mesh, char *name, size_t padding)
Print all triangles in a mesh to stdout.
Point ae_point_normalize_xyz (Point p)
Normalize a point's xyz to unit length.
void ae_tri_set_normals (Tri *tri)
Compute and set per-vertex normals for a triangle.
Point ae_tri_get_average_normal (Tri tri)
Compute the average of the three vertex normals of a triangle.
Point ae_tri_get_average_point (Tri tri)
Compute the average of the three vertices of a triangle.
void ae_tri_calc_normal (Mat2D normal, Tri tri)
Compute the face normal of a triangle.
void ae_tri_mesh_translate (Tri_mesh mesh, float x, float y, float z)
Translate a triangle mesh by (x, y, z).
void ae_tri_mesh_rotate_Euler_xyz (Tri_mesh mesh, float phi_deg, float theta_deg, float psi_deg)
Rotate a triangle mesh using XYZ Euler angles (degrees).
void ae_tri_mesh_set_bounding_box (Tri_mesh mesh, float *x_min, float *x_max, float *y_min, float *y_max, float *z_min, float *z_max)
Compute the axis-aligned bounding box of a triangle mesh.
void ae_tri_mesh_normalize (Tri_mesh mesh)
Normalize mesh coordinates to [-1, 1], centered at origin.
void ae_tri_mesh_flip_normals (Tri_mesh mesh)
Flip triangle winding and recompute per-vertex normals.
void ae_tri_mesh_set_normals (Tri_mesh mesh)
Recompute per-vertex normals for all triangles in a mesh.
void ae_quad_set_normals (Quad *quad)
Compute and set per-vertex normals for a quad.
Point ae_quad_get_average_normal (Quad quad)
Compute the average of the four vertex normals of a quad.
Point ae_quad_get_average_point (Quad quad)
Compute the average of the four vertices of a quad.
void ae_quad_calc_normal (Mat2D normal, Quad quad)
Compute the face normal of a quad using the first three vertices.
void ae_curve_copy (Curve *des, Curve src)
Copy a Curve (ADA array of points).
void ae_tri_calc_light_intensity (Tri *tri, Scene *scene, Lighting_mode lighting_mode)
Compute per-vertex lighting intensity for a triangle.
void ae_quad_calc_light_intensity (Quad *quad, Scene *scene, Lighting_mode lighting_mode)
Compute per-vertex lighting intensity for a quad.
Point ae_line_itersect_plane (Mat2D plane_p, Mat2D plane_n, Mat2D line_start, Mat2D line_end, float *t)
Intersect a line segment with a plane.
int ae_line_clip_with_plane (Point start_in, Point end_in, Mat2D plane_p, Mat2D plane_n, Point *start_out, Point *end_out)
Clip a line segment against a plane.
float ae_signed_dist_point_and_plane (Point p, Mat2D plane_p, Mat2D plane_n)
Signed distance from a point to a plane.
int ae_tri_clip_with_plane (Tri tri_in, Mat2D plane_p, Mat2D plane_n, Tri *tri_out1, Tri *tri_out2)
Clip a triangle against a plane.
int ae_quad_clip_with_plane (Quad quad_in, Mat2D plane_p, Mat2D plane_n, Quad *quad_out1, Quad *quad_out2)
Clip a quad against a plane.
void ae_projection_mat_set (Mat2D proj_mat, float aspect_ratio, float FOV_deg, float z_near, float z_far)
Build a perspective projection matrix.
void ae_view_mat_set (Mat2D view_mat, Camera camera, Mat2D up)
Build a right-handed view matrix from a Camera and up vector.
Point ae_point_project_world2screen (Mat2D view_mat, Mat2D proj_mat, Point src, int window_w, int window_h)
Project a point from world space directly to screen space.
Point ae_point_project_world2view (Mat2D view_mat, Point src)
Transform a point from world space to view space.
Point ae_point_project_view2screen (Mat2D proj_mat, Point src, int window_w, int window_h)
Project a view-space point to screen space.
void ae_line_project_world2screen (Mat2D view_mat, Mat2D proj_mat, Point start_src, Point end_src, int window_w, int window_h, Point *start_des, Point *end_des, Scene *scene)
Project and near-clip a world-space line segment to screen space.
Tri ae_tri_transform_to_view (Mat2D view_mat, Tri tri)
Transform a triangle from world space to view space.
Tri_mesh ae_tri_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Tri tri, int window_w, int window_h, Scene *scene, Lighting_mode lighting_mode)
Project a single world-space triangle to screen space with clipping.
void ae_tri_mesh_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Tri_mesh *des, Tri_mesh src, int window_w, int window_h, Scene *scene, Lighting_mode lighting_mode)
Project a triangle mesh from world to screen space with clipping.
Quad ae_quad_transform_to_view (Mat2D view_mat, Quad quad)
Transform a quad from world space to view space.
Quad_mesh ae_quad_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Quad quad, int window_w, int window_h, Scene *scene, Lighting_mode lighting_mode)
Project a single world-space quad to screen space with clipping.
void ae_quad_mesh_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Quad_mesh *des, Quad_mesh src, int window_w, int window_h, Scene *scene, Lighting_mode lighting_mode)
Project a quad mesh from world to screen space with clipping.
void ae_curve_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Curve *des, Curve src, int window_w, int window_h, Scene *scene)
Project and clip a polyline (Curve) from world to screen space.
void ae_curve_ada_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Curve_ada *des, Curve_ada src, int window_w, int window_h, Scene *scene)
Project and clip an array of polylines from world to screen space.
void ae_grid_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Grid des, Grid src, int window_w, int window_h, Scene *scene)
Project and clip all polylines in a Grid from world to screen.
void ae_tri_swap (Tri *v, int i, int j)
Swap two triangles in an array.
bool ae_tri_compare (Tri t1, Tri t2)
Compare two triangles for sorting by depth.
void ae_tri_qsort (Tri *v, int left, int right)
Quicksort an array of triangles by depth.
double ae_linear_map (double s, double min_in, double max_in, double min_out, double max_out)
Linearly map a scalar from one range to another.
void ae_z_buffer_copy_to_screen (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer)
Visualize an inverse-z buffer by writing a grayscale image.
Detailed Description
Software 3D rendering and scene utilities for meshes, camera, and projection.
A small, header-driven 3D engine providing:
Scene and camera setup (projection/view matrices, Euler navigation).
Triangle and quad mesh loading (OBJ/ASCII+binary STL), normalization, transforms, and per-vertex/face normals.
Back-face culling, near-plane and screen-space polygon clipping.
Perspective projection (world->view->screen) and line/grid helpers.
Basic Phong-like lighting (ambient, diffuse, specular) with flat/smooth modes.
Simple z-buffer visualization utility.
Inspiration This code is heavily inspired by the 3D engine of 'OneLoneCoder' in C++. You can find the source code in: https://github.com/OneLoneCoder/Javidx9/tree/master/ConsoleGameEngine/BiggerProjects/Engine3D . featured in this video of his: https://youtu.be/ih20l3pJoeU?si=CzQ8rjk5ZEOlqEHN.
Note
- Depends on Almog_Dynamic_Array.h, Matrix2D.h, Almog_Draw_Library.h, and Almog_String_Manipulation.h for math, containers, and I/O utilities.
- All public functions are prefixed with 'ae_'.
- Define ALMOG_ENGINE_IMPLEMENTATION in exactly one translation unit to compile the function bodies.
Definition in file Almog_Engine.h.
Macro Definition Documentation
AE_ASSERT
#define AE_ASSERT assert
Definition at line 44 of file Almog_Engine.h.
ae_assert_point_is_valid
#define ae_assert_point_is_valid(p)
Value:
        AE_ASSERT(isfinite((p).x) && isfinite((p).y) && isfinite((p).z) && isfinite((p).w)); \
        AE_ASSERT((p).x > -AE_MAX_POINT_VAL && (p).x < AE_MAX_POINT_VAL); \
        AE_ASSERT((p).y > -AE_MAX_POINT_VAL && (p).y < AE_MAX_POINT_VAL); \
        AE_ASSERT((p).z > -AE_MAX_POINT_VAL && (p).z < AE_MAX_POINT_VAL); \
        AE_ASSERT((p).w > -AE_MAX_POINT_VAL && (p).w < AE_MAX_POINT_VAL);
Definition at line 89 of file Almog_Engine.h.
ae_assert_quad_is_valid
#define ae_assert_quad_is_valid(quad)
Value:
        ae_assert_point_is_valid((quad).points[0]); \
        ae_assert_point_is_valid((quad).points[1]); \
        ae_assert_point_is_valid((quad).points[2]); \
        ae_assert_point_is_valid((quad).points[3])
Definition at line 97 of file Almog_Engine.h.
ae_assert_tri_is_valid
#define ae_assert_tri_is_valid(tri)
Value:
        ae_assert_point_is_valid((tri).points[0]); \
        ae_assert_point_is_valid((tri).points[1]); \
        ae_assert_point_is_valid((tri).points[2])
Definition at line 94 of file Almog_Engine.h.
AE_MAX_POINT_VAL
#define AE_MAX_POINT_VAL 1e5
Definition at line 88 of file Almog_Engine.h.
ae_point_add_point
#define ae_point_add_point(p, p1, p2)
Value:
        (p).x = (p1).x + (p2).x; \
        (p).y = (p1).y + (p2).y; \
        (p).z = (p1).z + (p2).z; \
        (p).w = (p1).w + (p2).w
Definition at line 105 of file Almog_Engine.h.
ae_point_calc_norma
#define ae_point_calc_norma(p) sqrt(((p).x * (p).x) + ((p).y * (p).y) + ((p).z * (p).z))
Definition at line 104 of file Almog_Engine.h.
ae_point_dot_point
#define ae_point_dot_point(p1, p2) (((p1).x * (p2).x) + ((p1).y * (p2).y) + ((p1).z * (p2).z))
Definition at line 113 of file Almog_Engine.h.
ae_point_mult
#define ae_point_mult(p, const)
Value:
        (p).x *= const; \
        (p).y *= const; \
        (p).z *= const
Definition at line 114 of file Almog_Engine.h.
ae_point_normalize_xyz_norma
#define ae_point_normalize_xyz_norma(p, norma)
Value:
        (p).x = (p).x / norma; \
        (p).y = (p).y / norma; \
        (p).z = (p).z / norma
Definition at line 101 of file Almog_Engine.h.
ae_point_sub_point
#define ae_point_sub_point(p, p1, p2)
Value:
        (p).x = (p1).x - (p2).x; \
        (p).y = (p1).y - (p2).y; \
        (p).z = (p1).z - (p2).z; \
        (p).w = (p1).w - (p2).w
Definition at line 109 of file Almog_Engine.h.
ae_points_equal
#define ae_points_equal(p1, p2) (p1).x == (p2).x && (p1).y == (p2).y && (p1).z == (p2).z
Definition at line 117 of file Almog_Engine.h.
AE_PRINT_MESH
#define AE_PRINT_MESH(mesh) ae_print_tri_mesh(mesh, #mesh, 0)
Definition at line 267 of file Almog_Engine.h.
AE_PRINT_TRI
#define AE_PRINT_TRI(tri) ae_print_tri(tri, #tri, 0)
Definition at line 266 of file Almog_Engine.h.
ARGB_hexARGB
#define ARGB_hexARGB(a, r, g, b) 0x01000000l*(uint8_t)(a) + 0x00010000*(uint8_t)(r) + 0x00000100*(uint8_t)(g) + 0x00000001*(uint8_t)(b)
Definition at line 83 of file Almog_Engine.h.
QUAD_MESH_ARRAY
#define QUAD_MESH_ARRAY
Definition at line 136 of file Almog_Engine.h.
STL_ATTRIBUTE_BITS_SIZE
#define STL_ATTRIBUTE_BITS_SIZE 2
Definition at line 71 of file Almog_Engine.h.
STL_HEADER_SIZE
#define STL_HEADER_SIZE 80
Definition at line 59 of file Almog_Engine.h.
STL_NUM_SIZE
#define STL_NUM_SIZE 4
Definition at line 63 of file Almog_Engine.h.
STL_SIZE_FOREACH_TRI
#define STL_SIZE_FOREACH_TRI 50
Definition at line 67 of file Almog_Engine.h.
TRI_MESH_ARRAY
#define TRI_MESH_ARRAY
Definition at line 127 of file Almog_Engine.h.
Enumeration Type Documentation
Lighting_mode
enum Lighting_mode
Enumerator
AE_LIGHTING_FLAT
AE_LIGHTING_SMOOTH
AE_LIGHTING_MODE_LENGTH
Definition at line 120 of file Almog_Engine.h.
Function Documentation
ae_camera_free()
void ae_camera_free (Scene * scene)
Free camera-related allocations in a Scene.
Frees all Mat2D objects owned by scene->camera (init_position, current_position, offset_position, direction, camera_x/y/z).
Parameters
scene Scene whose camera resources will be freed.
Definition at line 366 of file Almog_Engine.h.
References Scene::camera, Camera::camera_x, Camera::camera_y, Camera::camera_z, Camera::current_position, Camera::direction, Camera::init_position, mat2D_free(), and Camera::offset_position.
Referenced by ae_scene_free().
ae_camera_init()
void ae_camera_init (Scene * scene, int window_h, int window_w)
Initialize the camera part of a Scene.
Sets perspective parameters (z_near, z_far, fov, aspect_ratio), allocates camera matrices/vectors, and sets initial position and orientation. The aspect ratio is computed as window_h / window_w.
Parameters
scene Scene whose camera will be initialized.
window_h Window height in pixels.
window_w Window width in pixels.
Definition at line 320 of file Almog_Engine.h.
References Camera::aspect_ratio, Scene::camera, Camera::camera_x, Camera::camera_y, Camera::camera_z, Camera::current_position, Camera::direction, Camera::fov_deg, Camera::init_position, mat2D_alloc(), MAT2D_AT, mat2D_copy(), mat2D_fill(), Camera::offset_position, Camera::pitch_offset_deg, Camera::roll_offset_deg, Camera::yaw_offset_deg, Camera::z_far, and Camera::z_near.
Referenced by ae_scene_init().
ae_camera_reset_pos()
void ae_camera_reset_pos (Scene * scene)
Reset camera orientation and position to initial state.
Resets roll/pitch/yaw to zero, clears offset_position, restores camera basis vectors to identity, and copies current_position from init_position.
Parameters
scene Scene containing the camera to reset.
Definition at line 472 of file Almog_Engine.h.
References Scene::camera, Camera::camera_x, Camera::camera_y, Camera::camera_z, Camera::current_position, Camera::init_position, MAT2D_AT, mat2D_copy(), mat2D_fill(), Camera::offset_position, Camera::pitch_offset_deg, Camera::roll_offset_deg, and Camera::yaw_offset_deg.
Referenced by process_input_window().
ae_curve_ada_project_world2screen()
void ae_curve_ada_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Curve_ada * des, Curve_ada src, int window_w, int window_h, Scene * scene)
Project and clip an array of polylines from world to screen space.
Applies ae_curve_project_world2screen to each element in src and writes into the corresponding element in des. Arrays must be the same length.
Parameters
proj_mat Projection matrix (4x4).
view_mat View matrix (4x4).
des Output array of curves (each overwritten).
src Input array of world-space curves.
window_w Screen width in pixels.
window_h Screen height in pixels.
scene Scene (camera for near plane).
Definition at line 3670 of file Almog_Engine.h.
References ae_curve_project_world2screen(), Curve_ada::elements, and Curve_ada::length.
ae_curve_copy()
void ae_curve_copy (Curve * des, Curve src)
Copy a Curve (ADA array of points).
Clears destination length and appends all points from src.
Parameters
des Destination curve (modified/grown as needed).
src Source curve.
Definition at line 1461 of file Almog_Engine.h.
References ada_appand, Curve::elements, and Curve::length.
Referenced by ae_curve_project_world2screen().
ae_curve_project_world2screen()
void ae_curve_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Curve * des, Curve src, int window_w, int window_h, Scene * scene)
Project and clip a polyline (Curve) from world to screen space.
Projects each segment with near-plane clipping and screen-edge clipping. Segments fully outside are removed. The destination curve is overwritten.
Note
This solution is not prefect. It sometimes delete one more edge then necessary, but I think that it won't brake.
Parameters
proj_mat Projection matrix (4x4).
view_mat View matrix (4x4).
des Output curve (overwritten; ADA array grown as needed).
src Input world-space curve.
window_w Screen width in pixels.
window_h Screen height in pixels.
scene Scene (camera for near plane).
Definition at line 3558 of file Almog_Engine.h.
References ada_remove, ae_curve_copy(), ae_line_clip_with_plane(), ae_line_project_world2screen(), ae_points_equal, Curve::elements, Curve::length, mat2D_alloc(), MAT2D_AT, mat2D_fill(), and mat2D_free().
Referenced by ae_curve_ada_project_world2screen(), and ae_grid_project_world2screen().
ae_grid_project_world2screen()
void ae_grid_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Grid des, Grid src, int window_w, int window_h, Scene * scene)
Project and clip all polylines in a Grid from world to screen.
Applies ae_curve_project_world2screen to each curve in the grid.
Parameters
proj_mat Projection matrix (4x4).
view_mat View matrix (4x4).
des Output grid (curves overwritten).
src Input world-space grid.
window_w Screen width in pixels.
window_h Screen height in pixels.
scene Scene (camera for near plane).
Definition at line 3691 of file Almog_Engine.h.
References ae_curve_project_world2screen(), Grid::curves, Curve_ada::elements, and Curve_ada::length.
Referenced by update().
ae_line_clip_with_plane()
int ae_line_clip_with_plane (Point start_in, Point end_in, Mat2D plane_p, Mat2D plane_n, Point * start_out, Point * end_out)
Clip a line segment against a plane.
Returns the portion of the line segment [start_in, end_in] that lies on or inside the plane (signed distance >= 0). plane_n is normalized inside the function.
Parameters
start_in Input start point (world or view space).
end_in Input end point.
plane_p Plane reference point (3x1).
plane_n Plane normal (3x1).
start_out Output clipped start point (if visible).
end_out Output clipped end point (if visible).
Returns
int 0 if fully outside, 1 if fully or partially inside (outputs are valid), -1 on error.
Definition at line 1720 of file Almog_Engine.h.
References ae_assert_point_is_valid, ae_line_itersect_plane(), ae_point_to_mat2D(), ae_signed_dist_point_and_plane(), mat2D_alloc(), mat2D_free(), and mat2D_normalize.
Referenced by ae_curve_project_world2screen(), and ae_line_project_world2screen().
ae_line_itersect_plane()
Point ae_line_itersect_plane (Mat2D plane_p, Mat2D plane_n, Mat2D line_start, Mat2D line_end, float * t)
Intersect a line segment with a plane.
Computes intersection of segment [line_start, line_end] with the plane defined by point plane_p and normal plane_n. plane_n is normalized inside the function. The parameter t in [0, 1] is returned via out-parameter.
Note
The Mat2D objects line_start and line_end are temporarily modified internally; pass copies if you must preserve their values.
Parameters
plane_p Plane reference point (3x1).
plane_n Plane normal (3x1).
line_start Segment start point (3x1).
line_end Segment end point (3x1).
t Output parametric distance along the segment (0=start, 1=end).
Returns
Point Intersection point in 3D.
Definition at line 1680 of file Almog_Engine.h.
References ae_mat2D_to_point(), mat2D_add(), mat2D_alloc(), mat2D_dot_product(), mat2D_fill(), mat2D_free(), mat2D_mult(), mat2D_normalize, and mat2D_sub().
Referenced by ae_line_clip_with_plane(), ae_quad_clip_with_plane(), and ae_tri_clip_with_plane().
ae_line_project_world2screen()
void ae_line_project_world2screen (Mat2D view_mat, Mat2D proj_mat, Point start_src, Point end_src, int window_w, int window_h, Point * start_des, Point * end_des, Scene * scene)
Project and near-clip a world-space line segment to screen space.
Transforms the segment to view space, clips it against the near plane at z = z_near + 0.01, then projects to screen space. If fully clipped, both outputs are set to the sentinel (-1, -1, 1, 1).
Parameters
view_mat View matrix (4x4).
proj_mat Projection matrix (4x4).
start_src World-space start point.
end_src World-space end point.
window_w Screen width in pixels.
window_h Screen height in pixels.
start_des Output screen-space start point (or sentinel).
end_des Output screen-space end point (or sentinel).
scene Scene (used for near plane distance).
Definition at line 2933 of file Almog_Engine.h.
References ae_line_clip_with_plane(), ae_point_project_view2screen(), ae_point_project_world2view(), Scene::camera, mat2D_alloc(), MAT2D_AT, mat2D_fill(), mat2D_free(), and Camera::z_near.
Referenced by ae_curve_project_world2screen().
ae_linear_map()
double ae_linear_map (double s, double min_in, double max_in, double min_out, double max_out)
Linearly map a scalar from one range to another.
Computes min_out + (s - min_in) * (max_out - min_out) / (max_in - min_in).
Parameters
s Input scalar.
min_in Input range minimum.
max_in Input range maximum.
min_out Output range minimum.
max_out Output range maximum.
Returns
double Mapped scalar.
Definition at line 3770 of file Almog_Engine.h.
Referenced by ae_z_buffer_copy_to_screen().
ae_mat2D_to_point()
Point ae_mat2D_to_point (Mat2D m)
Read a 3x1 Mat2D vector into a Point.
Reads x, y, z from m(0..2,0) and returns a Point with w=1.
Parameters
m Source matrix (3x1).
Returns
Point The corresponding point with w=1.
Definition at line 522 of file Almog_Engine.h.
References MAT2D_AT, and Point::x.
Referenced by ae_line_itersect_plane(), ae_quad_calc_light_intensity(), ae_quad_set_normals(), ae_tri_calc_light_intensity(), and ae_tri_set_normals().
ae_point_normalize_xyz()
Point ae_point_normalize_xyz (Point p)
Normalize a point's xyz to unit length.
Divides x, y, z by their Euclidean norm. w is preserved unchanged.
Parameters
p Input point.
Returns
Point Unit-length point (xyz), with original w.
Definition at line 976 of file Almog_Engine.h.
References ae_point_calc_norma, Point::w, Point::x, Point::y, and Point::z.
Referenced by ae_quad_calc_light_intensity(), ae_quad_get_average_normal(), ae_scene_init(), ae_tri_calc_light_intensity(), and ae_tri_get_average_normal().
ae_point_project_view2screen()
Point ae_point_project_view2screen (Mat2D proj_mat, Point src, int window_w, int window_h)
Project a view-space point to screen space.
Applies the projection matrix, performs perspective divide if |w| > 1e-3, maps normalized device coords to pixel coordinates: x_screen = (x_ndc + 1) * 0.5 * window_w y_screen = (y_ndc + 1) * 0.5 * window_h
z is z_ndc, w is the clip-space w (or 1 if the original w ~ 0).
Parameters
proj_mat Projection matrix (4x4).
src View-space point.
window_w Screen width in pixels.
window_h Screen height in pixels.
Returns
Point Screen-space point.
Definition at line 2870 of file Almog_Engine.h.
References ae_assert_point_is_valid, mat2D_alloc(), MAT2D_AT, mat2D_dot(), mat2D_free(), Point::w, Point::x, Point::y, and Point::z.
Referenced by ae_line_project_world2screen(), ae_point_project_world2screen(), ae_quad_project_world2screen(), and ae_tri_project_world2screen().
ae_point_project_world2screen()
Point ae_point_project_world2screen (Mat2D view_mat, Mat2D proj_mat, Point src, int window_w, int window_h)
Project a point from world space directly to screen space.
Combines ae_point_project_world2view and ae_point_project_view2screen.
Parameters
view_mat View matrix (4x4).
proj_mat Projection matrix (4x4).
src World-space point.
window_w Screen width in pixels.
window_h Screen height in pixels.
Returns
Point Screen-space point (x,y in pixels). z is post-projection z/w, w is clip-space w.
Definition at line 2806 of file Almog_Engine.h.
References ae_point_project_view2screen(), and ae_point_project_world2view().
ae_point_project_world2view()
Point ae_point_project_world2view (Mat2D view_mat, Point src)
Transform a point from world space to view space.
Multiplies [x y z 1] by view_mat (row-vector convention in this code). Returns the resulting view-space point; w should be 1.
Parameters
view_mat View matrix (4x4).
src World-space point.
Returns
Point View-space point (w=1).
Definition at line 2824 of file Almog_Engine.h.
References AE_ASSERT, ae_assert_point_is_valid, mat2D_alloc(), MAT2D_AT, mat2D_dot(), mat2D_free(), Point::w, Point::x, Point::y, and Point::z.
Referenced by ae_line_project_world2screen(), and ae_point_project_world2screen().
ae_point_to_mat2D()
void ae_point_to_mat2D (Point p, Mat2D m)
Write a Point into a Mat2D vector.
Writes p into m. m must be either 3x1 or 1x3. Only x, y, z are written.
Parameters
p Source point (x, y, z used; w ignored).
m Destination matrix (3x1 or 1x3).
Definition at line 498 of file Almog_Engine.h.
References Mat2D::cols, MAT2D_AT, MATRIX2D_ASSERT, Mat2D::rows, Point::x, Point::y, and Point::z.
Referenced by ae_line_clip_with_plane(), ae_quad_calc_normal(), ae_quad_clip_with_plane(), ae_quad_project_world2screen(), ae_quad_set_normals(), ae_tri_calc_normal(), ae_tri_clip_with_plane(), ae_tri_project_world2screen(), and ae_tri_set_normals().
ae_print_points()
void ae_print_points (Curve p)
Print a list of points to stdout.
Each point is printed as: `point i: (x, y, z)`.
Parameters
p Curve of points to print.
Definition at line 925 of file Almog_Engine.h.
References Curve::elements, Curve::length, Point::x, Point::y, and Point::z.
ae_print_tri()
void ae_print_tri (Tri tri, char * name, size_t padding)
Print a triangle to stdout.
Prints the triangle's vertices and draw flag, with an optional name and indentation padding (spaces).
Parameters
tri Triangle to print.
name Label to print before the triangle.
padding Number of leading spaces for indentation.
Definition at line 942 of file Almog_Engine.h.
References Tri::points, Tri::to_draw, Point::x, Point::y, and Point::z.
Referenced by ae_print_tri_mesh().
ae_print_tri_mesh()
void ae_print_tri_mesh (Tri_mesh mesh, char * name, size_t padding)
Print all triangles in a mesh to stdout.
Each triangle is printed via ae_print_tri with the given padding.
Parameters
mesh Triangle mesh to print.
name Label for the mesh.
padding Number of leading spaces for indentation.
Definition at line 958 of file Almog_Engine.h.
References ae_print_tri(), Tri_mesh::elements, and Tri_mesh::length.
ae_projection_mat_set()
void ae_projection_mat_set (Mat2D proj_mat, float aspect_ratio, float FOV_deg, float z_near, float z_far)
Build a perspective projection matrix.
proj_mat must be 4x4. FOV is in degrees. The matrix maps view-space to clip space consistent with the engine's pipeline; z is mapped using z_far/(z_far - z_near).
Parameters
proj_mat Output 4x4 projection matrix.
aspect_ratio aspect = window_h / window_w.
FOV_deg Vertical field of view in degrees (must be > 0).
z_near Near clipping plane distance (> 0).
z_far Far clipping plane distance (> z_near).
Definition at line 2682 of file Almog_Engine.h.
References AE_ASSERT, Mat2D::cols, MAT2D_AT, mat2D_fill(), PI, and Mat2D::rows.
Referenced by ae_scene_init(), and update().
ae_quad_calc_light_intensity()
void ae_quad_calc_light_intensity (Quad * quad, Scene * scene, Lighting_mode lighting_mode)
Compute per-vertex lighting intensity for a quad.
Same model as ae_tri_calc_light_intensity, applied to four vertices. Results are clamped to [0, 1].
Parameters
quad Quad to update (quad->light_intensity[i] is written).
scene Scene providing light and material parameters.
lighting_mode Flat or smooth lighting mode.
Definition at line 1580 of file Almog_Engine.h.
References AE_LIGHTING_FLAT, AE_LIGHTING_SMOOTH, ae_mat2D_to_point(), ae_point_add_point, ae_point_dot_point, ae_point_mult, ae_point_normalize_xyz(), ae_point_sub_point, ae_quad_get_average_normal(), ae_quad_get_average_point(), Material::c_ambi, Material::c_diff, Material::c_spec, Scene::camera, Camera::current_position, Light_source::light_direction_or_pos, Quad::light_intensity, Light_source::light_intensity, Scene::light_source0, Scene::material0, Quad::normals, Quad::points, Material::specular_power_alpha, and Point::w.
Referenced by ae_quad_project_world2screen().
ae_quad_calc_normal()
void ae_quad_calc_normal (Mat2D normal, Quad quad)
Compute the face normal of a quad using the first three vertices.
normal must be a 3x1 vector. The function writes the normalized cross product of (p1 - p0) x (p2 - p0) into normal.
Parameters
normal Output 3x1 vector for the face normal.
quad Input quad.
Definition at line 1428 of file Almog_Engine.h.
References AE_ASSERT, ae_assert_quad_is_valid, ae_point_to_mat2D(), Mat2D::cols, mat2D_alloc(), mat2D_calc_norma(), mat2D_cross(), mat2D_free(), mat2D_mult(), mat2D_sub(), Quad::points, and Mat2D::rows.
ae_quad_clip_with_plane()
int ae_quad_clip_with_plane (Quad quad_in, Mat2D plane_p, Mat2D plane_n, Quad * quad_out1, Quad * quad_out2)
Clip a quad against a plane.
Splits or discards the quad quad_in against the plane defined by (plane_p, plane_n). plane_n is normalized inside the function.
Parameters
quad_in Input quad.
plane_p Plane reference point (3x1).
plane_n Plane normal (3x1).
quad_out1 First output quad (if any). When output count is 2, this holds one of the resulting polygons (possibly as a quad composed from intersections).
quad_out2 Second output quad (if split).
Returns
int Number of output polygons: 0 (culled), 1, or 2. Returns -1 on error.
Definition at line 2181 of file Almog_Engine.h.
References ae_assert_quad_is_valid, ae_line_itersect_plane(), ae_point_to_mat2D(), ae_signed_dist_point_and_plane(), Quad::colors, mat2D_alloc(), mat2D_free(), mat2D_normalize, Quad::points, and Point::w.
Referenced by ae_quad_mesh_project_world2screen(), and ae_quad_project_world2screen().
ae_quad_get_average_normal()
Point ae_quad_get_average_normal (Quad quad)
Compute the average of the four vertex normals of a quad.
Averages the four vertex normals and normalizes the result.
Parameters
quad Input quad.
Returns
Point The averaged, normalized normal.
Definition at line 1379 of file Almog_Engine.h.
References ae_point_normalize_xyz(), Quad::normals, Point::w, Point::x, Point::y, and Point::z.
Referenced by ae_quad_calc_light_intensity(), and ae_quad_project_world2screen().
ae_quad_get_average_point()
Point ae_quad_get_average_point (Quad quad)
Compute the average of the four vertices of a quad.
Parameters
quad Input quad.
Returns
Point The average point (x, y, z, w are simple averages).
Definition at line 1403 of file Almog_Engine.h.
References Quad::points, Point::w, Point::x, Point::y, and Point::z.
Referenced by ae_quad_calc_light_intensity().
ae_quad_mesh_project_world2screen()
void ae_quad_mesh_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Quad_mesh * des, Quad_mesh src, int window_w, int window_h, Scene * scene, Lighting_mode lighting_mode)
Project a quad mesh from world to screen space with clipping.
Iterates over all quads, applies near-plane and screen-edge clipping, and writes results into des. Quads can be split by clipping, so des may end up with more elements than src.
Parameters
proj_mat Projection matrix (4x4).
view_mat View matrix (4x4).
des Output mesh (cleared and filled; ADA array grown as needed).
src Input world-space quad mesh.
window_w Screen width in pixels.
window_h Screen height in pixels.
scene Scene (camera/light/material).
lighting_mode Flat or smooth lighting mode.
Definition at line 3434 of file Almog_Engine.h.
References ada_appand, ada_insert_unordered, ada_remove_unordered, ae_assert_quad_is_valid, ae_quad_clip_with_plane(), ae_quad_project_world2screen(), Quad_mesh::elements, Quad_mesh::length, mat2D_alloc(), MAT2D_AT, mat2D_fill(), and mat2D_free().
ae_quad_project_world2screen()
Quad_mesh ae_quad_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Quad quad, int window_w, int window_h, Scene * scene, Lighting_mode lighting_mode)
Project a single world-space quad to screen space with clipping.
Computes lighting and visibility, transforms to view space, clips against near plane, and projects to screen space. A quad may produce one or two quads after clipping.
Parameters
proj_mat Projection matrix (4x4).
view_mat View matrix (4x4).
quad World-space quad.
window_w Screen width in pixels.
window_h Screen height in pixels.
scene Scene (camera/light/material).
lighting_mode Flat or smooth lighting mode.
Returns
Quad_mesh An ADA array of resulting screen-space quads. Caller must free result.elements.
Definition at line 3321 of file Almog_Engine.h.
References ada_appand, ada_init_array, ae_assert_quad_is_valid, ae_point_project_view2screen(), ae_point_to_mat2D(), ae_quad_calc_light_intensity(), ae_quad_clip_with_plane(), ae_quad_get_average_normal(), ae_quad_transform_to_view(), Scene::camera, Camera::current_position, Quad_mesh::elements, Quad_mesh::length, Light_source::light_direction_or_pos, Quad::light_intensity, Scene::light_source0, mat2D_alloc(), MAT2D_AT, mat2D_fill(), mat2D_free(), mat2D_sub(), Quad::normals, Quad::points, Quad::to_draw, Point::x, Point::y, Point::z, and Camera::z_near.
Referenced by ae_quad_mesh_project_world2screen().
ae_quad_set_normals()
void ae_quad_set_normals (Quad * quad)
Compute and set per-vertex normals for a quad.
For each vertex, computes the cross product of adjacent edges and normalizes the result. Results are stored in quad->normals[i].
Parameters
quad Quad whose normals will be computed and written.
Definition at line 1336 of file Almog_Engine.h.
References ae_assert_quad_is_valid, ae_mat2D_to_point(), ae_point_to_mat2D(), mat2D_alloc(), mat2D_copy(), mat2D_cross(), mat2D_free(), mat2D_normalize, mat2D_sub(), Quad::normals, and Quad::points.
ae_quad_transform_to_view()
Quad ae_quad_transform_to_view (Mat2D view_mat, Quad quad)
Transform a quad from world space to view space.
Applies view_mat to each vertex (homogeneous multiply with w=1). Returns the transformed quad; normals are not changed.
Parameters
view_mat View matrix (4x4).
quad World-space quad.
Returns
Quad View-space quad.
Definition at line 3271 of file Almog_Engine.h.
References AE_ASSERT, ae_assert_quad_is_valid, mat2D_alloc(), MAT2D_AT, mat2D_dot(), mat2D_free(), Quad::points, Point::w, Point::x, Point::y, and Point::z.
Referenced by ae_quad_project_world2screen().
ae_scene_free()
void ae_scene_free (Scene * scene)
Free all resources owned by a Scene.
Frees camera, matrices, and any allocated meshes in the in_world, projected, and original mesh arrays (triangles and quads). Does not free the Scene struct itself when passed by pointer.
Parameters
scene Scene to free.
Note
Assumes the game_state was initialized with zeros.
Definition at line 429 of file Almog_Engine.h.
References ae_camera_free(), Tri_mesh::elements, Quad_mesh::elements, Tri_mesh_array::elements, Quad_mesh_array::elements, Scene::in_world_quad_meshes, Scene::in_world_tri_meshes, Tri_mesh_array::length, Quad_mesh_array::length, mat2D_free(), Scene::original_quad_meshes, Scene::original_tri_meshes, Scene::proj_mat, Scene::projected_quad_meshes, Scene::projected_tri_meshes, Scene::up_direction, and Scene::view_mat.
Referenced by destroy_window().
ae_scene_init()
Scene ae_scene_init (int window_h, int window_w)
Create and initialize a Scene.
Initializes camera, up direction, default light and material, and allocates projection and view matrices. Caller must release resources with ae_scene_free.
Parameters
window_h Window height in pixels.
window_w Window width in pixels.
Returns
Scene An initialized scene object.
Definition at line 388 of file Almog_Engine.h.
References ae_camera_init(), ae_point_normalize_xyz(), ae_projection_mat_set(), ae_view_mat_set(), Camera::aspect_ratio, Material::c_ambi, Material::c_diff, Material::c_spec, Scene::camera, Camera::fov_deg, Light_source::light_direction_or_pos, Light_source::light_intensity, Scene::light_source0, mat2D_alloc(), MAT2D_AT, mat2D_fill(), Scene::material0, Scene::proj_mat, Material::specular_power_alpha, Scene::up_direction, Scene::view_mat, Point::w, Point::x, Point::y, Point::z, Camera::z_far, and Camera::z_near.
Referenced by setup_window().
ae_signed_dist_point_and_plane()
float ae_signed_dist_point_and_plane (Point p, Mat2D plane_p, Mat2D plane_n)
Signed distance from a point to a plane.
Computes dot(n, p) - dot(n, plane_p). The normal is not normalized internally; pass a normalized plane_n for distances in consistent units.
Parameters
p Point to evaluate.
plane_p Plane reference point (3x1).
plane_n Plane normal (3x1).
Returns
float Signed distance (>=0 is on the `inside` of the plane).
Definition at line 1807 of file Almog_Engine.h.
References ae_assert_point_is_valid, MAT2D_AT, Point::x, Point::y, and Point::z.
Referenced by ae_line_clip_with_plane(), ae_quad_clip_with_plane(), and ae_tri_clip_with_plane().
ae_tri_calc_light_intensity()
void ae_tri_calc_light_intensity (Tri * tri, Scene * scene, Lighting_mode lighting_mode)
Compute per-vertex lighting intensity for a triangle.
Implements a Phong-like model with ambient, diffuse, and specular terms, using material0 and light_source0 from the scene. When lighting_mode is AE_LIGHTING_FLAT, the average normal and triangle centroid are used for all vertices; when AE_LIGHTING_SMOOTH, each vertex normal and position is used. For directional light, light_direction_or_pos.w == 0; for point light, w != 0. Results are clamped to [0, 1].
Parameters
tri Triangle to update (tri->light_intensity[i] is written).
scene Scene providing light and material parameters.
lighting_mode Flat or smooth lighting mode.
Definition at line 1487 of file Almog_Engine.h.
References AE_LIGHTING_FLAT, AE_LIGHTING_SMOOTH, ae_mat2D_to_point(), ae_point_add_point, ae_point_dot_point, ae_point_mult, ae_point_normalize_xyz(), ae_point_sub_point, ae_tri_get_average_normal(), ae_tri_get_average_point(), Material::c_ambi, Material::c_diff, Material::c_spec, Scene::camera, Camera::current_position, Light_source::light_direction_or_pos, Tri::light_intensity, Light_source::light_intensity, Scene::light_source0, Scene::material0, Tri::normals, Tri::points, Material::specular_power_alpha, and Point::w.
Referenced by ae_tri_project_world2screen().
ae_tri_calc_normal()
void ae_tri_calc_normal (Mat2D normal, Tri tri)
Compute the face normal of a triangle.
normal must be a 3x1 vector. The function writes the normalized cross product of (p1 - p0) x (p2 - p0) into normal.
Parameters
normal Output 3x1 vector for the face normal.
tri Input triangle.
Definition at line 1086 of file Almog_Engine.h.
References AE_ASSERT, ae_assert_tri_is_valid, ae_point_to_mat2D(), Mat2D::cols, mat2D_alloc(), mat2D_calc_norma(), mat2D_cross(), mat2D_free(), mat2D_mult(), mat2D_sub(), Tri::points, and Mat2D::rows.
Referenced by ae_tri_project_world2screen().
ae_tri_clip_with_plane()
int ae_tri_clip_with_plane (Tri tri_in, Mat2D plane_p, Mat2D plane_n, Tri * tri_out1, Tri * tri_out2)
Clip a triangle against a plane.
Splits or discards the triangle tri_in against the plane defined by (plane_p, plane_n). plane_n is normalized inside the function.
Parameters
tri_in Input triangle.
plane_p Plane reference point (3x1).
plane_n Plane normal (3x1).
tri_out1 First output triangle (if any).
tri_out2 Second output triangle (if split).
Returns
int Number of output triangles: 0 (culled), 1, or 2. Returns -1 on error.
Definition at line 1838 of file Almog_Engine.h.
References ae_assert_tri_is_valid, ae_line_itersect_plane(), ae_point_to_mat2D(), ae_signed_dist_point_and_plane(), Tri::colors, mat2D_alloc(), mat2D_free(), mat2D_normalize, Tri::points, Tri::tex_points, Point::w, Point::x, and Point::y.
Referenced by ae_tri_mesh_project_world2screen(), and ae_tri_project_world2screen().
ae_tri_compare()
bool ae_tri_compare (Tri t1, Tri t2)
Compare two triangles for sorting by depth.
Returns true if t1 should come before t2 when sorting by the maximum z of their vertices (descending order).
Parameters
t1 First triangle.
t2 Second triangle.
Returns
bool true if t1 precedes t2, false otherwise.
Definition at line 3725 of file Almog_Engine.h.
References Tri::points, and Point::z.
Referenced by ae_tri_qsort().
ae_tri_create()
Tri ae_tri_create (Point p1, Point p2, Point p3)
Create a triangle from three points.
Parameters
p1 First vertex (world space).
p2 Second vertex (world space).
p3 Third vertex (world space).
Returns
Tri The created triangle with vertices set. Other fields are left uninitialized.
Definition at line 278 of file Almog_Engine.h.
References Tri::points.
ae_tri_get_average_normal()
Point ae_tri_get_average_normal (Tri tri)
Compute the average of the three vertex normals of a triangle.
Averages the three vertex normals and normalizes the result.
Parameters
tri Input triangle.
Returns
Point The averaged, normalized normal (w averaged but unused).
Definition at line 1041 of file Almog_Engine.h.
References ae_point_normalize_xyz(), Tri::normals, Point::w, Point::x, Point::y, and Point::z.
Referenced by ae_tri_calc_light_intensity().
ae_tri_get_average_point()
Point ae_tri_get_average_point (Tri tri)
Compute the average of the three vertices of a triangle.
Parameters
tri Input triangle.
Returns
Point The average point (x, y, z, w are simple averages).
Definition at line 1062 of file Almog_Engine.h.
References Tri::points, Point::w, Point::x, Point::y, and Point::z.
Referenced by ae_tri_calc_light_intensity().
ae_tri_mesh_appand_copy()
void ae_tri_mesh_appand_copy (Tri_mesh_array * mesh_array, Tri_mesh mesh)
Append a copy of a Tri_mesh into a Tri_mesh_array.
Creates a deep copy of mesh (triangles by value) and appends it to mesh_array (ADA array of meshes).
Parameters
mesh_array Destination mesh array to append into.
mesh Source triangle mesh to copy.
Definition at line 851 of file Almog_Engine.h.
References ada_appand, ada_init_array, Tri_mesh::elements, and Tri_mesh::length.
Referenced by setup().
ae_tri_mesh_create_copy()
void ae_tri_mesh_create_copy (Tri_mesh * des, Tri * src_elements, size_t len)
Append copies of triangles to a destination Tri_mesh (resets destination length first).
Appends len triangles from src_elements into the destination ADA array pointed by des.
Parameters
des Destination triangle mesh (ADA array). Will grow as needed.
src_elements Source array of triangles to copy from.
len Number of triangles to copy from src_elements.
Definition at line 299 of file Almog_Engine.h.
References ada_appand, and Tri_mesh::length.
ae_tri_mesh_flip_normals()
void ae_tri_mesh_flip_normals (Tri_mesh mesh)
Flip triangle winding and recompute per-vertex normals.
Swaps vertex order to invert winding, copies attributes accordingly, and recomputes normals.
Parameters
mesh Mesh to flip (modified in place).
Definition at line 1283 of file Almog_Engine.h.
References ae_tri_set_normals(), Tri::colors, Tri_mesh::elements, Tri_mesh::length, Tri::light_intensity, Tri::normals, Tri::points, Tri::tex_points, and Tri::to_draw.
ae_tri_mesh_get_from_file()
Tri_mesh ae_tri_mesh_get_from_file (char * file_path)
Load a triangle mesh from a file (OBJ or STL).
Dispatches to ae_tri_mesh_get_from_obj_file or ae_tri_mesh_get_from_stl_file based on file extension.
Parameters
file_path Path to the file (.obj, .stl, .STL).
Returns
Tri_mesh The loaded triangle mesh. Caller must free mesh.elements when done.
Definition at line 816 of file Almog_Engine.h.
References ae_tri_mesh_get_from_obj_file(), ae_tri_mesh_get_from_stl_file(), asm_get_word_and_cut(), ASM_MAX_LEN_LINE, and asm_str_in_str().
Referenced by setup().
ae_tri_mesh_get_from_obj_file()
Tri_mesh ae_tri_mesh_get_from_obj_file (char * file_path)
Load a triangle mesh from a Wavefront OBJ file.
Supports vertex positions (v). Face lines (f) with 3 or 4 vertices are parsed. Texture coordinates and normals in the file are ignored (a warning is printed once if present). Quads are triangulated as (0,1,2) and (2,3,0). Colors are set to white and to_draw is set to true.
Parameters
file_path Path to the OBJ file.
Returns
Tri_mesh The loaded triangle mesh. Caller must free mesh.elements when done.
Definition at line 540 of file Almog_Engine.h.
References ada_appand, ada_init_array, asm_get_line(), asm_get_next_word_from_line(), asm_get_word_and_cut(), asm_length(), ASM_MAX_LEN_LINE, asm_str_in_str(), Tri::colors, Curve::elements, Tri::light_intensity, Tri::points, Tri::to_draw, Point::x, Point::y, and Point::z.
Referenced by ae_tri_mesh_get_from_file().
ae_tri_mesh_get_from_quad_mesh()
Tri_mesh ae_tri_mesh_get_from_quad_mesh (Quad_mesh q_mesh)
Convert a Quad_mesh into a Tri_mesh.
Splits each quad into two triangles: (0,1,2) and (2,3,0), copying per-vertex attributes (points, colors, normals, light intensities).
Parameters
q_mesh Input quad mesh.
Returns
Tri_mesh Resulting triangle mesh. Caller must free mesh.elements when done.
Definition at line 875 of file Almog_Engine.h.
References ada_appand, ada_init_array, Tri::colors, Quad::colors, Quad_mesh::elements, Quad_mesh::length, Tri::light_intensity, Quad::light_intensity, Tri::normals, Quad::normals, Tri::points, Quad::points, Tri::to_draw, and Quad::to_draw.
ae_tri_mesh_get_from_stl_file()
Tri_mesh ae_tri_mesh_get_from_stl_file (char * file_path)
Load a triangle mesh from a binary STL file.
Reads binary STL (little-endian). Per-triangle normals from the file are negated to match the engine's convention and copied to each vertex normal. Colors are set to white and to_draw is set to true.
Parameters
file_path Path to the binary STL file.
Returns
Tri_mesh The loaded triangle mesh. Caller must free mesh.elements when done.
Definition at line 743 of file Almog_Engine.h.
References ada_appand, ada_init_array, Tri::colors, Tri::light_intensity, Tri::normals, Tri::points, STL_ATTRIBUTE_BITS_SIZE, STL_HEADER_SIZE, STL_NUM_SIZE, Tri::to_draw, Point::x, Point::y, and Point::z.
Referenced by ae_tri_mesh_get_from_file().
ae_tri_mesh_normalize()
void ae_tri_mesh_normalize (Tri_mesh mesh)
Normalize mesh coordinates to [-1, 1], centered at origin.
Uniformly scales and recenters the mesh so that the largest axis fits exactly into [-1, 1]. Other axes are scaled proportionally. Updates all vertices in place.
Parameters
mesh Triangle mesh to normalize (modified in place).
Definition at line 1244 of file Almog_Engine.h.
References ae_tri_mesh_set_bounding_box(), Tri_mesh::elements, Tri_mesh::length, Tri::points, Point::x, Point::y, and Point::z.
Referenced by setup().
ae_tri_mesh_project_world2screen()
void ae_tri_mesh_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Tri_mesh * des, Tri_mesh src, int window_w, int window_h, Scene * scene, Lighting_mode lighting_mode)
Project a triangle mesh from world to screen space with clipping.
Iterates over all triangles, applies near-plane and screen-edge clipping (top/right/bottom/left), and writes results into des. Triangles can be split by clipping, so des may end up with more elements than src.
Parameters
proj_mat Projection matrix (4x4).
view_mat View matrix (4x4).
des Output mesh (cleared and filled; ADA array grown as needed).
src Input world-space triangle mesh.
window_w Screen width in pixels.
window_h Screen height in pixels.
scene Scene (camera/light/material).
lighting_mode Flat or smooth lighting mode.
Definition at line 3151 of file Almog_Engine.h.
References ada_appand, ada_insert_unordered, ada_remove_unordered, ae_assert_tri_is_valid, ae_tri_clip_with_plane(), ae_tri_project_world2screen(), Tri_mesh::elements, Tri_mesh::length, mat2D_alloc(), MAT2D_AT, mat2D_fill(), and mat2D_free().
Referenced by update().
ae_tri_mesh_rotate_Euler_xyz()
void ae_tri_mesh_rotate_Euler_xyz (Tri_mesh mesh, float phi_deg, float theta_deg, float psi_deg)
Rotate a triangle mesh using XYZ Euler angles (degrees).
Applies DCM = Cz(psi_deg) * Cy(theta_deg) * Cx(phi_deg) to each vertex. Recomputes per-vertex normals afterward.
Parameters
mesh Triangle mesh to rotate (modified in place).
phi_deg Rotation about X axis, degrees.
theta_deg Rotation about Y axis, degrees.
psi_deg Rotation about Z axis, degrees.
Definition at line 1143 of file Almog_Engine.h.
References ae_tri_mesh_set_normals(), Tri_mesh::elements, Tri_mesh::length, mat2D_alloc(), MAT2D_AT, mat2D_dot(), mat2D_free(), mat2D_set_rot_mat_x(), mat2D_set_rot_mat_y(), mat2D_set_rot_mat_z(), Tri::points, Point::x, Point::y, and Point::z.
Referenced by setup().
ae_tri_mesh_set_bounding_box()
void ae_tri_mesh_set_bounding_box (Tri_mesh mesh, float * x_min, float * x_max, float * y_min, float * y_max, float * z_min, float * z_max)
Compute the axis-aligned bounding box of a triangle mesh.
Writes min/max for x, y, z across all vertices in the mesh.
Parameters
mesh Input triangle mesh.
x_min Output minimum x.
x_max Output maximum x.
y_min Output minimum y.
y_max Output maximum y.
z_min Output minimum z.
z_max Output maximum z.
Definition at line 1206 of file Almog_Engine.h.
References Tri_mesh::elements, Tri_mesh::length, Tri::points, Point::x, Point::y, and Point::z.
Referenced by ae_tri_mesh_normalize().
ae_tri_mesh_set_normals()
void ae_tri_mesh_set_normals (Tri_mesh mesh)
Recompute per-vertex normals for all triangles in a mesh.
Calls ae_tri_set_normals on each triangle.
Parameters
mesh Mesh to update (modified in place).
Definition at line 1321 of file Almog_Engine.h.
References ae_tri_set_normals(), Tri_mesh::elements, and Tri_mesh::length.
Referenced by ae_tri_mesh_rotate_Euler_xyz().
ae_tri_mesh_translate()
void ae_tri_mesh_translate (Tri_mesh mesh, float x, float y, float z)
Translate a triangle mesh by (x, y, z).
Adds the given offsets to each vertex in the mesh.
Parameters
mesh Triangle mesh to translate (modified in place).
x X-axis offset.
y Y-axis offset.
z Z-axis offset.
Definition at line 1121 of file Almog_Engine.h.
References Tri_mesh::elements, Tri_mesh::length, Tri::points, Point::x, Point::y, and Point::z.
ae_tri_project_world2screen()
Tri_mesh ae_tri_project_world2screen (Mat2D proj_mat, Mat2D view_mat, Tri tri, int window_w, int window_h, Scene * scene, Lighting_mode lighting_mode)
Project a single world-space triangle to screen space with clipping.
Computes lighting, back-face visibility, transforms to view space, clips against near plane, and projects to screen space. If clipping splits the triangle, multiple triangles may be returned.
Parameters
proj_mat Projection matrix (4x4).
view_mat View matrix (4x4).
tri World-space triangle.
window_w Screen width in pixels.
window_h Screen height in pixels.
scene Scene (camera for near plane, light/material for lighting).
lighting_mode Flat or smooth lighting mode.
Returns
Tri_mesh An ADA array of resulting screen-space triangles. Caller must free result.elements.
Definition at line 3038 of file Almog_Engine.h.
References ada_appand, ada_init_array, ae_assert_tri_is_valid, ae_point_project_view2screen(), ae_point_to_mat2D(), ae_tri_calc_light_intensity(), ae_tri_calc_normal(), ae_tri_clip_with_plane(), ae_tri_transform_to_view(), Scene::camera, Camera::current_position, Tri_mesh::elements, Tri_mesh::length, Tri::light_intensity, mat2D_alloc(), MAT2D_AT, mat2D_fill(), mat2D_free(), mat2D_sub(), mat2D_transpose(), Tri::normals, Tri::points, Tri::tex_points, Tri::to_draw, Point::w, Point::x, Point::y, Point::z, and Camera::z_near.
Referenced by ae_tri_mesh_project_world2screen().
ae_tri_qsort()
void ae_tri_qsort (Tri * v, int left, int right)
Quicksort an array of triangles by depth.
Sorts v[left..right] using ae_tri_compare (descending by max z).
Parameters
v Array of triangles to sort.
left Left index (inclusive).
right Right index (inclusive).
Definition at line 3742 of file Almog_Engine.h.
References ae_tri_compare(), and ae_tri_swap().
ae_tri_set_normals()
void ae_tri_set_normals (Tri * tri)
Compute and set per-vertex normals for a triangle.
For each vertex, computes the cross product of the adjacent edges around that vertex and normalizes it. Results are stored in tri->normals[i].
Parameters
tri Triangle whose normals will be computed and written.
Definition at line 998 of file Almog_Engine.h.
References ae_assert_tri_is_valid, ae_mat2D_to_point(), ae_point_to_mat2D(), mat2D_alloc(), mat2D_copy(), mat2D_cross(), mat2D_free(), mat2D_normalize, mat2D_sub(), Tri::normals, and Tri::points.
Referenced by ae_tri_mesh_flip_normals(), and ae_tri_mesh_set_normals().
ae_tri_swap()
void ae_tri_swap (Tri * v, int i, int j)
Swap two triangles in an array.
Parameters
v Array of triangles.
i Index of first element.
j Index of second element.
Definition at line 3706 of file Almog_Engine.h.
Referenced by ae_tri_qsort().
ae_tri_transform_to_view()
Tri ae_tri_transform_to_view (Mat2D view_mat, Tri tri)
Transform a triangle from world space to view space.
Applies view_mat to each vertex (homogeneous multiply with w=1). Returns the transformed triangle; normals are not changed.
Parameters
view_mat View matrix (4x4).
tri World-space triangle.
Returns
Tri View-space triangle.
Definition at line 2988 of file Almog_Engine.h.
References AE_ASSERT, ae_assert_tri_is_valid, mat2D_alloc(), MAT2D_AT, mat2D_dot(), mat2D_free(), Tri::points, Point::w, Point::x, Point::y, and Point::z.
Referenced by ae_tri_project_world2screen().
ae_view_mat_set()
void ae_view_mat_set (Mat2D view_mat, Camera camera, Mat2D up)
Build a right-handed view matrix from a Camera and up vector.
Computes camera basis (right, up, forward) from yaw/pitch/roll offsets and direction, applies offset_position along those axes to update current_position, then zeroes offset_position. Writes the resulting 4x4 view matrix.
Note
Although camera is passed by value, its Mat2D members (e.g. current_position, offset_position, camera_x/y/z) are modified in place due to internal pointer semantics of Mat2D.
Parameters
view_mat Output 4x4 view matrix.
camera Camera state (basis vectors and positions updated).
up World up direction (3x1).
Definition at line 2716 of file Almog_Engine.h.
References Camera::camera_x, Camera::camera_y, Camera::camera_z, Camera::current_position, Camera::direction, mat2D_add(), mat2D_alloc(), MAT2D_AT, mat2D_calc_norma(), mat2D_copy(), mat2D_cross(), mat2D_dot(), mat2D_dot_product(), mat2D_fill(), mat2D_free(), mat2D_mult(), mat2D_set_DCM_zyx(), mat2D_sub(), mat2D_transpose(), Camera::offset_position, Camera::pitch_offset_deg, Camera::roll_offset_deg, and Camera::yaw_offset_deg.
Referenced by ae_scene_init(), and update().
ae_z_buffer_copy_to_screen()
void ae_z_buffer_copy_to_screen (Mat2D_uint32 screen_mat, Mat2D inv_z_buffer)
Visualize an inverse-z buffer by writing a grayscale image.
Finds the min positive and max inverse-z in inv_z_buffer, maps the range to [0.1, 1.0], and writes an RGB grayscale value into screen_mat at each pixel. Values <= 0 are clamped to the minimum positive.
Parameters
screen_mat Output RGB image (Mat2D_uint32) 0xRRGGBB per pixel.
inv_z_buffer Input inverse-z values (Mat2D of doubles).
Definition at line 3785 of file Almog_Engine.h.
References ae_linear_map(), Mat2D::cols, MAT2D_AT, MAT2D_AT_UINT32, RGB_hexRGB, and Mat2D::rows.