src/include/display.c File Reference
#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include `Matrix2D.h`
#include <stdlib.h>
#include <stdint.h>
#include `Almog_Engine.h`
Classes
struct game_state_t
Macros
#define WINDOW_WIDTH (16 * 80)
#define WINDOW_HEIGHT (9 * 80)
#define FPS 100
#define FRAME_TARGET_TIME (1000 / FPS)
#define dprintSTRING(expr) printf(#expr ` = %s\n`, expr)
#define dprintCHAR(expr) printf(#expr ` = %c\n`, expr)
#define dprintINT(expr) printf(#expr ` = %d\n`, expr)
#define dprintD(expr) printf(#expr ` = %g\n`, expr)
#define dprintSIZE_T(expr) printf(#expr ` = %zu\n`, expr)
Functions
int initialize_window (game_state_t *game_state)
void setup_window (game_state_t *game_state)
void process_input_window (game_state_t *game_state)
void update_window (game_state_t *game_state)
void render_window (game_state_t *game_state)
void destroy_window (game_state_t *game_state)
void fix_framerate (game_state_t *game_state)
void setup (game_state_t *game_state)
void update (game_state_t *game_state)
void render (game_state_t *game_state)
void check_window_mat_size (game_state_t *game_state)
void copy_mat_to_surface_RGB (game_state_t *game_state)
int main ()
Macro Definition Documentation
dprintCHAR
#define dprintCHAR(expr) printf(#expr ` = %c\n`, expr)
Definition at line 25 of file display.c.
dprintD
#define dprintD(expr) printf(#expr ` = %g\n`, expr)
Definition at line 27 of file display.c.
dprintINT
#define dprintINT(expr) printf(#expr ` = %d\n`, expr)
Definition at line 26 of file display.c.
dprintSIZE_T
#define dprintSIZE_T(expr) printf(#expr ` = %zu\n`, expr)
Definition at line 28 of file display.c.
dprintSTRING
#define dprintSTRING(expr) printf(#expr ` = %s\n`, expr)
Definition at line 24 of file display.c.
FPS
#define FPS 100
Definition at line 17 of file display.c.
FRAME_TARGET_TIME
#define FRAME_TARGET_TIME (1000 / FPS)
Definition at line 21 of file display.c.
WINDOW_HEIGHT
#define WINDOW_HEIGHT (9 * 80)
Definition at line 13 of file display.c.
WINDOW_WIDTH
#define WINDOW_WIDTH (16 * 80)
Definition at line 9 of file display.c.
Function Documentation
check_window_mat_size()
void check_window_mat_size (game_state_t * game_state)
Definition at line 361 of file display.c.
References Camera::aspect_ratio, Scene::camera, Mat2D_uint32::cols, game_state_t::inv_z_buffer_mat, mat2D_alloc(), mat2D_alloc_uint32(), mat2D_free(), mat2D_free_uint32(), Mat2D_uint32::rows, game_state_t::scene, game_state_t::window, game_state_t::window_h, game_state_t::window_pixels_mat, game_state_t::window_surface, and game_state_t::window_w.
Referenced by update_window().
copy_mat_to_surface_RGB()
void copy_mat_to_surface_RGB (game_state_t * game_state)
Definition at line 376 of file display.c.
References Mat2D_uint32::cols, Mat2D_uint32::elements, Mat2D_uint32::rows, game_state_t::window_pixels_mat, and game_state_t::window_surface.
Referenced by render_window().
destroy_window()
void destroy_window (game_state_t * game_state)
Definition at line 316 of file display.c.
References ae_scene_free(), game_state_t::inv_z_buffer_mat, mat2D_free(), mat2D_free_uint32(), game_state_t::renderer, game_state_t::scene, game_state_t::window, game_state_t::window_pixels_mat, game_state_t::window_surface, and game_state_t::window_texture.
Referenced by main().
fix_framerate()
void fix_framerate (game_state_t * game_state)
Definition at line 333 of file display.c.
References game_state_t::delta_time, game_state_t::frame_target_time, game_state_t::previous_frame_time, and game_state_t::to_limit_fps.
Referenced by update_window().
initialize_window()
int initialize_window (game_state_t * game_state)
Definition at line 137 of file display.c.
References game_state_t::renderer, game_state_t::window, game_state_t::window_h, and game_state_t::window_w.
Referenced by main().
main()
int main ()
Definition at line 88 of file display.c.
References game_state_t::a_was_pressed, game_state_t::const_fps, game_state_t::d_was_pressed, game_state_t::delta_time, destroy_window(), game_state_t::e_was_pressed, game_state_t::elapsed_time, FPS, game_state_t::fps, FRAME_TARGET_TIME, game_state_t::frame_target_time, game_state_t::game_is_running, initialize_window(), game_state_t::left_button_pressed, game_state_t::previous_frame_time, process_input_window(), game_state_t::q_was_pressed, render_window(), game_state_t::renderer, game_state_t::s_was_pressed, setup_window(), game_state_t::space_bar_was_pressed, game_state_t::to_clear_renderer, game_state_t::to_limit_fps, game_state_t::to_render, game_state_t::to_update, update_window(), game_state_t::w_was_pressed, game_state_t::window, game_state_t::window_h, WINDOW_HEIGHT, game_state_t::window_w, and WINDOW_WIDTH.
process_input_window()
void process_input_window (game_state_t * game_state)
Definition at line 186 of file display.c.
References ae_camera_reset_pos(), Scene::camera, game_state_t::game_is_running, game_state_t::left_button_pressed, MAT2D_AT, Camera::offset_position, Camera::pitch_offset_deg, game_state_t::previous_frame_time, Camera::roll_offset_deg, game_state_t::scene, game_state_t::space_bar_was_pressed, game_state_t::to_render, and game_state_t::to_update.
Referenced by main().
render()
void render (game_state_t * game_state)
Definition at line 32 of file grid_example.c.
References ADL_DEFAULT_OFFSET_ZOOM, adl_grid_draw(), adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal(), Tri_mesh_array::elements, grid_proj, Scene::in_world_tri_meshes, game_state_t::inv_z_buffer_mat, Tri_mesh::length, Tri_mesh_array::length, Scene::projected_tri_meshes, game_state_t::scene, and game_state_t::window_pixels_mat.
Referenced by render_window().
render_window()
void render_window (game_state_t * game_state)
Definition at line 295 of file display.c.
References Mat2D::cols, Mat2D_uint32::cols, copy_mat_to_surface_RGB(), Mat2D::elements, Mat2D_uint32::elements, game_state_t::inv_z_buffer_mat, render(), Mat2D::rows, Mat2D_uint32::rows, game_state_t::to_clear_renderer, game_state_t::window, and game_state_t::window_pixels_mat.
Referenced by main().
setup()
void setup (game_state_t * game_state)
Definition at line 14 of file grid_example.c.
References ada_appand, ada_init_array, adl_cartesian_grid_create(), ae_tri_mesh_appand_copy(), ae_tri_mesh_get_from_file(), ae_tri_mesh_normalize(), ae_tri_mesh_rotate_Euler_xyz(), ASM_MAX_LEN_LINE, game_state_t::const_fps, Tri_mesh_array::elements, grid, grid_proj, Scene::in_world_tri_meshes, Tri_mesh::length, Tri_mesh_array::length, Scene::original_tri_meshes, Scene::projected_tri_meshes, game_state_t::scene, and game_state_t::to_limit_fps.
Referenced by setup_window().
setup_window()
void setup_window (game_state_t * game_state)
Definition at line 170 of file display.c.
References ae_scene_init(), game_state_t::inv_z_buffer_mat, mat2D_alloc(), mat2D_alloc_uint32(), game_state_t::scene, setup(), game_state_t::window, game_state_t::window_h, game_state_t::window_pixels_mat, game_state_t::window_surface, and game_state_t::window_w.
Referenced by main().
update()
void update (game_state_t * game_state)
Definition at line 23 of file grid_example.c.
References ae_grid_project_world2screen(), AE_LIGHTING_FLAT, ae_projection_mat_set(), ae_tri_mesh_project_world2screen(), ae_view_mat_set(), Camera::aspect_ratio, Scene::camera, Tri_mesh_array::elements, Camera::fov_deg, grid, grid_proj, Scene::in_world_tri_meshes, Tri_mesh_array::length, Scene::proj_mat, Scene::projected_tri_meshes, game_state_t::scene, Scene::up_direction, Scene::view_mat, game_state_t::window_h, game_state_t::window_w, Camera::z_far, and Camera::z_near.
Referenced by update_window().
update_window()
void update_window (game_state_t * game_state)
Definition at line 267 of file display.c.
References check_window_mat_size(), game_state_t::const_fps, game_state_t::delta_time, game_state_t::elapsed_time, fix_framerate(), game_state_t::fps, game_state_t::frame_target_time, game_state_t::to_limit_fps, update(), game_state_t::window, game_state_t::window_h, and game_state_t::window_w.
Referenced by main().