src/grid_example.c File Reference
#include `./include/display.c`
#include `./include/Matrix2D.h`
#include `./include/Almog_Draw_Library.h`
#include `./include/Almog_Engine.h`
Macros
#define SETUP
#define UPDATE
#define RENDER
#define MATRIX2D_IMPLEMENTATION
#define ALMOG_DRAW_LIBRARY_IMPLEMENTATION
#define ALMOG_ENGINE_IMPLEMENTATION
Functions
void setup (game_state_t *game_state)
void update (game_state_t *game_state)
void render (game_state_t *game_state)
Variables
Grid grid
Grid grid_proj
Macro Definition Documentation
ALMOG_DRAW_LIBRARY_IMPLEMENTATION
#define ALMOG_DRAW_LIBRARY_IMPLEMENTATION
Definition at line 7 of file grid_example.c.
ALMOG_ENGINE_IMPLEMENTATION
#define ALMOG_ENGINE_IMPLEMENTATION
Definition at line 9 of file grid_example.c.
MATRIX2D_IMPLEMENTATION
#define MATRIX2D_IMPLEMENTATION
Definition at line 5 of file grid_example.c.
RENDER
#define RENDER
Definition at line 3 of file grid_example.c.
SETUP
#define SETUP
Definition at line 1 of file grid_example.c.
UPDATE
#define UPDATE
Definition at line 2 of file grid_example.c.
Function Documentation
render()
void render (game_state_t * game_state)
Definition at line 32 of file grid_example.c.
References ADL_DEFAULT_OFFSET_ZOOM, adl_grid_draw(), grid_proj, and game_state_t::window_pixels_mat.
setup()
void setup (game_state_t * game_state)
Definition at line 14 of file grid_example.c.
References adl_cartesian_grid_create(), game_state_t::const_fps, grid, and grid_proj.
update()
void update (game_state_t * game_state)
Definition at line 23 of file grid_example.c.
References ae_grid_project_world2screen(), ae_projection_mat_set(), ae_view_mat_set(), Camera::aspect_ratio, Scene::camera, Camera::fov_deg, grid, grid_proj, Scene::proj_mat, game_state_t::scene, Scene::up_direction, Scene::view_mat, game_state_t::window_h, game_state_t::window_w, Camera::z_far, and Camera::z_near.
Variable Documentation
grid
Grid grid
Definition at line 12 of file grid_example.c.
Referenced by adl_cartesian_grid_create(), adl_grid_draw(), setup(), and update().
grid_proj
Grid grid_proj
Definition at line 13 of file grid_example.c.
Referenced by render(), setup(), and update().