src/temp.c File Reference
#include `./include/display.c`
#include `./include/Matrix2D.h`
#include `./include/Almog_Draw_Library.h`
#include `./include/Almog_Engine.h`
Macros
#define SETUP
#define UPDATE
#define RENDER
#define MATRIX2D_IMPLEMENTATION
#define ALMOG_DRAW_LIBRARY_IMPLEMENTATION
#define ALMOG_ENGINE_IMPLEMENTATION
Functions
void setup (game_state_t *game_state)
void update (game_state_t *game_state)
void render (game_state_t *game_state)
Macro Definition Documentation
ALMOG_DRAW_LIBRARY_IMPLEMENTATION
#define ALMOG_DRAW_LIBRARY_IMPLEMENTATION
Definition at line 7 of file temp.c.
ALMOG_ENGINE_IMPLEMENTATION
#define ALMOG_ENGINE_IMPLEMENTATION
Definition at line 9 of file temp.c.
MATRIX2D_IMPLEMENTATION
#define MATRIX2D_IMPLEMENTATION
Definition at line 5 of file temp.c.
RENDER
#define RENDER
Definition at line 3 of file temp.c.
SETUP
#define SETUP
Definition at line 1 of file temp.c.
UPDATE
#define UPDATE
Definition at line 2 of file temp.c.
Function Documentation
render()
void render (game_state_t * game_state)
Definition at line 63 of file temp.c.
References ADL_DEFAULT_OFFSET_ZOOM, adl_tri_mesh_fill_Pinedas_rasterizer_interpolate_normal(), Tri_mesh_array::elements, game_state_t::inv_z_buffer_mat, Tri_mesh_array::length, Scene::projected_tri_meshes, game_state_t::scene, and game_state_t::window_pixels_mat.
Referenced by render_window().
setup()
void setup (game_state_t * game_state)
Definition at line 12 of file temp.c.
References ada_appand, ada_init_array, ae_tri_mesh_appand_copy(), ae_tri_mesh_get_from_file(), ae_tri_mesh_normalize(), ae_tri_mesh_rotate_Euler_xyz(), Tri_mesh_array::elements, Scene::in_world_tri_meshes, Tri_mesh::length, Tri_mesh_array::length, MAX_LEN_LINE, Scene::original_tri_meshes, Scene::projected_tri_meshes, game_state_t::scene, and game_state_t::to_limit_fps.
Referenced by setup_window().
update()
void update (game_state_t * game_state)
Definition at line 49 of file temp.c.
References AE_LIGHTING_FLAT, ae_projection_mat_set(), ae_tri_mesh_project_world2screen(), ae_view_mat_set(), Camera::aspect_ratio, Scene::camera, Tri_mesh_array::elements, Camera::fov_deg, Scene::in_world_tri_meshes, Tri_mesh_array::length, Scene::proj_mat, Scene::projected_tri_meshes, game_state_t::scene, Scene::up_direction, Scene::view_mat, game_state_t::window_h, game_state_t::window_w, Camera::z_far, and Camera::z_near.
Referenced by update_window().